### ISSUE TITLE
Module synthesis: Problem processing the data

### ISSUE THREAD

**Issue by AntonioCaroppos** [marytts/marytts#1021]
Hello!

To make sure my setup was fine, I built the arctic voice, and it was perfectly fine. 

Then I built my own voice, and compiled fine, I didn't use a custom dictionary. 

Now I wanted to make it speak, and I get the following error. 
What could I check to find out what is going wrong here?

```
2020-09-01 14:11:25,109 [I/O dispatcher 2] INFO  marytts.server Connection from null
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server New synthesis request: /process
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_JetPilot_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Rate_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Stadium_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Stadium_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Volume_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Chorus_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     VOICE_SELECTIONS=my_voice de female unitselection general
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Add_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_FIRFilter_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     AUDIO=WAVE_FILE
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Whisper_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_JetPilot_parameters=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Stadium_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Whisper_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     exampleTexts=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Robot_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Robot_parameters=amount:100.0;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_FIRFilter_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Rate_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_TractScaler_parameters=amount:1.5;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Volume_parameters=amount:2.0;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Chorus_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Stadium_parameters=amount:100.0
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Chorus_parameters=delay1:466;amp1:0.54;delay2:600;amp2:-0.10;delay3:250;amp3:0.30
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Robot_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Add_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Scale_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Rate_parameters=durScale:1.5;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_FIRFilter_parameters=type:3;fc1:500.0;fc2:2000.0
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_JetPilot_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Whisper_parameters=amount:100.0;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_JetPilot_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Volume_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     HELP_TEXT=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     AUDIO_OUT=WAVE_FILE
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     OUTPUT_TYPE=AUDIO
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Add_parameters=f0Add:50.0;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_FIRFilter_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_TractScaler_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     OUTPUT_TEXT=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Volume_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Scale_selected=
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Scale_parameters=f0Scale:2.0;
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Scale_default=Default
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_TractScaler_help=Help
2020-09-01 14:11:25,110 [I/O dispatcher 2] DEBUG marytts.server     effect_Robot_selected=
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     effect_Chorus_help=Help
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     effect_TractScaler_selected=
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     INPUT_TEXT=test
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     effect_Whisper_default=Default
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     VOICE=my_voice
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     LOCALE=de
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     effect_Rate_default=Default
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     effect_F0Add_help=Help
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server     INPUT_TYPE=TEXT
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.server No audio effects requested
2020-09-01 14:11:25,111 [I/O dispatcher 2] INFO  marytts.R 4 New request (input type "TEXT", output type "AUDIO", voice "my_voice", effect "", audio "WAVE")
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.IO Setting text input: test
2020-09-01 14:11:25,111 [I/O dispatcher 2] INFO  marytts.server Read: test
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.R 4 Now converting the following input data from TEXT to RAWMARYXML:
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.IO Writing Text output:
test
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.R 4 Determining which modules to use
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module TextToMaryXML converts TEXT into RAWMARYXML (locale de, voice my_voice)
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry found path through modules
2020-09-01 14:11:25,111 [I/O dispatcher 2] INFO  marytts.R 4 Handling request using the following modules:
2020-09-01 14:11:25,111 [I/O dispatcher 2] INFO  marytts.R 4 - TextToMaryXML (marytts.modules.TextToMaryXML)
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.IO Writing Text output:
test
2020-09-01 14:11:25,111 [I/O dispatcher 2] INFO  marytts.R 4 Next module: TextToMaryXML
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.TextToMaryXML textNodeString=`test'
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.R 4 Now splitting the following RAWMARYXML data into chunks:
2020-09-01 14:11:25,111 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
test
</p>
</maryxml>

2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.R 4 Now converting the following input data from RAWMARYXML to AUDIO:
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
test
</p>
</maryxml>

2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.R 4 Determining which modules to use
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module JTokeniser converts RAWMARYXML into TOKENS (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module Preprocess converts TOKENS into WORDS (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module OpenNLPPosTagger converts WORDS into PARTSOFSPEECH (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module JPhonemiser_de converts PARTSOFSPEECH into PHONEMES (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module Prosody converts PHONEMES into INTONATION (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module PronunciationModel converts INTONATION into ALLOPHONES (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module AcousticModeller converts ALLOPHONES into ACOUSTPARAMS (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry Module Synthesis converts ACOUSTPARAMS into AUDIO (locale de, voice my_voice)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.ModuleRegistry found path through modules
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 Handling request using the following modules:
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - JTokeniser (marytts.language.de.JTokeniser)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - Preprocess (marytts.language.de.Preprocess)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - OpenNLPPosTagger (marytts.modules.OpenNLPPosTagger)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - JPhonemiser_de (marytts.language.de.JPhonemiser)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - Prosody (marytts.language.de.Prosody)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - PronunciationModel (marytts.language.de.Postlex)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - AcousticModeller (marytts.modules.AcousticModeller)
2020-09-01 14:11:25,112 [I/O dispatcher 2] INFO  marytts.R 4 - Synthesis (marytts.modules.Synthesis)
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,112 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
test
</p>
</maryxml>

2020-09-01 14:11:25,113 [I/O dispatcher 2] INFO  marytts.R 4 Next module: JTokeniser
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t>
test
</t>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,113 [I/O dispatcher 2] INFO  marytts.R 4 Next module: Preprocess
2020-09-01 14:11:25,113 [I/O dispatcher 2] INFO  marytts.Preprocess Expanding say-as elements...
2020-09-01 14:11:25,113 [I/O dispatcher 2] INFO  marytts.Preprocess Matching and expanding patterns...
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.MultiWordEP@70cf32e3 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.NetEP@5a59ca5e to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.CompositeEP@4bdeaabb to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.DateEP@6c4906d3 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.TimeEP@65987993 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.DurationEP@71075444 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.CurrencyEP@4f32a3ad to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.MeasureEP@6b695b06 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.TelephoneEP@4d1bf319 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.AbbrevEP@6f53b8a to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.NumberEP@5c80cf32 to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.Preprocess Now applying ep marytts.language.de.preprocess.SpecialCharEP@7d900ecf to token test 
2020-09-01 14:11:25,113 [I/O dispatcher 2] INFO  marytts.Preprocess Done.
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,113 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t>
test
</t>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,114 [I/O dispatcher 2] INFO  marytts.R 4 Next module: OpenNLPPosTagger
2020-09-01 14:11:25,114 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,114 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t pos="VVFIN">
test
</t>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,114 [I/O dispatcher 2] INFO  marytts.R 4 Next module: JPhonemiser_de
2020-09-01 14:11:25,114 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<t g2p_method="lexicon" ph="' t E s t" pos="VVFIN">
test
</t>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,115 [I/O dispatcher 2] INFO  marytts.R 4 Next module: Prosody
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.Prosody Processing next sentence
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.Prosody Now looking at token `test'
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.Prosody insertBoundary: after token `test', tone L-%, bi 5
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.Prosody Starting treewalker at token test
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.Prosody tw found a boundary
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,115 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<phrase>
<t accent="*" g2p_method="lexicon" ph="' t E s t" pos="VVFIN">
test
</t>
<boundary breakindex="5" tone="L-%"/>
</phrase>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,116 [I/O dispatcher 2] INFO  marytts.R 4 Next module: PronunciationModel
2020-09-01 14:11:25,116 [I/O dispatcher 2] DEBUG marytts.PronunciationModel Getting xml-data from document finished.
2020-09-01 14:11:25,116 [I/O dispatcher 2] DEBUG marytts.PronunciationModel Setting the changed xml document finished.
2020-09-01 14:11:25,116 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,116 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<phrase>
<t accent="*" g2p_method="lexicon" ph="' t E s t" pos="VVFIN">
test
<syllable accent="*" ph="t E s t" stress="1">
<ph p="t"/>
<ph p="E"/>
<ph p="s"/>
<ph p="t"/>
</syllable>
</t>
<boundary breakindex="5" tone="L-%"/>
</phrase>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,116 [I/O dispatcher 2] INFO  marytts.R 4 Next module: AcousticModeller
2020-09-01 14:11:25,117 [I/O dispatcher 2] DEBUG marytts.AcousticModeller 
Applying prosody modification if any:
2020-09-01 14:11:25,118 [I/O dispatcher 2] DEBUG marytts.R 4 Handing the following data to the next module:
2020-09-01 14:11:25,118 [I/O dispatcher 2] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
<p>
<s>
<phrase>
<t accent="*" g2p_method="lexicon" ph="' t E s t" pos="VVFIN">
test
<syllable accent="*" ph="t E s t" stress="1">
<ph d="139" end="0.13908" p="t"/>
<ph d="160" end="0.299441" f0="(0,220) (50,171) (100,173)" p="E"/>
<ph d="121" end="0.419986" p="s"/>
<ph d="35" end="0.4546693" p="t"/>
</syllable>
</t>
<boundary breakindex="5" duration="400" tone="L-%"/>
</phrase>
</s>
</p>
</maryxml>

2020-09-01 14:11:25,118 [I/O dispatcher 2] INFO  marytts.R 4 Next module: Synthesis
2020-09-01 14:11:25,118 [I/O dispatcher 2] DEBUG marytts.UnitSelectionSynthesizer Selecting units with a marytts.unitselection.select.DiphoneUnitSelector from a marytts.unitselection.data.DiphoneUnitDatabase
2020-09-01 14:11:25,119 [I/O dispatcher 2] DEBUG marytts.Viterbi Viterbi running with beam size 100
2020-09-01 14:11:25,119 [I/O dispatcher 2] DEBUG marytts.DiphoneUnitDatabase For target _-t, selected 4724 units
2020-09-01 14:11:25,120 [I/O dispatcher 2] ERROR marytts.server Processing failed.
java.lang.Exception: Module Synthesis: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 43991
	at marytts.unitselection.data.DiphoneUnitDatabase.getCandidates(DiphoneUnitDatabase.java:93)
	at marytts.unitselection.select.viterbi.Viterbi.apply(Viterbi.java:224)
	at marytts.unitselection.select.UnitSelector.selectUnits(UnitSelector.java:115)
	at marytts.unitselection.UnitSelectionSynthesizer.synthesize(UnitSelectionSynthesizer.java:177)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:527)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:252)
	at marytts.modules.Synthesis.process(Synthesis.java:222)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more
2020-09-01 14:11:25,121 [I/O dispatcher 2] DEBUG marytts.http Returning HTTP status 500: Processing failed.
java.lang.Exception: Module Synthesis: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 43991
	at marytts.unitselection.data.DiphoneUnitDatabase.getCandidates(DiphoneUnitDatabase.java:93)
	at marytts.unitselection.select.viterbi.Viterbi.apply(Viterbi.java:224)
	at marytts.unitselection.select.UnitSelector.selectUnits(UnitSelector.java:115)
	at marytts.unitselection.UnitSelectionSynthesizer.synthesize(UnitSelectionSynthesizer.java:177)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:527)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:252)
	at marytts.modules.Synthesis.process(Synthesis.java:222)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more

2020-09-01 14:11:25,121 [I/O dispatcher 2] INFO  marytts.server Request couldn't be handled successfully.
```

**Comment by psibre** [comment]
Thanks for the detailed debug output!
My guess is there might be a mismatch in the units in the contents of your unit file.
How did you build your unit selection voice? Which version of the voicebuilding plugin or voice import tools did you use?

**Comment by AntonioCaroppos** [comment]
I have built the voice using the 5.3 branch. 

marytts.tools.voiceimport.DatabaseImportMain

Which other info do you need?

**Comment by AntonioCaroppos** [comment]
Is there an earlier version of the unit selection voice building that worked fine?

**Comment by psibre** [comment]
That depends on whether it's a data problem or a bug...

Is your data open?

**Comment by AntonioCaroppos** [comment]
No, it's not open. Do you want me to provide it to you in private?

**Comment by AntonioCaroppos** [comment]
May I send it to you?

**Comment by AntonioCaroppos** [comment]
No matter how many sentences I use during voice building, during synthesis it always says "4724 units":

`    2020-09-09 20:44:05,502 [I/O dispatcher 4] DEBUG marytts.DiphoneUnitDatabase For target _-d, selected 4724 units`

Even when I use only 1 sentence during building, it says "selected 4724 units".

**Comment by psibre** [comment]
Sounds like your voicebuilding project might be in an undefined/invalid state... Make sure you have your data backed up, then I would recommend to `./gradlew clean build`.

**Comment by AntonioCaroppos** [comment]
gradlew clean build is only available in branch 6. 
I'm using branch 5.

How do I do this with branch 5, please?

**Comment by AntonioCaroppos** [comment]
Yes, my voicebuilding was not really clean. I cleaned everything and started from scratch, then it worked. Thank you!
