### ISSUE TITLE
MaryTTS server refusing connection -- Too many open files

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#114]
Under certain conditions (see below), a running MaryTTS server may may become unresponsive, failing to accept any further requests:

```
marytts.server Problem with HTTP connection
org.apache.http.nio.reactor.IOReactorException: Failure accepting connection
    at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processEvent(DefaultListeningIOReactor.java:133)
    at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processEvents(DefaultListeningIOReactor.java:113)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:315)
    at marytts.server.http.MaryHttpServer.run(MaryHttpServer.java:225)
    at marytts.server.Mary.main(Mary.java:544)
Caused by: java.io.IOException: Too many open files
    at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
    at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:163)
    at org.apache.http.impl.nio.reactor.DefaultListeningIOReactor.processEvent(DefaultListeningIOReactor.java:129)
    ... 4 more
```

This stacktrace is from a stress test, running MaryTTS on a 16-core compute server with `bin/marytts-server.sh -Dserver.http.parallelthreads=32 -Dlog4j.logger.marytts=INFO,stderr -Xmx4g` and synthesizing with 100 parallel client threads.
Perhaps this thread is relevant here:
http://httpcomponents.10934.n7.nabble.com/Too-Many-Open-Files-Exception-td6659.html

**Comment by seblemaguer** [comment]
The current server architecture is going to be abandonned in the next version
