### ISSUE TITLE
TimelineReader barfs if header is too big

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#117]
As reported by @sathishpc, the TimelineReader cannot handle headers that are bigger than the hard-coded limit of 64k:

```
Running DurationCARTTrainer
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot load timeline file from /path/to/voice/mary/timeline_waveforms.mry
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:128)
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:105)
    at marytts.tools.voiceimport.DurationCARTTrainer.compute(DurationCARTTrainer.java:136)
    at marytts.tools.voiceimport.DatabaseImportMain.main(DatabaseImportMain.java:465)
Caused by: marytts.exceptions.MaryConfigurationException: File seems corrupt: index is expected after data, not before
    at marytts.unitselection.data.TimelineReader.load(TimelineReader.java:192)
    at marytts.unitselection.data.TimelineReader.<init>(TimelineReader.java:126)
    ... 3 more
```

**Comment by Rootex** [comment]
I guess solving this issues is not as easy as increasing the size of the bytebuffer as there can be some constraints to consider if files that big are to be handle. Is there a proposed solution to this or i can go ahead to test with bigger files after increasing the buffer size.
