### ISSUE TITLE
New Voice Error

### ISSUE THREAD

**Issue by karthikkrishnanv** [marytts/marytts#136]
Hello all

I have built a new English voice and am able to install it. When I try to use it with a test string, I see the error below. Can anyone point out how to debug this or any tips on overcoming this ?

```
Exception in thread "main" marytts.exceptions.SynthesisException: java.io.IOException: Error message from server:
java.lang.Exception: Module AcousticModeller: Problem processing the data.
    at marytts.server.Request.processOneChunk(Request.java:551)
    at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
    at marytts.server.Request.process(Request.java:336)
    at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
    at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
    at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
    at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
    at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
    at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
    at java.lang.Thread.run(Thread.java:679)
Caused by: marytts.exceptions.SynthesisException: Could not apply F0 model
    at marytts.modules.AcousticModeller.process(AcousticModeller.java:211)
    at marytts.server.Request.processOneChunk(Request.java:549)
    ... 19 more
Caused by: marytts.exceptions.MaryConfigurationException: Error generating F0 out of HMMs trees and pdfs. 
    at marytts.modules.acoustic.HMMModel.predictAndSetF0(HMMModel.java:328)
    at marytts.modules.acoustic.HMMModel.applyFromTo(HMMModel.java:174)
    at marytts.modules.AcousticModeller.process(AcousticModeller.java:209)
    ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 57
    at marytts.htsengine.HTSPStream.getPar(HTSPStream.java:169)
    at marytts.htsengine.HTSParameterGeneration.setRealisedF0(HTSParameterGeneration.java:622)
    at marytts.htsengine.HTSParameterGeneration.htsMaximumLikelihoodParameterGeneration(HTSParameterGeneration.java:324)
    at marytts.htsengine.HTSParameterGeneration.htsMaximumLikelihoodParameterGeneration(HTSParameterGeneration.java:159)
    at marytts.modules.acoustic.HMMModel.predictAndSetF0(HMMModel.java:282)
    ... 22 more
</pre></body></html>
    at marytts.client.RemoteMaryInterface.generateAudio(RemoteMaryInterface.java:252)
    at example.MaryTTSRemote.main(MaryTTSRemote.java:49)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module AcousticModeller: Problem processing the data.
    at marytts.server.Request.processOneChunk(Request.java:551)
    at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
    at marytts.server.Request.process(Request.java:336)
    at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
    at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
    at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
    at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
    at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
    at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
    at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
    at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
    at java.lang.Thread.run(Thread.java:679)
Caused by: marytts.exceptions.SynthesisException: Could not apply F0 model
    at marytts.modules.AcousticModeller.process(AcousticModeller.java:211)
    at marytts.server.Request.processOneChunk(Request.java:549)
    ... 19 more
Caused by: marytts.exceptions.MaryConfigurationException: Error generating F0 out of HMMs trees and pdfs. 
    at marytts.modules.acoustic.HMMModel.predictAndSetF0(HMMModel.java:328)
    at marytts.modules.acoustic.HMMModel.applyFromTo(HMMModel.java:174)
    at marytts.modules.AcousticModeller.process(AcousticModeller.java:209)
    ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 57
    at marytts.htsengine.HTSPStream.getPar(HTSPStream.java:169)
    at marytts.htsengine.HTSParameterGeneration.setRealisedF0(HTSParameterGeneration.java:622)
    at marytts.htsengine.HTSParameterGeneration.htsMaximumLikelihoodParameterGeneration(HTSParameterGeneration.java:324)
    at marytts.htsengine.HTSParameterGeneration.htsMaximumLikelihoodParameterGeneration(HTSParameterGeneration.java:159)
    at marytts.modules.acoustic.HMMModel.predictAndSetF0(HMMModel.java:282)
    ... 22 more
</pre></body></html>
    at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:440)
    at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:484)
    at marytts.client.MaryClient.process(MaryClient.java:682)
    at marytts.client.RemoteMaryInterface.processStringToBytes(RemoteMaryInterface.java:272)
    at marytts.client.RemoteMaryInterface.generateAudio(RemoteMaryInterface.java:249)
    ... 1 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1403)
    at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:431)
    ... 5 more
-------------------------
```

**Comment by Munzey** [comment]
@seblemaguer maybe you have an idea?
