### ISSUE TITLE
Error when using cmu-rms-hsmm and cmu-bdl-hsmm voices

### ISSUE THREAD

**Issue by srimovila** [marytts/marytts#138]
I am running into the following error when using cmu-rms-hsmm
and cmu-bdl-hsmm voices with MaryTTS 5.0.

_Unsupported conversion: PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2
bytes/frame, little-endian from PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2
bytes/frame, little-endian_

cmu-slt-hsmm is working fine, though. I am
using voice-cmu-bdl-hsmm-5.0-SNAPSHOT.jar
and voice-cmu-rms-hsmm-5.0-SNAPSHOT.jar that I downloaded
from http://mary.dfki.de/download/5.0-SNAPSHOT/

I am using Java 1.6 on windows. Please let me know if you want me to send you an eclipse project with minimal code to reproduce this issue.

The source code is below.

import java.util.Locale;

import javax.sound.sampled.*;

import marytts.LocalMaryInterface;
import marytts.util.data.audio.MaryAudioUtils;
public class Test {
 public static void main(String[] args) {
 try {
LocalMaryInterface marytts = new LocalMaryInterface();
marytts.setLocale(Locale.US);
 //marytts.setVoice("cmu-slt-hsmm");
marytts.setVoice("cmu-rms-hsmm");
 //marytts.setVoice("cmu-bdl-hsmm");
 AudioInputStream audio = marytts.generateAudio("Hello World!");
 MaryAudioUtils.writeWavFile(MaryAudioUtils.getSamplesAsDoubleArray(audio),
"thisIsMyText.wav", audio.getFormat());
 } catch (Exception e) {
 e.printStackTrace();
 }
}
}

The complete stack trace is below.

marytts.exceptions.SynthesisException: cannot process
at marytts.LocalMaryInterface.process(LocalMaryInterface.java:378)
 at marytts.LocalMaryInterface.generateAudio(LocalMaryInterface.java:306)
at Test.main(Test.java:17)
Caused by: java.lang.Exception: Module Synthesis: Problem processing the
data.
at marytts.server.Request.processOneChunk(Request.java:551)
 at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
at marytts.server.Request.process(Request.java:336)
 at marytts.LocalMaryInterface.process(LocalMaryInterface.java:376)
... 2 more
Caused by: javax.sound.sampled.UnsupportedAudioFileException: Conversion
from audio format PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame,
little-endian to requested audio format PCM_SIGNED 48000.0 Hz, 16 bit,
mono, 2 bytes/frame, little-endian not supported.
Unsupported conversion: PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame,
little-endian from PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame,
little-endian
at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:288)
 at marytts.modules.Synthesis.process(Synthesis.java:232)
at marytts.server.Request.processOneChunk(Request.java:549)
 ... 5 more

Please advise. Thanks in advance for your help.

Best Regards,
Sri

**Comment by seblemaguer** [comment]
I don't manage to reproduce this error with the 5.2, therefore I suspect it was solved in between. If you have this error again don't hesitate to reopen this issue
