### ISSUE TITLE
Java Runtime exception when uploading the allophones.xml for New Language support for Sinhala (si_LK)

### ISSUE THREAD

**Issue by luckyjkh** [marytts/marytts#141]
Hi,

I'm using openMary TTS 5.0 version
Operating System: Ubuntu Linux
Java version: 1.7.0

And I successfully completed up to step 2.2 in New Language Support for Sinhala.
I downloaded allophones_en-US.xml and edited it for Sinhala and created allophones.xml file.
Then I executed transcription.sh and selected the allophones.xml through the TranscriptionGUI (hoping to load wordList from mysql table next). But it gave the following java runtime errors after selecting the allophones.xml file. 

Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at marytts.util.MaryUtils.string2locale(MaryUtils.java:406)
	at marytts.modules.phonemiser.AllophoneSet.<init>(AllophoneSet.java:157)
	at marytts.modules.phonemiser.AllophoneSet.getAllophoneSet(AllophoneSet.java:105)
	at marytts.modules.phonemiser.AllophoneSet.getAllophoneSet(AllophoneSet.java:65)
	at marytts.tools.transcription.TranscriptionTable.loadPhoneSet(TranscriptionTable.java:338)
	at marytts.tools.transcription.TranscriptionGUI.loadPhoneSetActionPerformed(TranscriptionGUI.java:698)
	at marytts.tools.transcription.TranscriptionGUI.access$1500(TranscriptionGUI.java:53)
	at marytts.tools.transcription.TranscriptionGUI$15.actionPerformed(TranscriptionGUI.java:490)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Could it be possible that i'm doing something wrong, or my allophones.xml file is errorneous? Please Help. Thank you in advance for any support.

-LuckyJ

==========Pasting content in my allophones.xml============

<pre class="wiki">&lt;allophones name="sampa" xml:lang="si-LK"
		features="vlng vheight vfront vrnd ctype cplace cvox"&gt;
	&lt;silence ph="_"/&gt;

	&lt;vowel ph="O" vlng="l" vheight="2" vfront="3" vrnd="+"/&gt;
	&lt;vowel ph="o" vlng="s" vheight="2" vfront="3" vrnd="+"/&gt;
	&lt;vowel ph="E" vlng="l" vheight="2" vfront="1" vrnd="-"/&gt;
	&lt;vowel ph="e" vlng="s" vheight="2" vfront="1" vrnd="-"/&gt;	
	&lt;vowel ph="U" vlng="l" vheight="1" vfront="3" vrnd="+"/&gt;	
	&lt;vowel ph="u" vlng="s" vheight="1" vfront="3" vrnd="+"/&gt;
	&lt;vowel ph="I" vlng="l" vheight="1" vfront="1" vrnd="-"/&gt;	
	&lt;vowel ph="i" vlng="s" vheight="1" vfront="1" vrnd="-"/&gt;

	&lt;vowel ph="AE" vlng="l" vheight="3" vfront="1" vrnd="-"/&gt;
	&lt;vowel ph="ae" vlng="s" vheight="3" vfront="1" vrnd="-"/&gt;
	&lt;vowel ph="@" vlng="s" vheight="2" vfront="2" vrnd="-"/&gt;	
	&lt;vowel ph="A" vlng="l" vheight="3" vfront="3" vrnd="-"/&gt;
	&lt;vowel ph="a" vlng="s" vheight="3" vfront="3" vrnd="-"/&gt;
	
	&lt;vowel ph="au" vlng="d" vheight="3" vfront="2" vrnd="+"/&gt;
	&lt;vowel ph="ai" vlng="d" vheight="1" vfront="2" vrnd="-"/&gt;
	
	&lt;consonant ph="on" ctype="n" cplace="v" cvox="+"/&gt;
	&lt;consonant ph="h" ctype="f" cplace="v" cvox="+"/&gt;
	&lt;consonant ph="f" ctype="f" cplace="b" cvox="-"/&gt;
	&lt;consonant ph="s" ctype="f" cplace="a" cvox="-"/&gt;
	&lt;consonant ph="sh" ctype="f" cplace="p" cvox="-"/&gt;
	&lt;consonant ph="v" ctype="f" cplace="b" cvox="-"/&gt;

	&lt;consonant ph="l" ctype="a" cplace="a" cvox="-"/&gt;
	&lt;consonant ph="r" ctype="a" cplace="a" cvox="+"/&gt;
	&lt;consonant ph="y" ctype="a" cplace="p" cvox="+"/&gt;
	&lt;consonant ph="mb" ctype="n" cplace="l" cvox="+"/&gt;
	&lt;consonant ph="m" ctype="n" cplace="l" cvox="+"/&gt;
	&lt;consonant ph="b" ctype="s" cplace="l" cvox="+"/&gt;
	&lt;consonant ph="p" ctype="s" cplace="l" cvox="-"/&gt;

	&lt;consonant ph="ndh" ctype="n" cplace="d" cvox="+"/&gt;
	&lt;consonant ph="n" ctype="n" cplace="d" cvox="+"/&gt;
	&lt;consonant ph="dh" ctype="s" cplace="d" cvox="+"/&gt;
	&lt;consonant ph="th" ctype="s" cplace="d" cvox="-"/&gt;
	&lt;consonant ph="nd" ctype="n" cplace="a" cvox="+"/&gt;
	&lt;consonant ph="d" ctype="s" cplace="a" cvox="+"/&gt;

	&lt;consonant ph="t" ctype="s" cplace="a" cvox="-"/&gt;
	&lt;consonant ph="cn" ctype="n" cplace="p" cvox="+"/&gt;
	&lt;consonant ph="jh" ctype="s" cplace="p" cvox="+"/&gt;
	&lt;consonant ph="ch" ctype="s" cplace="p" cvox="-"/&gt;
	&lt;consonant ph="ng" ctype="n" cplace="v" cvox="+"/&gt;
	&lt;consonant ph="g" ctype="s" cplace="v" cvox="+"/&gt;
	&lt;consonant ph="k" ctype="s" cplace="v" cvox="-"/&gt;

&lt;/allophones&gt;
</pre>

**Comment by Munzey** [comment]
user has a newer issue open related to this topic so closing
