### ISSUE TITLE
UnsupportedOperationException when running the Voice Building Tools for new unit-selection voice

### ISSUE THREAD

**Issue by luckyjkh** [marytts/marytts#151]
Hi,

After creating New Language support for Sinhala (marytts-lang-si) with marytts-builder-5.1-SNAPSHOT version, I tried to run the voice building tool with 
$MARY_BASE/target/marytts-builder-<VERSION>/bin/voiceimport.sh 

The tool created Mel-Cepstrum coefficients for all 386 sentences in my voice building directory, and gave the following error. Can anyone please help me rectify it? Has anyone come across the same error before?

........
sen378
sen379
sen380
sen381
sen382
sen383
sen384
sen385
sen386
---- Mel-Cepstrum coefficients done.
Computing ALLOPHONES files for 386 files
Mary TTS client 5.1-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1-SNAPSHOT (impl. unknown)
java.lang.Exception: The component AllophonesExtractor produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.UnsupportedOperationException: No known way of generating output from input -- no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:508)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
	at marytts.server.Request.process(Request.java:336)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:724)
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:440)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:484)
	at marytts.client.MaryClient.process(MaryClient.java:648)
	at marytts.client.MaryClient.process(MaryClient.java:655)
	at marytts.tools.voiceimport.AllophonesExtractor.generateAllophonesFile(AllophonesExtractor.java:220)
	at marytts.tools.voiceimport.AllophonesExtractor.compute(AllophonesExtractor.java:151)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:431)
	... 6 more

**Comment by Munzey** [comment]
at the stage you are at, you should have a maven module called `marytts-lang-si`, with similar file structure to the other mary languages found in `marytts-languages`. Inside `marytts-lang-si/src/main/resources/marytts/language/si`, you should have your `si.config` file. It should look something like this:
```
# Sinhala language config file

name = si
si.version = 5.0.0

locale = si_LK

###########################################################################
############################## The Modules  ###############################
###########################################################################
# For keys ending in ".list", values will be appended across config files,
# so that .list keys can occur in several config files.
# For all other keys, values will be copied to the global config, so
# keys should be unique across config files.


# Java classes to use as the modules, as a whitespace-separated list.
# These have to implement marytts.modules.MaryModule.
# For each input type + output type, only one Module may be listed
# across all components, or an Exception will be thrown.
# No particular order is required -- a processing pipeline from input data type
# to output data type will be computed on-line.

modules.classes.list = \
        marytts.modules.JPhonemiser(si_LK.) \

####################################################################
####################### Module settings  ###########################
####################################################################
# Phonemiser settings
si_LK.allophoneset = jar:/marytts/language/si_LK/lexicon/allophones.si_LK.xml
#if you have a user dict add this line
si_LK.userdict = MARY_BASE/user-dictionaries/userdict-si_LK.txt
si_LK.lexicon = jar:/marytts/language/si_LK/lexicon/si_LK.fst
si_LK.lettertosound = jar:/marytts/language/si_LK/lexicon/si_LK.lts

# Feature processor manager
featuremanager.classes.list = \
	marytts.features.FeatureProcessorManager(si_LK)
```

**Comment by Munzey** [comment]
from issue #155 i will assume this is no longer a problem, please open a new issue if problem persists
