### ISSUE TITLE
Cannot handle multi-valued nominal class! - Error on training LTS (Similar to Issue #72)

### ISSUE THREAD

**Issue by luckyjkh** [marytts/marytts#153]
Hi,

I'm trying to add new language support for "Sinhala" Unit Selection.
In step 3 of tutorial, after transcribing about 100 words which I loaded from the mysql database (si_LK_wordList table), I clicked on the "Train and Predict" button and got the following error, which is similar to issue 72 https://github.com/marytts/marytts/issues/72 on the Vietnamese attempt. Can someone help me with this? Will it be helpful if I upload my most frequent word list and my allophones.xml for someone to help me?

.....
Received key release event, key nr. 10
Key released in row 101
row nr. 101
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: ං
      Training decision tree for: ළ
      Training decision tree for: හ
      Training decision tree for: ඇ
      Training decision tree for: ස
      Training decision tree for: ආ
      Training decision tree for: ශ
      Training decision tree for: අ
      Training decision tree for: ව
      Training decision tree for: ා
      Training decision tree for: ඊ
      Training decision tree for: ඉ
      Training decision tree for: ්
      Training decision tree for: ‍
      Training decision tree for: ූ
      Training decision tree for: ඒ
      Training decision tree for: ු
      Training decision tree for: එ
      Training decision tree for: ි
      Training decision tree for: ී
      Training decision tree for: ඔ
      Training decision tree for: ැ
      Training decision tree for: ක
      Training decision tree for: ො
      Training decision tree for: ෝ
      Training decision tree for: ේ
      Training decision tree for: ඟ
java.lang.RuntimeException: couldn't train decisiontree using weka: 
    at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:233)
    at marytts.tools.transcription.TranscriptionTable.trainLTS(TranscriptionTable.java:176)
    at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:203)
    at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:803)
    at marytts.tools.transcription.TranscriptionGUI.access$800(TranscriptionGUI.java:53)
    at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:364)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!
    at weka.core.Capabilities.test(Capabilities.java:940)
    at weka.core.Capabilities.test(Capabilities.java:1109)
    at weka.core.Capabilities.test(Capabilities.java:1022)
    at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
    at weka.classifiers.trees.j48.C45PruneableClassifierTree.buildClassifier(C45PruneableClassifierTree.java:120)
    at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:231)
    ... 41 more

Thanks in advance for any help you could give me.

Lakshika

**Comment by entenbein** [comment]
Hi,

I came across the same error. Is anyone still/again on this?

Thanks

**Comment by psibre** [comment]
I've played around with [a fix in my `test-lts` branch](/psibre/marytts/commit/c6c223c20210a218de00310735aebe7c7ba872a2); maybe that helps until we merge a proper solution.

**Comment by BibekBazaz** [comment]
Hello, I am too facing the same error while building the language support for HINDI language. Can you please elaborate what is this problem and how you guys managed to solve it??

I will be really grateful for any help.

**Comment by BibekBazaz** [comment]
@psibre  I tried to use the files you gave in your fix. but they give test failures when i try to build maven. So what should i do??

**Comment by JSefara** [comment]
Greetings

I encountered the same issue.

**Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!**

After some research the temporary solution is as follows:

- Switch to Mary TTS 4.3.1.

- Run the transcription.sh tool and feed it with your allophone set and wordlist. 

- Copy these newly created files:  [**allophones.xy.xml  xy.lts xy_lexicon.fst xy_pos.fst**  ]

- Then switch back to Mary latest version and continue.

It worked for me. I had successfully added a new language (locale).

**Comment by BibekBazaz** [comment]
I used this trick by JSefara. Thanks for his help.

Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!

After some research the temporary solution is as follows:

    Switch to Mary TTS 4.3.1.

    Run the transcription.sh tool and feed it with your allophone set and wordlist.

    Copy these newly created files: [allophones.xy.xml xy.lts xy_lexicon.fst xy_pos.fst ]

    Then switch back to Mary latest version and continue.

**Comment by BibekBazaz** [comment]
Thank you friend for your help. It did fix my training problem.

**Comment by entenbein** [comment]
I guess there's rather a problem with the input data than with this particular MaryTTS version.

**Comment by BibekBazaz** [comment]
Every user gets almost the same problems. So if the problem is with the
input data, its because there is no rules on how the input files should be.
So I request other users who have successfully used this version to add new
language support to document on how the input files of various stages
should be.

**Comment by entenbein** [comment]
You might want to stick to the formatting as in the provided files:
https://github.com/marytts/marytts/tree/master/user-dictionaries

**Comment by haquynh1505** [comment]
@BibekBazaz : How did you build mary 4.3.1? I ran into the same problem with LTS training and it seems like your solution is unique. However, I cannot build 4.3.1 because it lacks the pom file I think. Could you please help me? 
Thanks a lot in advance!

**Comment by BibekBazaz** [comment]
@haquynh1505  Hello, Firstly I could not find the MaryTTS 4.3.1. zip file so I could not install it. I found the standalone version which I installed using eclipse. I imported it but then again there were errors. So i left it there and went back to the MaryTTS 5.x version available in github. I had major issues in DBSelction Step. So I went through the code made a few throw catch exception changes in the code and re run the software. It worked. B ut the generation of the number of sentences were very limited. It might be because many of the sentences were rejected during the exception because it detected those as null strings.  I had limited time so I continued with 32 sentences and as a result the output of my TTS was not good.  I am busy as of now, but I soon plan to restart my work in Hindi and use MARYTTS to build the TTS. The major issue is that the database that I used was not very reliable. The tool did not have any such problems. So please go through the database and see if you can get a good qualoity database. 
I hope it helps.

**Comment by haquynh1505** [comment]
@BibekBazaz : thank you so much for such a kind and quick response! I'll try to take a look at the code!

**Comment by psibre** [comment]
Regarding MaryTTS 4.x, you can just check out the [`v4.3.1` tag](../tree/v4.3.1). Note that it builds with Ant, not Maven.

Regarding the specific issue, please also see #72 and #577.

**Comment by haquynh1505** [comment]
@psibre : Thank you! I saw both, and it seems like they needed to try with v4.3.1.

**Comment by JSefara** [comment]
Solved!
Here is the error.
java.lang.RuntimeException: couldn't train decisiontree using weka: 
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:242)
	at marytts.tools.transcription.TranscriptionTable.trainLTS(TranscriptionTable.java:178)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:212)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$8(TranscriptionGUI.java:810)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!
	at weka.core.Capabilities.test(Capabilities.java:940)
	at weka.core.Capabilities.test(Capabilities.java:1109)
	at weka.core.Capabilities.test(Capabilities.java:1022)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
	at weka.classifiers.trees.j48.C45PruneableClassifierTree.buildClassifier(C45PruneableClassifierTree.java:120)
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:240)
	... 41 more
**Solution**

LTSTrainer.java
Goto these lines and add **System.out.println("Data: "+data)** to see the content (arff) before sent to weka.

    C45PruneableClassifierTree decisionTree;
    try {
        decisionTree = new C45PruneableClassifierTreeWithUnary(new BinC45ModelSelection(minLeafData, data, true), true,
						0.25f, true, true, false);
				System.out.println("Data: "+data);
				decisionTree.buildClassifier(data);
			} 
    catch (Exception e) {
        throw new RuntimeException("couldn't train decisiontree using weka: ", e);
			}
**My output:**
Training decision tree for: c
Data: @relation c

@attribute att1 {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,null,t,u,v,w,x,y,z}
@attribute att2 {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,null,t,u,v,w,x,y,z}
@attribute att3 {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,null,t,u,v,w,x,y,z}
@attribute att4 {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,null,t,u,v,w,x,y,z}
@attribute att5 {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,null,t,u,v,w,x,y,z}
@attribute predicted-string {}

@data

java.lang.RuntimeException: couldn't train decisiontree using weka: 
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:242)
	at marytts.tools.transcription.TranscriptionTable.trainLTS(TranscriptionTable.java:178)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:212)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$8(TranscriptionGUI.java:810)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!
	at weka.core.Capabilities.test(Capabilities.java:940)
	at weka.core.Capabilities.test(Capabilities.java:1109)
	at weka.core.Capabilities.test(Capabilities.java:1022)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
	at weka.classifiers.trees.j48.C45PruneableClassifierTree.buildClassifier(C45PruneableClassifierTree.java:120)
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:240)
	... 41 more

**The data section of weka is empty and the predicted-string class is empty.
Now you can goto to your allophone set file to do some modifications. Make sure your phones cover all the alphabets. If possible deviate away from SAMPA. 
FYI**
@psibre
