### ISSUE TITLE
Mary TTS for Hindi, Assertion Error Exception, Server can't acess locale 

### ISSUE THREAD

**Issue by dheerendra002** [marytts/marytts#180]
Getting list of unprocessed clean_text records from hi_cleanText
Number of unprocessed clean_text records to process --> [4773]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:17_04_2014_03:12:29

Exception in thread "main" java.lang.AssertionError
	at marytts.features.FeatureRegistry.determineBestFeatureProcessorManager(FeatureRegistry.java:154)
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:227)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:180)

**Comment by Shandigutt** [comment]
You can solve this problem by adding your language module to marytts-assembly/assembly-builder/pom.xml. Then you can run FeatureMarker without assertion error.
