### ISSUE TITLE
Data truncation: Data too long for column 'rev_comment' error

### ISSUE THREAD

**Issue by bellegdi** [marytts/marytts#187]
Dear all
I am trying to add support for Arabic language.
I followed the steps given in 
https://github.com/marytts/marytts/wiki/New-Language-Support
After I have ran WikipediaDumpSplitter I ran WikipediaProcessor in which I got the following error.
I appreciate helping me resolving this problem.
Thanks in advance. 

```
WikipediaMarkupCleaner parameters:
  -mysqlHost localhost
  -mysqlUser root
  -mysqlPasswd xxxxxx
  -mysqlDB wkdb
  -listFile wikilist.txt
  -minPage 1000
  -minText 100
  -maxText 1500

Mysql driver loaded, set locale=ar_SA
Mysql connection created successfully.
    TABLE = "ar_SA_cleanText" does not exist, it will be created.
Mysql connection closed.

_______________________________________________________________________________

Processing xml file:xml_splits/page1.xml

Mysql driver loaded, set locale=ar_SA
Creating connection to DB server...
Mysql connection created successfully.
Creating and loading TABLES: page, text and revision. (The loading can take a while...)

Mysql driver loaded, set locale=ar_SA
Using mwdumper to convert xml file into sql source file and loading text, page and revision tables into the DB.
Creating connection to DB server...
Mysql connection created successfully.
Creating empty wikipedia tables: checking if tables text, page and revision already exist.

 ***To continue please check if the table "text" is used by another user/process.*** 
    Tables "text", "page" and "revision" are temporary tables used by mwdumper to extract wikipedia pages. 
    Just one user/process can use these tables at the same time in the same DataBase, please use other DataBase if possible.
    If the tables are not in use by any other user/process please use the option for deleting.

    TABLE = "text" already exists deleting (y/n)?y

 ***To continue please check if the table "page" is used by another user/process.*** 
    Tables "text", "page" and "revision" are temporary tables used by mwdumper to extract wikipedia pages. 
    Just one user/process can use these tables at the same time in the same DataBase, please use other DataBase if possible.
    If the tables are not in use by any other user/process please use the option for deleting.

    TABLE = "page" already exists deleting (y/n)?y

 ***To continue please check if the table "revision" is used by another user/process.*** 
    Tables "text", "page" and "revision" are temporary tables used by mwdumper to extract wikipedia pages. 
    Just one user/process can use these tables at the same time in the same DataBase, please use other DataBase if possible.
    If the tables are not in use by any other user/process please use the option for deleting.

    TABLE = "revision" already exists deleting (y/n)?y
  Creating table: text
  Creating table: page
  Creating table: revision
Exception in thread "main" java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 110
    at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
    at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:251)
    at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1047)
    at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:368)
Caused by: org.xml.sax.SAXException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 110
    at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at javax.xml.parsers.SAXParser.parse(Unknown Source)
    at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
    ... 3 more

```

**Comment by haquynh1505** [comment]
@bellegdi I've got the same problem today. I've already tried your solution firstly with "blob", but it didn't work at all, repeating the same problem. 

---------------------------------------------------------
Exception in thread "main" java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 234
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
	at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:257)
	at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1088)
	at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:444)
Caused by: org.xml.sax.SAXException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 234
	at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
	... 3 more
----------------------------------------------------------------

Then I tried "mediumblob" which I know is bigger than blob, but still, it didn't work! "longblob" threw the same outcome. 
Do you have any idea about this? Thank you in advance!

**Comment by Avinash01111992** [comment]
@haquynh1505  Hi even I'm  getting the same issue even after tried with all types blobs as @bellegdi  mentioned above.
Did you find the solution for this ?
