### ISSUE TITLE
HMMVoiceMakeData info

### ISSUE THREAD

**Issue by posttool** [marytts/marytts#190]
During this phase, I received the error-

```
java.lang.Exception: The component HMMVoiceMakeData produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.Exception: Error: directory /Users/david/Desktop/mf/voice/hts/data/mgc  does not exist or does not contain data files.
These data files can be generated setting the option HMMVoiceMakeData.makeMGC = 1
    at marytts.tools.voiceimport.HMMVoiceMakeData.compute(HMMVoiceMakeData.java:201)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
```

This error message was a bit misleading and had more to do with an HTS issue than Mary. Here is a link to the fix:

http://hts.sp.nitech.ac.jp/hts-users/spool/2012/msg00053.html

**Comment by Munzey** [comment]
@seblemaguer any thoughts?

**Comment by seblemaguer** [comment]
Yup I'll correct that in few days
