### ISSUE TITLE
Adding support for yoruba

### ISSUE THREAD

**Issue by johnaoga** [marytts/marytts#192]
Hi here,
I would like to add yoruba support in MaryTTS. I have added new module of yoruba language in MaryTTS. I've also produced waves database and phrases (wav folder and txt.done.data) and now I'm trying to build a voice with VoiceImportTool.

I got this exeption on step of HalfPhoneUnitFeatureComputer (All previous steps are completed successfully):
Mary TTS client 5.1-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1-SNAPSHOT (impl. unknown)
Mary TTS client 5.1-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1-SNAPSHOT (impl. unknown)
Mary TTS client 5.1-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1-SNAPSHOT (impl. unknown)
java.lang.Exception: The component HalfPhoneUnitFeatureComputer produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module TargetFeatureLister: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:552)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
	at marytts.server.Request.process(Request.java:298)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -119
	at marytts.features.TargetFeatureComputer.toStringValues(TargetFeatureComputer.java:183)
	at marytts.modules.TargetFeatureLister.listTargetFeatures(TargetFeatureLister.java:145)
	at marytts.modules.TargetFeatureLister.process(TargetFeatureLister.java:107)
	at marytts.server.Request.processOneChunk(Request.java:550)
	... 19 more
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:440)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:484)
	at marytts.client.MaryClient.process(MaryClient.java:648)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.computeFeaturesFor(PhoneUnitFeatureComputer.java:209)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.compute(PhoneUnitFeatureComputer.java:189)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:431)
	... 5 more
Someone have any idea?

**Comment by Munzey** [comment]
@johnaoga this issue should have been solved in v5.1.2, see issue #258. If you are still having problems please comment here and we can reopen the issue or open a new one
