### ISSUE TITLE
MaryTTS 5.2 (SNAPSHOT) Problems in extracting clean text from split files for Hindi language.

### ISSUE THREAD

**Issue by sohel-khalifa** [marytts/marytts#210]
Hi all.

I am trying to add support for Hindi language and reached step 2.2. I have created the DB with wkdb_create_database.sh and everythign seems fine till that. But when I run `wkdb_cleaning_up.sh ../wkdb.conf` the process goes as intended but at the end of the operation it throws the exception. Full stack trace below: 

Saving hi_IN_wordList table....
Inserting wordList in DB...
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: La table 'hi_in_wordlist' existe d├⌐j├á
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2619)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2569)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:813)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:656)
        at marytts.tools.dbselection.DBHandler.insertWordList(DBHandler.java:1083)
        at marytts.tools.dbselection.WikipediaMarkupCleaner.updateWordList(WikipediaMarkupCleaner.java:974)
        at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1133)
        at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:365)
hi_IN_wordList printed in file: ./wordlist-freq.txt ordered by frequency

Number of pages used=2152 Wordlist[126152]  Start time:03_09_2014_11:31:42  End time:03_09_2014_11:49:47
Deleting already used wikipedia tables.
Mysql connection closed.

This happens when the one split file is processed and the script is switching to the next split file from /current-dir/xml_splits/ directory. 

A text file wordlist-freq.txt is  created  after processing of the page1.xml, the processing of subsequent split files does not have any effect on wordlist.xml.

Please help me on this, my wkdb.conf file looks like this:

WIKIDATAPATH=/D/Mary/marytts-master/target/marytts-builder-5.2-SNAPSHOT/wiki
WIKILOCALE=hi
LOCALE=hi_IN
MYSQLHOST=localhost
MYSQLUSER=root
MYSQLPASSWD=root
MYSQLDB=wiki
FEATUREMAKERRELIABILITY=strict
FEATUREMAKERFEATURESFORSELECTION="phone,next_phone,selection_prosody"
SELECTEDSENTENCESTABLENAME=test
SELECTEDSENTENCESTABLEDSCRIPTION="Testing table for selected sentences. Wikipedia locale:  hi"
DATABASESELECTORSTOPCRITERION="numSentences 90 simpleDiphones simpleProsody"

**Comment by Munzey** [comment]
closed for inactivity. If you are still experiencing the same problem, please comment and we will reopen the issue, or you can open a new issue.
