### ISSUE TITLE
Using MaryLocalInterface in webapplication deployed on local Tomcat, can't find ".\lib\voices\bits3\dur.tree" 

### ISSUE THREAD

**Issue by FabianWelz** [marytts/marytts#212]
Hello everybody,

I am trying to use MaryTTS with the MaryLocalInterface in a java-webapplication deployed on a local Tomcat. 

It works fine using the hsmm-version of a voice, but if I wan't to use a voice that requires the additional files, like for bits3 .\lib\voices\bits3\dur.tree, it can not find the files. I placed them in all places I could think of within the Tomcat, but none of them worked.

For example i put them in:
-tomcat\webapps\MyWebApp\WEB-INF\lib\lib\voices\bits3
-tomcat\webapps\MyWebApp\WEB-INF\lib\voices\bits3
-tomcat\webapps\MyWebApp\WEB-INF\voices\bits3
-tomcat\webapps\MyWebApp\lib\voices\bits3

Thank you for any help in advance.
-Fabian

LOG:
2014-09-09 08:30:30,602 INFO  [] [] main - Mary starting up...
2014-09-09 08:30:30,602 INFO  [] [] main - Specification version 5.1
2014-09-09 08:30:30,602 INFO  [] [] main - Implementation version unknown
2014-09-09 08:30:30,602 INFO  [] [] main - Running on a Java 1.7.0_13 implementation by Oracle Corporation, on a Windows 7 platform (x86, 6.1)
2014-09-09 08:30:30,782 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.de.JTokeniser'
2014-09-09 08:30:30,782 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.de.Preprocess'
2014-09-09 08:30:30,782 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.OpenNLPPosTagger(de,de.pos)'
2014-09-09 08:30:30,782 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.de.JPhonemiser'
2014-09-09 08:30:30,782 INFO  [] [] JPhonemiser_de - User dictionary '.\user-dictionaries\userdict-de.txt' for locale 'de' does not exist. Ignoring.
2014-09-09 08:30:30,812 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.de.Prosody'
2014-09-09 08:30:30,812 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.de.Postlex'
2014-09-09 08:30:30,852 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.SimplePhoneme2AP(de)'
2014-09-09 08:30:30,852 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.JTokeniser'
2014-09-09 08:30:30,852 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.FreeTTSTokenToWords'
2014-09-09 08:30:30,852 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.JPhonemiser(en_US.)'
2014-09-09 08:30:30,852 INFO  [] [] JPhonemiser - User dictionary '.\user-dictionaries\userdict-en_US.txt' for locale 'en_US' does not exist. Ignoring.
2014-09-09 08:30:30,882 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.JPhonemiser(en_GB.)'
2014-09-09 08:30:30,882 INFO  [] [] JPhonemiser - User dictionary '.\user-dictionaries\userdict-en_GB.txt' for locale 'en_GB' does not exist. Ignoring.
2014-09-09 08:30:30,902 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.Prosody'
2014-09-09 08:30:30,902 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.SimplePhoneme2AP(en_US)'
2014-09-09 08:30:30,902 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.Utt2XMLWordsEn'
2014-09-09 08:30:30,902 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.XML2UttTokensEn'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.language.en.PronunciationModel'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.OpenNLPPosTagger(en,en.pos)'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.Synthesis'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.TextToMaryXML'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.SableParser'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.SSMLParser'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.APMLParser'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.EmotionmlParser'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.JTokeniser'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.DummyTokens2Words'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.ProsodyGeneric'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.PronunciationModel'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.TargetFeatureLister'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.HalfPhoneTargetFeatureLister'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.AcousticModeller'
2014-09-09 08:30:30,912 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.RealisedAcoustparamsExtractor'
2014-09-09 08:30:30,922 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.RealisedDurationsExtractor'
2014-09-09 08:30:30,922 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.HTSEngine'
2014-09-09 08:30:30,922 INFO  [] [] ModuleRegistry - Now initiating mary module 'marytts.modules.PraatTextGridGenerator'
2014-09-09 08:30:30,922 INFO  [] [] JTokeniser - Module started (RAWMARYXML->TOKENS, locale de).
2014-09-09 08:30:30,932 INFO  [] [] JTok - loading language resources for de from jtok/de
2014-09-09 08:30:30,942 INFO  [] [] JTokeniser - Starting power-on self test.
2014-09-09 08:30:30,952 INFO  [] [] JTokeniser - Power-on self test complete.
2014-09-09 08:30:30,952 INFO  [] [] Preprocess - Module started (TOKENS->WORDS, locale de).
2014-09-09 08:30:30,952 INFO  [] [] Preprocess - Starting power-on self test.
2014-09-09 08:30:30,952 INFO  [] [] Preprocess - Expanding say-as elements...
2014-09-09 08:30:30,952 INFO  [] [] Preprocess - Matching and expanding patterns...
2014-09-09 08:30:30,972 INFO  [] [] Preprocess - Done.
2014-09-09 08:30:30,972 INFO  [] [] Preprocess - Power-on self test complete.
2014-09-09 08:30:30,972 INFO  [] [] OpenNLPPosTagger - Module started (WORDS->PARTSOFSPEECH, locale de).
2014-09-09 08:30:31,542 INFO  [] [] OpenNLPPosTagger - Starting power-on self test.
2014-09-09 08:30:31,542 INFO  [] [] OpenNLPPosTagger - Power-on self test complete.
2014-09-09 08:30:31,542 INFO  [] [] JPhonemiser_de - Module started (PARTSOFSPEECH->PHONEMES, locale de).
2014-09-09 08:30:31,552 INFO  [] [] JPhonemiser_de - Starting power-on self test.
2014-09-09 08:30:31,552 INFO  [] [] JPhonemiser_de - Power-on self test complete.
2014-09-09 08:30:31,552 INFO  [] [] Prosody - Module started (PHONEMES->INTONATION, locale de).
2014-09-09 08:30:31,552 INFO  [] [] Prosody - Starting power-on self test.
2014-09-09 08:30:31,552 INFO  [] [] Prosody - Power-on self test complete.
2014-09-09 08:30:31,552 INFO  [] [] PronunciationModel - Module started (INTONATION->ALLOPHONES, locale de).
2014-09-09 08:30:31,552 INFO  [] [] PronunciationModel - Starting power-on self test.
2014-09-09 08:30:31,552 INFO  [] [] PronunciationModel - Power-on self test complete.
2014-09-09 08:30:31,552 INFO  [] [] SimplePhoneme2AP - Module started (SIMPLEPHONEMES->ACOUSTPARAMS, locale de).
2014-09-09 08:30:31,552 INFO  [] [] SimplePhoneme2AP - Starting power-on self test.
2014-09-09 08:30:31,552 INFO  [] [] SimplePhoneme2AP - Power-on self test complete.
2014-09-09 08:30:31,552 INFO  [] [] JTokeniser - Module started (RAWMARYXML->TOKENS, locale en).
2014-09-09 08:30:31,562 INFO  [] [] JTok - loading language resources for en from jtok/en
2014-09-09 08:30:31,562 INFO  [] [] JTokeniser - Starting power-on self test.
2014-09-09 08:30:31,562 INFO  [] [] JTokeniser - Power-on self test complete.
2014-09-09 08:30:31,562 INFO  [] [] TokenToWords - Module started (FREETTS_TOKENS->FREETTS_WORDS, locale en).
2014-09-09 08:30:31,562 INFO  [] [] FreeTTSVoices - Loading US English FreeTTS voices...
2014-09-09 08:30:31,562 INFO  [] [] FreeTTSVoices - done.
2014-09-09 08:30:31,572 INFO  [] [] TokenToWords - Starting power-on self test.
2014-09-09 08:30:31,572 INFO  [] [] TokenToWords - Power-on self test complete.
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Module started (PARTSOFSPEECH->PHONEMES, locale en_US).
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Starting power-on self test.
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Power-on self test complete.
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Module started (PARTSOFSPEECH->PHONEMES, locale en_GB).
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Starting power-on self test.
2014-09-09 08:30:31,572 INFO  [] [] JPhonemiser - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] Prosody - Module started (PHONEMES->INTONATION, locale en).
2014-09-09 08:30:31,582 INFO  [] [] Prosody - Starting power-on self test.
2014-09-09 08:30:31,582 INFO  [] [] Prosody - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] SimplePhoneme2AP - Module started (SIMPLEPHONEMES->ACOUSTPARAMS, locale en_US).
2014-09-09 08:30:31,582 INFO  [] [] SimplePhoneme2AP - Starting power-on self test.
2014-09-09 08:30:31,582 INFO  [] [] SimplePhoneme2AP - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] Utt2XML WordsEn - Module started (FREETTS_WORDS->WORDS, locale en).
2014-09-09 08:30:31,582 INFO  [] [] FreeTTSVoices - Loading US English FreeTTS voices...
2014-09-09 08:30:31,582 INFO  [] [] FreeTTSVoices - done.
2014-09-09 08:30:31,582 INFO  [] [] Utt2XML WordsEn - Starting power-on self test.
2014-09-09 08:30:31,582 INFO  [] [] Utt2XML WordsEn - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] XML2Utt TokensEn - Module started (TOKENS->FREETTS_TOKENS, locale en).
2014-09-09 08:30:31,582 INFO  [] [] FreeTTSVoices - Loading US English FreeTTS voices...
2014-09-09 08:30:31,582 INFO  [] [] FreeTTSVoices - done.
2014-09-09 08:30:31,582 INFO  [] [] XML2Utt TokensEn - Starting power-on self test.
2014-09-09 08:30:31,582 INFO  [] [] XML2Utt TokensEn - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] PronunciationModel - Module started (INTONATION->ALLOPHONES, locale en).
2014-09-09 08:30:31,582 INFO  [] [] PronunciationModel - Starting power-on self test.
2014-09-09 08:30:31,582 INFO  [] [] PronunciationModel - Power-on self test complete.
2014-09-09 08:30:31,582 INFO  [] [] OpenNLPPosTagger - Module started (WORDS->PARTSOFSPEECH, locale en).
2014-09-09 08:30:32,552 INFO  [] [] OpenNLPPosTagger - Starting power-on self test.
2014-09-09 08:30:32,552 INFO  [] [] OpenNLPPosTagger - Power-on self test complete.
2014-09-09 08:30:32,552 ERROR [] [] MaryLocalTTSInterface - Cannot start MARY server
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
    at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:65)
    at de.cfs.tts.mary.MaryLocalTTSInterface.addLocale(MaryLocalTTSInterface.java:95)
    at de.cfs.tts.GreetAndSay.addLocale(GreetAndSay.java:136)
    at de.cfs.tts.GreetAndSay.<init>(GreetAndSay.java:21)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:126)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:107)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:984)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:886)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:479)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:450)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:290)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:287)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:189)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:557)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:842)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:416)
    at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:261)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:192)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3972)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4467)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
    at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
    at org.apache.catalina.core.StandardService.start(StandardService.java:519)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: java.lang.Exception: Problem starting module Synthesis
    at marytts.server.Mary.startModules(Mary.java:150)
    at marytts.server.Mary.startup(Mary.java:298)
    at marytts.server.Mary.startup(Mary.java:205)
    at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:71)
    at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
    ... 48 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'bits3'
    at marytts.modules.synthesis.Voice.<init>(Voice.java:207)
    at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:84)
    at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:96)
    at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:82)
    at marytts.modules.Synthesis.startup(Synthesis.java:72)
    at marytts.server.Mary.startModules(Mary.java:148)
    ... 52 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot load duration graph file '.\lib\voices\bits3\dur.tree'
    at marytts.modules.synthesis.Voice.loadOldStyleProsodyModels(Voice.java:256)
    at marytts.modules.synthesis.Voice.init(Voice.java:240)
    at marytts.modules.synthesis.Voice.<init>(Voice.java:205)
    ... 57 more
Caused by: java.io.FileNotFoundException: .\lib\voices\bits3\dur.tree (Das System kann den angegebenen Pfad nicht finden)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:97)
    at marytts.cart.io.DirectedGraphReader.load(DirectedGraphReader.java:67)
    at marytts.modules.synthesis.Voice.loadOldStyleProsodyModels(Voice.java:254)
    ... 59 more
2014-09-09 08:30:32,592 WARN  [] [] Voice - Could not find default voice for locale en_US
2014-09-09 08:30:32,592 INFO  [] [] DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@dcb0a: defining beans [versionInfo,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.web.context.support.ServletContextPropertyPlaceholderConfigurer#0,scopedTarget.jdbcConnectionProvider,jdbcConnectionProvider,cfsMessageSource,timeZoneAccess,localeAccess,loadMessageSource,messageSource,org.springframework.security.userDetailsService,org.springframework.security.authentication.dao.DaoAuthenticationProvider#0,org.springframework.security.authentication.DefaultAuthenticationEventPublisher#0,org.springframework.security.authenticationManager,org.springframework.security.web.PortMapperImpl#0,org.springframework.security.web.context.HttpSessionSecurityContextRepository#0,org.springframework.security.web.authentication.session.SessionFixationProtectionStrategy#0,org.springframework.security.authentication.ProviderManager#0,org.springframework.security.access.vote.AffirmativeBased#0,org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0,org.springframework.security.web.access.DefaultWebInvocationPrivilegeEvaluator#0,org.springframework.security.authentication.AnonymousAuthenticationProvider#0,org.springframework.security.web.savedrequest.HttpSessionRequestCache#0,org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0,org.springframework.security.config.http.UserDetailsServiceInjectionBeanPostProcessor#0,org.springframework.security.filterChainProxy,authenticationService,org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource#0,org.springframework.security.access.vote.AffirmativeBased#1,org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor#0,org.springframework.security.methodSecurityMetadataSourceAdvisor,org.springframework.aop.config.internalAutoProxyCreator,dataSource,org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0,org.springframework.transaction.interceptor.TransactionInterceptor#0,org.springframework.transaction.config.internalTransactionAdvisor,txManager,scopedTarget.userSettingDao,userSettingDao,lobHandler,scopedTarget.mdxBookmarkDao,mdxBookmarkDao,functionTreeConfig,userSettingsEventSubscriber,userSettingsService,MaryTTSGreeter,MaryTTSInterface,FreeTTSGreeter,FreeTTSInterface,scopedTarget.eventBus,eventBus,viewResolver,imageResolver,de.cfs.eclnt.web.logging.MDCUserLoggedInEventSubscriber#0,comboboxFactory,FreeMarkerRenderer]; root of factory hierarchy
2014-09-09 08:30:32,592 ERROR [] [] ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'MaryTTSGreeter' defined in ServletContext resource [/WEB-INF/spring/tts.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [de.cfs.tts.GreetAndSay]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: No such voice: cmu-slt
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:283)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:984)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:886)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:479)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:450)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:290)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:287)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:189)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:557)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:842)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:416)
    at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:261)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:192)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3972)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4467)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:637)
    at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:563)
    at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:498)
    at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
    at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
    at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
    at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
    at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
    at org.apache.catalina.core.StandardService.start(StandardService.java:519)
    at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [de.cfs.tts.GreetAndSay]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: No such voice: cmu-slt
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:107)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
    ... 38 more
Caused by: java.lang.IllegalArgumentException: No such voice: cmu-slt
    at marytts.LocalMaryInterface.setVoice(LocalMaryInterface.java:167)
    at de.cfs.tts.mary.MaryLocalTTSInterface.addLocale(MaryLocalTTSInterface.java:97)
    at de.cfs.tts.GreetAndSay.addLocale(GreetAndSay.java:136)
    at de.cfs.tts.GreetAndSay.<init>(GreetAndSay.java:22)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:126)
    ... 40 more

**Comment by netzverb** [comment]
@FabianWelz: Hi Fabian, could you successfully run marytts on tomcat? I try it, but I have the following problem: #521 (marytts create memory leak). Would you share your code of accessing marytts? ;-)

Thanks!
Andreas

**Comment by FabianWelz** [comment]
@netzverb: Yes I was able to run marytts in an webapplication running in tomcat. But I cant share the code because it was part of an project at a previous employer, sorry
