### ISSUE TITLE
HMMVoiceCreation:HMMVoiceCompiler server issues

### ISSUE THREAD

**Issue by karthikkrishnanv** [marytts/marytts#223]
I have successfully built (I hope :) HMM voice and have installed it. When I try to run the server, it throws an out of memory error (I have tried different setting including 8G). The error is below. Any idea ? Also is it possible to actually use the original hts_engine with the files generated. I understand it has been ported to marytts runtime, per previous email. But if it can be somehow glued to build a htsvoice, I would be able to run my existing stack easily. Appreciate any ideas on this.

OpenJDK Runtime Environment (IcedTea 2.3.10) (7u25-2.3.10-1ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

MARY server 5.2-SNAPSHOT starting as a HTTP server...Exception in thread "main" java.lang.Exception: Problem starting module Synthesis
	at marytts.server.Mary.startModules(Mary.java:150)
	at marytts.server.Mary.startup(Mary.java:298)
	at marytts.server.Mary.startup(Mary.java:205)
	at marytts.server.Mary.main(Mary.java:508)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'my_voice-hsmm'
	at marytts.modules.synthesis.Voice.<init>(Voice.java:207)
	at marytts.htsengine.HMMVoice.<init>(HMMVoice.java:88)
	at marytts.modules.synthesis.HMMSynthesizer.startup(HMMSynthesizer.java:155)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:82)
	at marytts.modules.Synthesis.startup(Synthesis.java:72)
	at marytts.server.Mary.startModules(Mary.java:148)
	... 3 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate model 'duration' of type 'hmm' from 'null'
	at marytts.modules.synthesis.Voice.loadAcousticModels(Voice.java:349)
	at marytts.modules.synthesis.Voice.init(Voice.java:241)
	at marytts.modules.synthesis.Voice.<init>(Voice.java:205)
	... 8 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at marytts.cart.io.HTSCARTReader.loadPdfs(HTSCARTReader.java:407)
	at marytts.cart.io.HTSCARTReader.load(HTSCARTReader.java:143)
	at marytts.htsengine.CartTreeSet.loadTreeSet(CartTreeSet.java:123)
	at marytts.htsengine.HMMData.initHMMDataForHMMModel(HMMData.java:482)
	at marytts.modules.acoustic.HMMModel.loadData(HMMModel.java:127)
	at marytts.modules.acoustic.Model.load(Model.java:139)
	at marytts.modules.acoustic.HMMModel.<init>(HMMModel.java:104)
	at marytts.modules.synthesis.Voice.loadAcousticModels(Voice.java:343)
	... 10 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:384)
	at marytts.server.Mary$3.run(Mary.java:290)

**Comment by Munzey** [comment]
closed for inactivity. If you are still experiencing the same problem, please comment and we will reopen the issue, or you can open a new issue.
