### ISSUE TITLE
New Language support building isssues

### ISSUE THREAD

**Issue by dayoreke** [marytts/marytts#253]
I followed all the steps required to build NLP support for Yoruba.
However, when i try building the language i get this error

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-lang-yo 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.258s
[INFO] Finished at: Mon Nov 24 17:21:29 WAT 2014
[INFO] Final Memory: 8M/85M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project marytts-lang-yo: Could not resolve dependencies for project de.dfki.mary:marytts-lang-yo:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

Below is the error stack trace

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-lang-yo 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.142s
[INFO] Finished at: Mon Nov 24 17:48:29 WAT 2014
[INFO] Final Memory: 8M/85M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project marytts-lang-yo: Could not resolve dependencies for project de.dfki.mary:marytts-lang-yo:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project marytts-lang-yo: Could not resolve dependencies for project de.dfki.mary:marytts-lang-yo:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project de.dfki.mary:marytts-lang-yo:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
    ... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
    ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
    ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact de.dfki.mary:marytts-yontime:jar:5.2-SNAPSHOT
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
    ... 26 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

I will appreciate your responses. Thanks

**Comment by Munzey** [comment]
@dayoreke is the issue resolved? if not can you push to your TTS repository your latest commits? I can then try see where its going wrong

**Comment by neouyghur** [comment]
hi, I am getting similar error. But I can't handle it. Please help.

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-lang-ug 6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.dfki.mary:marytts-common:jar:6.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.dfki.mary:marytts-signalproc:jar:6.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.dfki.mary:marytts-runtime:jar:6.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.dfki.mary:marytts-runtime:jar:tests:6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.172 s
[INFO] Finished at: 2017-12-16T18:29:38+10:00
[INFO] Final Memory: 16M/483M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project marytts-lang-ug: Could not resolve dependencies for project de.dfki.mary:marytts-lang-ug:jar:6.0-SNAPSHOT: The following artifacts could not be resolved: de.dfki.mary:marytts-common:jar:6.0-SNAPSHOT, de.dfki.mary:marytts-signalproc:jar:6.0-SNAPSHOT, de.dfki.mary:marytts-runtime:jar:6.0-SNAPSHOT, de.dfki.mary:marytts-runtime:jar:tests:6.0-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-common:jar:6.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by neouyghur** [comment]
@psibre, I solved my problem. After I compiled the marrytts source file, it is solved. But I am not sure it is the correct way to solve the problem. Even I solved the porblem, I am still encountering the following problem. 

```
java.lang.UnsupportedOperationException: No known way of generating output (ACOUSTPARAMS) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by psibre** [comment]
@neouyghur So can we close this issue?

**Comment by neouyghur** [comment]
@paibre yes, thanks.

**Comment by alphamwamanda** [comment]
Hello, I also followed all the steps in building Swahili language but am getting the same error but this one am getting in the last step (voice compiler) I can't edit my pom file because every time I edit it when I rerun it changes as it was. please help me
