### ISSUE TITLE
redstart recording audio exception

### ISSUE THREAD

**Issue by omidp** [marytts/marytts#264]
Hi,
I run Redstart then import a simple text file with following content
در
به
از
سلام
when I try to record audio with RedStart I get following exception :  
Exception in thread "Thread-12" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at marytts.signalproc.filter.FIRFilter$FIROutput.getData(FIRFilter.java:160)
	at marytts.util.data.audio.DDSAudioInputStream.read(DDSAudioInputStream.java:95)
	at com.sun.media.sound.SunFileWriter$NoCloseInputStream.read(SunFileWriter.java:198)
	at java.io.SequenceInputStream.read(SequenceInputStream.java:208)
	at java.io.InputStream.read(InputStream.java:101)
	at com.sun.media.sound.WaveFileWriter.writeWaveFile(WaveFileWriter.java:239)
	at com.sun.media.sound.WaveFileWriter.write(WaveFileWriter.java:137)
	at javax.sound.sampled.AudioSystem.write(AudioSystem.java:1354)
	at marytts.util.data.audio.AudioRecorder$BufferingRecorder.run(AudioRecorder.java:746)
Files for s22: 1
java.lang.IllegalArgumentException: NaN not allowed in mean calculation
	at marytts.util.math.MathUtils.mean(MathUtils.java:331)
	at marytts.machinelearning.KMeansClusteringTrainer.train(KMeansClusteringTrainer.java:117)
	at marytts.signalproc.analysis.EnergyAnalyser.getSilenceCutoffFromKMeansClustering(EnergyAnalyser.java:356)
	at marytts.tools.redstart.Recording.checkForTempClipping(Recording.java:161)
	at marytts.tools.redstart.AdminWindow.determineStatus(AdminWindow.java:258)
	at marytts.tools.redstart.AdminWindow.makeRecording(AdminWindow.java:572)
	at marytts.tools.redstart.AdminWindow.manageRecording(AdminWindow.java:752)
	at marytts.tools.redstart.AdminWindow.access$2000(AdminWindow.java:65)
	at marytts.tools.redstart.AdminWindow$21.run(AdminWindow.java:1467)
what is that mean ?

**Comment by psibre** [comment]
According to the source code in `Recording.checkForTempClipping`,
```java
			// Need at least 100 ms of silence at the beginning and at the end:
```
But this is not actually enforced as far as I can see, which *might* be the cause of the error...
Is your recording too short for some reason?

Please note however that the Redstart tool has not been maintained for over five years. I would strongly recommend using another tool to record your audio.
