### ISSUE TITLE
NoClassDefFoundError when running marytts-server

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#274]
Trying to run the new release...
```
MARY server 5.1.2 starting as a HTTP server...Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/icu/text/RuleBasedNumberFormat
	at marytts.language.fr.Preprocess.<init>(Preprocess.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:130)
	at marytts.modules.ModuleRegistry.instantiateModule(ModuleRegistry.java:87)
	at marytts.server.Mary.startModules(Mary.java:130)
	at marytts.server.Mary.startup(Mary.java:296)
	at marytts.server.Mary.startup(Mary.java:203)
	at marytts.server.Mary.main(Mary.java:513)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.RuleBasedNumberFormat
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 12 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:385)
	at marytts.server.Mary$3.run(Mary.java:288)
```

**Comment by psibre** [comment]
A regression! Due to the removal of the ICU4J dependency from the runtime module, it's no longer on the classpath, since neither the runtime assembly nor the French language component (which is currently the only consumer of this dependency) actually contains it...

**Comment by psibre** [comment]
I've replaced the package files in the [5.1.2 release](https://github.com/marytts/marytts/releases/tag/v5.1.2) with zip files that include the missing `icu4j-54.1.1.jar`; a transparent fix for anyone using the downloadable packages.
But anyone checking out `v5.1.2` and running `mvn package` will be bitten by this issue.
