### ISSUE TITLE
When start [marytts-server] 

### ISSUE THREAD

**Issue by NeptunSun** [marytts/marytts#275]
When I am rexecuting ./marytts-server i am getting such error. 

java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

MARY server 5.2-SNAPSHOT starting as a HTTP server...Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/icu/text/RuleBasedNumberFormat
	at marytts.language.fr.Preprocess.<init>(Preprocess.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:130)
	at marytts.modules.ModuleRegistry.instantiateModule(ModuleRegistry.java:87)
	at marytts.server.Mary.startModules(Mary.java:130)
	at marytts.server.Mary.startup(Mary.java:296)
	at marytts.server.Mary.startup(Mary.java:203)
	at marytts.server.Mary.main(Mary.java:513)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.text.RuleBasedNumberFormat

**Comment by psibre** [comment]
fixed in #274
