### ISSUE TITLE
test failure for Indonesian language support

### ISSUE THREAD

**Issue by yusufardi97** [marytts/marytts#278]
Hello,
I currently working on language support for Indonesian. When i try building the language file and test it, i encounter this error.

>mvn -e test
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-lang-id 5.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT is missing, n
o dependency information available
[WARNING] The POM for de.dfki.mary:marytts-signalproc:jar:5.2-SNAPSHOT is missin
g, no dependency information available
[WARNING] The POM for de.dfki.mary:marytts-runtime:jar:5.2-SNAPSHOT is missing,
no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.584 s
[INFO] Finished at: 2015-02-02T06:53:58+07:00
[INFO] Final Memory: 6M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project marytts-lang-id: Could not resolve dep
endencies for project de.dfki.mary:marytts-lang-id:jar:5.2-SNAPSHOT: The followi
ng artifacts could not be resolved: de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT
, de.dfki.mary:marytts-signalproc:jar:5.2-SNAPSHOT, de.dfki.mary:marytts-runtime
:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-common:jar:5.2-S
NAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
n project marytts-lang-id: Could not resolve dependencies for project de.dfki.ma
ry:marytts-lang-id:jar:5.2-SNAPSHOT: The following artifacts could not be resolv
ed: de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT, de.dfki.mary:marytts-signalpro
c:jar:5.2-SNAPSHOT, de.dfki.mary:marytts-runtime:jar:5.2-SNAPSHOT: Could not fin
d artifact de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDe
pendencies(LifecycleDependencyResolver.java:220)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resol
veProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAr
eResolved(MojoExecutor.java:257)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not res
olve dependencies for project de.dfki.mary:marytts-lang-id:jar:5.2-SNAPSHOT: The
 following artifacts could not be resolved: de.dfki.mary:marytts-common:jar:5.2-
SNAPSHOT, de.dfki.mary:marytts-signalproc:jar:5.2-SNAPSHOT, de.dfki.mary:marytts
-runtime:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-common:j
ar:5.2-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(D
efaultProjectDependenciesResolver.java:198)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDe
pendencies(LifecycleDependencyResolver.java:195)
        ... 22 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The foll
owing artifacts could not be resolved: de.dfki.mary:marytts-common:jar:5.2-SNAPS
HOT, de.dfki.mary:marytts-signalproc:jar:5.2-SNAPSHOT, de.dfki.mary:marytts-runt
ime:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-common:jar:5.
2-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDepen
dencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(D
efaultProjectDependenciesResolver.java:192)
        ... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The follow
ing artifacts could not be resolved: de.dfki.mary:marytts-common:jar:5.2-SNAPSHO
T, de.dfki.mary:marytts-signalproc:jar:5.2-SNAPSHOT, de.dfki.mary:marytts-runtim
e:jar:5.2-SNAPSHOT: Could not find artifact de.dfki.mary:marytts-common:jar:5.2-
SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:459)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
acts(DefaultArtifactResolver.java:262)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDepen
dencies(DefaultRepositorySystem.java:367)
        ... 24 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find
 artifact de.dfki.mary:marytts-common:jar:5.2-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:449)
        ... 26 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
>

i already edit the pom and all the required file (from fr language) according to new language support. could you tell me where i'm doing it wrong?

**Comment by yusufardi97** [comment]
ah, sorry, my bad. I'm using already compiled folder in the earlier step (dump wiki, etc), so the one i have in git folder was not yet compiled and there's no jar file there. After installing those jar files, the test runs just fine.
