### ISSUE TITLE
Allophone `-' could not be found in AllophoneSet `sampa' (Locale: en_US)

### ISSUE THREAD

**Issue by rospocher** [marytts/marytts#285]
HI, I'm trying to generate an audio file from an english language text file with version 5.1.2.

The tool seems to be correctly installed (the speech generation of the default sentences work OK).
However, if I type a sentence containing word "scalable", even typing simply "scalable" in the input box, I get the following error message in the log: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: en_US).

This is the call I made:
http://localhost:59125/process?INPUT_TEXT=scalable&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=en_US

and this is the log:
```
Processing failed.

java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:549)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: en_US)
	at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
	at marytts.modules.phonemiser.Syllabifier.correctStressSymbol(Syllabifier.java:297)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:252)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:52)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:166)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:225)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:153)
	at marytts.server.Request.processOneChunk(Request.java:547)
	... 19 more
```
I can't access the online demo to check if it behaves the same.
I this an expected behaviour?

thanks

**Comment by seblemaguer** [comment]
Apparently, it's relicate of the syllabification change. I found and corrected the problem for the english language but I need to update the german package which leads to a failing stage after the correction

**Comment by psibre** [comment]
@seblemaguer what's your commit?

**Comment by seblemaguer** [comment]
@psibre I didn't commit yet as the integration test failed for the german language

**Comment by psibre** [comment]
@seblemaguer I'm also getting a failure in MaryInterfaceDeIT.canProcessTokensToAllophones, but with a feature branch, we can debug this together. =)

**Comment by psibre** [comment]
Indeed, this slipped through when Syllabifier was deprecated in #266

**Comment by psibre** [comment]
@seblemaguer I just realized I based my commits off an orphaned master... feel free to rebase them onto upstream/master

**Comment by rospocher** [comment]
Hi, thanks. I've pulled from git and compiled (mvn install), but I'm now getting the punctuation marks (e.g, commas, question marks, etc) spelled (some strange word that I can't grasp), and with compound words like "applejuice", I get the following error:

Connected to localhost:59125, Mary TTS server 5.2-SNAPSHOT (impl. unknown)
Exception in thread "main" java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Found unknown symbol `1' in phonetic string `{1pljuIs' -- ignoring.
	at marytts.modules.phonemiser.AllophoneSet.splitIntoAllophoneList(AllophoneSet.java:405)
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:456)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:225)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:153)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 19 more
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
	at marytts.client.MaryClient.process(MaryClient.java:653)
	at marytts.client.MaryClient.process(MaryClient.java:659)
	at MaryClientUser.main(MaryClientUser.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:388)
	... 9 more

**Comment by psibre** [comment]
@rospocher Thanks for the report! I wasn't happy with e9c8edd89203c1392baec661a2fbd3527627b9db to begin with, but didn't want to mess with the way that syllabify is called on empty strings in several classes (with subsequent code handling `null`). But now I realize I should have gone the extra mile and done just that, because we obviously don't want to have stuff like
```
<t g2p_method="" ph="null" pos=".">
?
</t>
```

Regarding the `applejuice`:point_right: `{1pljuIs` issue (and others like it lurking under the surface), this a separate issue. Years ago (ec57e5906dfd30d341ebb42a7b959628ab5b2b3b) the English pronunciation prediction was built directly from the raw [CMUdict](http://www.speech.cs.cmu.edu/cgi-bin/cmudict), which uses ARPAbet transcription and encodes syllable stress as a trailing integer on the corresponding nucleus. This is the reason there is code scattered around that handles (or not) "trailing `1`s". All other languages have the raw lexicon transcribed in SAMPA. To be honest, I have no idea why the raw CMUdict was not converted to SAMPA in a preprocessing step, but as a result, the trained LTS rules apparently emit random `1`s to indicate stress...

Workaround for now: `apple juice`:point_right:`' { - p @ l` `' dZ u s`.

**Comment by seblemaguer** [comment]
commit a84e5d8f6d4e4b88e7768ace49d5bdfc8c6db0e5 should solved the global problem as the punctuation are now ignored in the phonetisation stage

**Comment by psibre** [comment]
Not solved completely: try `Rachael's`

**Comment by psibre** [comment]
...also `didn't`... oops. Certain other contractions are hackily stored in the `userdict-en_US.txt`, but not this one.

**Comment by fuzeller** [comment]
Hello, I'm having the same issue (Allophone `-' could not be found in AllophoneSet `sampa' (Locale: en_US)) when trying to use CMUDict2MaryFST, as it uses much of the same code.  I tried fix-285 in a new clone from git + mvn install against the default US lexicon and got the same error. I verified the 'getIgnoreChars' code was in my copy of 'AllophoneSet'. I'd be happy to provide log data if it could help.

My intent with the CMUDict2MaryFST is to build a new dialect with additional allophones, so this test with the default code suggests I won't be able to just yet.

Thank you.

**Comment by NeptunSun** [comment]
Hello, I am always getting this error when I call "transcription.sh" script for Transcribe most frequent words. But When I try early version MaryTTS I am successfully pass this step without error.


java.lang.IllegalArgumentException: Allophone `'' could not be found in AllophoneSet `sampa' (Locale: az)
	at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:550)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:215)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$800(TranscriptionGUI.java:52)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by psibre** [comment]
FIxed along with #341.

Now we get:
### TEXT
```
Rachael's scalable applejuice
```

### PHONEMES
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<voice name="cmu-slt-hsmm">
<s>
<mtu orig="Rachael's">
<t g2p_method="rules" ph="' r { tS l" pos="NN">
rachael
</t>
<t ph="z" pos="POS">
's
</t>
</mtu>
<t g2p_method="rules" ph="' s k A - l @ - b @ l" pos="JJ">
scalable
</t>
<t g2p_method="rules" ph="' { l - p j u - I s" pos="NN">
applejuice
</t>
</s>
</voice>
</p>
</maryxml>
```

**Comment by JSefara** [comment]
Error  while running TranscriptionAligner from voiceimport tools.

**Allophone `\' could not be found in AllophoneSet `sampa' (Locale: nbl)**

data0001.txt = Agcwalise nanyana ngiwuphi umtlolo ohlathulula iinkhathi zokungena kwakho  emsebenzini, zokudla nezokutjhayisa njalonjalo.

traversing through 994 files
data_0001
/voice/ndebele/lab/data_0001.lab
Orig   : _|a|g||\|w|a|l|i|s|E|_|n|a|J|a|n|a|_|N|g|i|w|u|p_h|i|_|u|m|t_>|l|O|l|O|_|O|K|a|t_h|u|l|u|l|a|_|i|N|k_h|a|t_h|i|_|z|O|k|u|N|g|E|n|a|_|k|w|a|k_h|O|_|E|m|s|E|b_<|E|n|z|i|n|i|_|z|O|k|u|K\|a|_|n|E|z|O|k|u|t_>|a|j|i|s|a|_|n|a|l|O|n|a|l|O|_
Correct: _|a|g||\|w|a|l|i|s|E|n|a|J|a|n|a|N|g|i|w|u|p_h|i|u|m|t_>|l|O|l|O|O|K|a|t_h|u|l|u|l|a|i|N|k_h|a|t_h|i|z|O|k|u|N|g|E|n|a|k|w|a|k_h|O|E|m|s|E|b_<|E|n|z|i|n|i|_|z|O|k|u|K\|a|n|E|z|O|k|u|t_>|a|j|i|s|a|n|a|l|O|n|a|l|O|_
Alignments:  _ # a # g #  # \ # w # a # l # i # s # E # # n # a # J # a # n # a # # N # g # i # w # u # p_h # i # # u # m # t_> # l # O # l # O # # O # K # a # t_h # u # l # u # l # a # # i # N # k_h # a # t_h # i # # z # O # k # u # N # g # E # n # a # # k # w # a # k_h # O # # E # m # s # E # b_< # E # n # z # i # n # i # _ # z # O # k # u # K\ # a # # n # E # z # O # k # u # t_> # a # j # i # s # a # # n # a # l # O # n # a # l # O # _ 
Boundary, align =  _ 
Ph = a, align =  a 
Ph = g, align =  g 
Ph = |\, align =   
Ph = w, align =  \ 
Ph = a, align =  w 
Ph = l, align =  a 
Ph = i, align =  l 
Ph = s, align =  i 
Ph = E, align =  s 
 inserted phone from transcription: E
Ph = n, align =  
Ph = a, align =  n 
Ph = J, align =  a 
Ph = a, align =  J 
Ph = n, align =  a 
Ph = a, align =  n 
 inserted phone from transcription: a
Ph = N, align =  
Ph = g, align =  N 
Ph = i, align =  g 
Ph = w, align =  i 
Ph = u, align =  w 
Ph = p_h, align =  u 
Ph = i, align =  p_h 
 inserted phone from transcription: i
Ph = u, align =  
Ph = m, align =  u 
Ph = t_>, align =  m 
Ph = l, align =  t_> 
Ph = O, align =  l 
Ph = l, align =  O 
Ph = O, align =  l 
 inserted phone from transcription: O
Ph = O, align =  
Ph = K, align =  O 
Ph = a, align =  K 
Ph = t_h, align =  a 
Ph = u, align =  t_h 
Ph = l, align =  u 
Ph = u, align =  l 
Ph = l, align =  u 
Ph = a, align =  l 
 inserted phone from transcription: a
Ph = i, align =  
Ph = N, align =  i 
Ph = k_h, align =  N 
Ph = a, align =  k_h 
Ph = t_h, align =  a 
Ph = i, align =  t_h 
 inserted phone from transcription: i
Ph = z, align =  
Ph = O, align =  z 
Ph = k, align =  O 
Ph = u, align =  k 
Ph = N, align =  u 
Ph = g, align =  N 
Ph = E, align =  g 
Ph = n, align =  E 
Ph = a, align =  n 
 inserted phone from transcription: a
Ph = k, align =  
Ph = w, align =  k 
Ph = a, align =  w 
Ph = k_h, align =  a 
Ph = O, align =  k_h 
 inserted phone from transcription: O
Ph = E, align =  
Ph = m, align =  E 
Ph = s, align =  m 
Ph = E, align =  s 
Ph = b_<, align =  E 
Ph = E, align =  b_< 
Ph = n, align =  E 
Ph = z, align =  n 
Ph = i, align =  z 
Ph = n, align =  i 
Ph = i, align =  n 
Boundary, align =  i 
  deleted boundary from xml
Ph = z, align =  _ 
Ph = O, align =  z 
Ph = k, align =  O 
Ph = u, align =  k 
Ph = K\, align =  u 
Ph = a, align =  K\ 
 inserted phone from transcription: a
Ph = n, align =  
Ph = E, align =  n 
Ph = z, align =  E 
Ph = O, align =  z 
Ph = k, align =  O 
Ph = u, align =  k 
Ph = t_>, align =  u 
Ph = a, align =  t_> 
Ph = j, align =  a 
Ph = i, align =  j 
Ph = s, align =  i 
Ph = a, align =  s 
 inserted phone from transcription: a
Ph = n, align =  
Ph = a, align =  n 
Ph = l, align =  a 
Ph = O, align =  l 
Ph = n, align =  O 
Ph = a, align =  n 
Ph = l, align =  a 
Ph = O, align =  l 
Boundary, align =  O 
  deleted boundary from xml
java.lang.Exception: The component TranscriptionAligner produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.InvalidDataException: Allophone `\' could not be found in AllophoneSet `sampa' (Locale: nbl)
	at marytts.tools.analysis.MaryTranscriptionAligner.alignXmlTranscriptions(MaryTranscriptionAligner.java:99)
	at marytts.tools.voiceimport.TranscriptionAligner.alignTranscription(TranscriptionAligner.java:152)
	at marytts.tools.voiceimport.TranscriptionAligner.compute(TranscriptionAligner.java:122)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)


Allophones.nbl.xml is at 
https://drive.google.com/open?id=0B9PpG3wXony0VDFDTVN6U1ZkZUU

**It looks like Transcription Aligner replaces phone |\ with \**
How to resolve this issue?

**Comment by psibre** [comment]
@JSefara This is a different issue from #285, even if the error message is similar, and so should have been a new, separate issue. Having said that, please avoid the use of backslashes in your allophone names and see if that solves your problem.

**Comment by JSefara** [comment]
@psibre. Thanks, it is solved.
