### ISSUE TITLE
F0PolynomialFeatureFileWriter cannot handle situation where no F0 contour can be computed

### ISSUE THREAD

**Issue by svendeswan** [marytts/marytts#290]
This error occured to me because I accidentially mixed 16kHz recording with 44.1kHz recording while creating a new voice using the voiceimport.sh toolkit. If you get this error check the F0PolynomialFeatureFileWriter.showGraph = true (in the Settings Editor) and repeat the process. You can then hear the audio sentence by sentence and probably you will find the faulty audio sequence.

The stack trace to this error is:

```
java.lang.Exception: The component F0PolynomialFeatureFileWriter
produced the following exception:
at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.NullPointerException
at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.getInterpolatedLogF0Contour(F0PolynomialFeatureFileWriter.java:344)
at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.writeUnitFeaturesTo(F0PolynomialFeatureFileWriter.java:512)
at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.compute(F0PolynomialFeatureFileWriter.java:208)
at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
```

This has been produced by the 5-2-Snapshot version

Cheers,
Sven

**Comment by psibre** [comment]
@svendeswan thanks for the report and the workaround!

**Comment by psibre** [comment]
As pointed out privately by @svendeswan this was also previously TRACked as [ticket:339](http://mary.opendfki.de/ticket/339).

**Comment by lesvizit** [comment]
What should we do when we have ensured that all the recordings have the same frequence (44.1Khz)?

**Comment by Georgakopoulos** [comment]
I have a very similar problem, but I could not find any files that are of a different frequency than 16000Hz.
```java
INFO  F0PolynomialFeatureFileWriter: F0 polynomial feature file writer started.
java.lang.Exception: The component F0PolynomialFeatureFileWriter produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: java.lang.NullPointerException
	at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.getInterpolatedLogF0Contour(F0PolynomialFeatureFileWriter.java:344)
	at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.writeUnitFeaturesTo(F0PolynomialFeatureFileWriter.java:512)
	at marytts.tools.voiceimport.F0PolynomialFeatureFileWriter.compute(F0PolynomialFeatureFileWriter.java:208)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
```
I basically ignored the problem by setting the **F0PolynomialFeatureFileWriter.interpolate**	to **false** and it worked fine, but I don't know what influence this will have on my voice?
