### ISSUE TITLE
Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT

### ISSUE THREAD

**Issue by jetremote** [marytts/marytts#301]
Hello,

I installed MaryTTS with mvn install command from the root directory. Now I want to run mvn package in the user-examples directory but I get an error dependencies. How I can fix it?

Greetings

> mvn package -e -X
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-48-generic", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/ubuntu/.m2/settings.xml
[DEBUG] Using local repository at /home/ubuntu/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/ubuntu/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Could not find metadata marytts:marytts:5.1-beta2-SNAPSHOT/maven-metadata.xml in local (/home/ubuntu/.m2/repository)
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' points at de.dfki.mary:marytts instead of marytts:marytts, please verify your project structure @ line 3, column 10
[FATAL] Non-resolvable parent POM: Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project marytts:user-examples:5.1-beta2-SNAPSHOT (/home/ubuntu/Descargas/marytts/user-examples/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 3, column 10 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:813)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
	... 22 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact marytts:marytts:pom:5.1-beta2-SNAPSHOT
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
	... 26 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by jetremote** [comment]
Must be installed marytts:marytts:5.1-beta2-SNAPSHOT in the local repository?

**Comment by psibre** [comment]
The `user-examples` were removed from the main code a long time ago and have not been updated. If you want to build something similar, you should take care to ensure that the dependencies can be resolved, i.e., that your POM is configured with the correct version.

Note that if all you want to do is build a standalone project that uses MaryTTS as a dependency, the artifacts can also be resolved through [Bintray/JCenter](https://bintray.com/bintray/jcenter/) and [OJO](https://oss.jfrog.org/).

**Comment by jetremote** [comment]
Thank you for your reply. I have not had time to continue working on it, but when I can I will consider its recommendations.

Greetings

**Comment by Abdull** [comment]
> The user-examples were removed from the main code a long time ago and have not been updated.

the user-examples still seem to be distributed with the main code as of 2015-04-26 ( https://github.com/marytts/marytts/tree/master/user-examples ).
