### ISSUE TITLE
Internal server error for non-special character texts

### ISSUE THREAD

**Issue by jorrig** [marytts/marytts#321]
I get the following error when trying to synthesize .txt files that do NOT contain special characters, such as umlauted vowels:

```
Traceback (most recent call last):
  File "../call_mary.py", line 49, in <module>
    raise Exception(content)
Exception: b"<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module JPhonemiser_de: Problem processing the data.\n\tat marytts.server.Request.processOneChunk(Request.java:549)\n\tat marytts.server.Request.processOrLookupOneChunk(Request.java:385)\n\tat marytts.server.Request.process(Request.java:327)\n\tat marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)\n\tat marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)\n\tat marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)\n\tat org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)\n\tat org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)\n\tat org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)\n\tat org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)\n\tat org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)\n\tat org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)\n\tat org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)\n\tat org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.IllegalArgumentException: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: de)\n\tat marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)\n\tat marytts.modules.phonemiser.Syllabifier.correctStressSymbol(Syllabifier.java:297)\n\tat marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:252)\n\tat marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:52)\n\tat marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:166)\n\tat marytts.language.de.JPhonemiser.phonemise(JPhonemiser.java:349)\n\tat marytts.language.de.JPhonemiser.process(JPhonemiser.java:232)\n\tat marytts.server.Request.processOneChunk(Request.java:547)\n\t... 19 more\n</pre></body></html>"
```

Interestingly, txt files that do contain umlauts work fine. The input files are UTF-8 encoded.
I'm running a local marytts server on OSX 10.10.3.

**Comment by psibre** [comment]
```
java.lang.Exception: Module JPhonemiser_de: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:549)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: de)
	at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
	at marytts.modules.phonemiser.Syllabifier.correctStressSymbol(Syllabifier.java:297)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:252)
	at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:52)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:166)
	at marytts.language.de.JPhonemiser.phonemise(JPhonemiser.java:349)
	at marytts.language.de.JPhonemiser.process(JPhonemiser.java:232)
	at marytts.server.Request.processOneChunk(Request.java:547)
	... 19 more
```
FTFY

**Comment by psibre** [comment]
This is actually due to an open issue related to syllabification of unknown words.
As a workaround, try using version 5.1.1.
