### ISSUE TITLE
Bug for italian language inside JPhonemiser module.

### ISSUE THREAD

**Issue by gmiano** [marytts/marytts#322]
Hi,
I would like to report a bug that stops text synthesis for italian language. Here I post the error:

java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Cannot syllabify empty phone string
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:450)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:236)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:164)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 19 more

I used a workaround to correct the error. I modified line 148 inside JPhonemiser.java and substituted
Matcher m = p.matcher(pos);   ---------> Matcher m=p.matcher(text);

**Comment by giuliopaci** [comment]
Can you provide a sample text that triggers the error?

**Comment by gmiano** [comment]
You can try with the example test:
"Benvenuto nel mondo della sintesi vocale."

Without a dot it works, but when dot is present an exception is thrown.

**Comment by giuliopaci** [comment]
Thank you for the sample and the bug report.

The error has been introduced a few months ago in the "generic" JPhonemiser.
I do not know what was the purpose of the patch that introduced the regression, as I am using a very different codebase now. However the code is failing because it is expecting the POS tag name of punctuation to be composed of punctuation characters, as it happens for English, and not acronyms (e.g., "FS", Final Stop) as it happens for Italian.
Your workaround is working in this specific case because the text value of the punctuation token is also made of punctuation characters.

Unfortunately I do not think to be able to provide a real solution for this issue: looking at other languages the standard solution is to copy the JPhonemiser.java in the Italian directory, change the module to use it and then fix it for the specific language.

I believe that a better approach would be to generalize JPhonemiser.java, make it extensible either via parameters or via inheritance and then customize it in the language modules.
However when I tried to propose it a couple years ago, any patch I proposed in this direction has not been accepted.

**Comment by psibre** [comment]
@giuliopaci Thanks for your input! What started as a reimplementation of the buggy old syllabifier has turned into a major operation... that sadly added several regressions, because we weren't exhaustively testing all languages.
Currently we're rebuilding the LTS resources, which were still emitting ARPA-style stress notation...

**Comment by Munzey** [comment]
this could be alleviated as @giuliopaci says by creating a JPhonemiser class inside of the italian language and altering the regex pattern used (i.e. changing the `MaryConstants.PUNCT_POS_REGEXP`) but a somewhat better workaround is to  make sure that if there is no phone prediction for a token, to just make sure it doesn't get a `ph` attribute.

**Comment by psibre** [comment]
@gmiano @giuliopaci For the record, the issue with with the dot and the `pos="FS` is tracked as #298 and #309.

Meanwhile, we're patching things up so that at least no exceptions are thrown in such cases.
