### ISSUE TITLE
NullPointerException when syllabifying "'s"

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#342]
When syllabifying input text such as *90s*, the text normalization produces a token that cannot be syllabified:

### TEXT
```
90s
```
#### PARTSOFSPEECH
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<voice name="cmu-slt-hsmm">
<s>
<mtu orig="90s">
<t pos="NN">
ninety
</t>
<t pos="POS">
's
</t>
</mtu>
</s>
</voice>
</p>
</maryxml>

```

### PHONEMES
```
Internal server error

Processing failed.

java.lang.Exception: Module JPhonemiser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:554)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:163)
	at marytts.modules.JPhonemiser.phonemise(JPhonemiser.java:237)
	at marytts.modules.JPhonemiser.process(JPhonemiser.java:164)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 19 more
```

**Comment by psibre** [comment]
For the record, we now get the expected
### PHONEMES
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<voice name="cmu-slt-hsmm">
<s>
<mtu orig="90s">
<t g2p_method="lexicon" ph="' n AI n - t i" pos="NN">
ninety
</t>
<t g2p_method="rules" ph="' s" pos="POS">
's
</t>
</mtu>
</s>
</voice>
</p>
</maryxml>
```
