### ISSUE TITLE
NoClassDefFoundError when running marytts-server

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#365]
After #364 there is now a runtime classpath error related to groovy missing:
```
$ target/marytts-5.2-SNAPSHOT/bin/marytts-server
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

MARY server 5.2-SNAPSHOT starting as a HTTP server...Exception in thread "main" java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at marytts.util.MaryRuntimeUtils.instantiateObject(MaryRuntimeUtils.java:118)
	at marytts.modules.ModuleRegistry.instantiateModule(ModuleRegistry.java:87)
	at marytts.server.Mary.startModules(Mary.java:130)
	at marytts.server.Mary.startup(Mary.java:291)
	at marytts.server.Mary.startup(Mary.java:201)
	at marytts.server.Mary.main(Mary.java:491)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:363)
	at marytts.server.Mary$2.run(Mary.java:284)
```

**Comment by psibre** [comment]
Following 311e6403c22a77cec06fbf431ddf62be6f40e7f9 we now get this error with `voice-cmu-slt-hsmm:
```
[ERROR] Failed to execute goal org.codehaus.gmaven:gmaven-plugin:1.5:execute (default) on project voice-cmu-slt-hsmm: Execution default of goal org.codehaus.gmaven:gmaven-plugin:1.5:execute failed: An API incompatibility was encountered while executing org.codehaus.gmaven:gmaven-plugin:1.5:execute: java.lang.NoSuchMethodError: org.codehaus.groovy.ast.ModuleNode.getStarImports()Ljava/util/List;
```
This is related to the use of a `gmaven` script block when packaging that voice.

Actually it had been a thorn in our side for a while, but at this point, it's hurting.
