### ISSUE TITLE
Luxembourgish locale not supported in FeatureSelection component

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#370]
Trying to build a voice with locale `lb` fails with the legacy voicebuilding tools:
```
Mary TTS client 5.2-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2-SNAPSHOT (impl. unknown)
java.lang.Exception: The component FeatureSelection produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: 400:Bad Request
<html><body><h1>Bad request</h1><p>The value 'lb' of parameter 'locale' is not valid: The locale is not supported.<br />Supported locales: <code>de,en_GB,en_US,fr,it,ru,sv,te,tr</code>.</h1></body></html>
	at marytts.client.http.MaryHttpClient.serverInfoRequest(MaryHttpClient.java:302)
	at marytts.client.http.MaryHttpClient.serverInfoRequest(MaryHttpClient.java:287)
	at marytts.client.http.MaryHttpClient.getDiscreteFeatures(MaryHttpClient.java:265)
	at marytts.tools.voiceimport.FeatureSelection.compute(FeatureSelection.java:141)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

**Comment by psibre** [comment]
Just to clarify, the `lb` locale **is** on the classpath, and [http://localhost:59125/locales](http://localhost:59125/locales) returns
```
lb
it
ru
fr
en_US
en_GB
de
sv
te
tr
```

**Comment by psibre** [comment]
Oops, it seems that no `featuremanager.classes.list` is defined in `lb.config`...
