### ISSUE TITLE
VoiceCompiler failure

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#375]
The VoiceCompiler's template files were left out of recent improvements and fixes.
So now, running it fails, for various reasons, with the less-than-informative error,
```
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Cannot run program "mvn" (in directory "[...]"): error=2, No
 such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:329)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:91)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```

**Comment by psibre** [comment]
Believing that [running `mvn`](../blob/195df7f1c7295493c000a0aa07468499f662c561/marytts-builder/src/main/java/marytts/tools/voiceimport/VoiceCompiler.java#L323) will simply work is a pretty strong assumption.
Possibly more robust alternatives might be [Maven Invoker](http://maven.apache.org/shared/maven-invoker/) or [Maven Embedder](http://maven.apache.org/ref/3-LATEST/maven-embedder/) (see also http://stackoverflow.com/q/5141788), but both require configuration that would be system-specific (such as the path to `mvn`, so we'd be back we're we started).
We don't want to over-engineer a solution at this point, because the marytts-builder will soon be replaced anyway. So providing a new configurable property with a reasonable default is probably the best solution:
```
VoiceCompiler.mavenBin /usr/bin/mvn
```
