### ISSUE TITLE
PhoneUnitFeatureComputer cannot parse Luxembourgish MaryXML

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#377]
The ad-hoc `g2p_method` attribute value `lexicon_fr` in [LuxembourgishPhonemiser](../blob/143b2b1ddfeea1a58fbf87115e98f8c962d18df0/marytts-languages/marytts-lang-lb/src/main/groovy/marytts/language/lb/LuxembourgishPhonemiser.groovy#L45-L47), intended to highlight when out-of-vocabulary tokens are phonemised by consulting the French lexicon, is causing XML validation errors in production, such as when building a Luxembourgish voice, in the PhoneUnitFeatureComputer:
```
Mary TTS client 5.2-SNAPSHOT (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2-SNAPSHOT (impl. unknown)
java.lang.Exception: The component PhoneUnitFeatureComputer produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Problem reading input<pre>org.xml.sax.SAXParseException; lineNumber: 33; columnNumber: 59; cvc-enumeration-valid: Value 'lexicon_fr' is not facet-v
alid with respect to enumeration '[lexicon, userdict, compound, rules, foreign:en, phonemiseDenglish]'. It must be a value from the enumeration.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:437)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:325)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:458)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3237)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processOneAttribute(XMLSchemaValidator.java:2832)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2769)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2056)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:379)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at marytts.util.dom.DomUtils.parseDocument(DomUtils.java:142)
	at marytts.util.dom.DomUtils.parseDocument(DomUtils.java:121)
	at marytts.datatypes.MaryData.setData(MaryData.java:214)
	at marytts.server.Request.setInputData(Request.java:245)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:220)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
	at marytts.client.MaryClient.process(MaryClient.java:653)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.computeFeaturesFor(PhoneUnitFeatureComputer.java:180)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.compute(PhoneUnitFeatureComputer.java:166)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:388)
	... 5 more
```

**Comment by psibre** [comment]
As a workaround, the MaryTTS *server* can be started with `-Dmaryxml.validate.input=false`.

**Comment by psibre** [comment]
stable workaround might be to use XSD conformant `g2p_method` attribute value, but add another one for the lexicon source, i.e., `fr` etc.

**Comment by psibre** [comment]
It turns out that this error can no longer be reproduced when using the [gradle voicebuilding plugin](https://github.com/marytts/gradle-marytts-voicebuilding-plugin) -- shifting to the [BatchProcessor](https://github.com/marytts/gradle-marytts-voicebuilding-plugin/blob/db3e2d5cb0af3408ded3d7dd34530f8a7f1f1677/marytts-voicebuilding/src/main/groovy/marytts/BatchProcessor.groovy) in marytts/gradle-marytts-voicebuilding-plugin@70658eced6d43c07e6d2ed47b945fb8e794f53de has made this issue obsolete.
