### ISSUE TITLE
Dependency missing: noclassdeffounderror org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by timobaumann** [marytts/marytts#394]
I'm using MaryTTS in a webstart application. In particular, marytts-client-5.2-SNAPSHOT-jar-with-dependencies.jar and marytts-runtime-5.2-SNAPSHOT-jar-with-dependencies.jar are in my classpath. However, javaws complains about the missing ElementTraversal class. This class is not part of either jar. It turns out that on my system, I find this class in xml-apis-1.4.01.jar which is part of xalan/xerces/xomething. However, webstart seems to not read anything from /usr/share/java, so it doesn't find the class.

It appears that a dependency is missing to xalan/xerces/xml-apis when constructing the jar-with-depencies.jar, as I would expect all dependent classes in there. 

Unfortunately, my knowledge of maven is too limited to provide a fix.

**Comment by aitorme** [comment]
HI @timobaumann I just tried to reproduce the error that you mentioned above but my marytts-client works perfectly: the GUI client runs and it processes the input text. Are you running the latest version with all the ultimate commits and, if you are, could you please give further detail of the problem? Everything seems fine on my computer...

**Comment by seblemaguer** [comment]
Hello,

as webstart is not reading anything from /usr/share/java, have you checked the configuration of it ? I mean, the packages "-with-dependencies" does not contain any system library.

**Comment by timobaumann** [comment]
I think it's not supposed to read anything from /usr/share/java. Notice that this directory does not contain the system library, which instead is contained in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/. It's containing things like log4j, which Mary also includes in the -with-dependencies package. I guess something like this: 
<dependency>
	<groupId>xml-apis</groupId>
	<artifactId>xml-apis</artifactId>
	<version>2.0.2</version>
</dependency>
is missing in the pom. Although, again, I don't know too little about maven to be certain about what exactly is the right dependency.

**Comment by seblemaguer** [comment]
ok thanks for clarification (I was assuming that your /usr/share/java was your system java directory). Normally, xml-apis is a transitive of another package. I will check which one now. 

Assuming you are using linux/ubuntu (can you indicate if it's the case ?), if you have installed the package which provided xml-apis using apt-get (for me it is this one libjaxp1.3-java, for you it should be libjaxp1.4-java or something like that) or if you have installed a package which is depending on this one therefore maven consider it's a system based package and does not deal with it. That's why, it does not include it by default on the "with-dependencies" package. 

I'm saying that because after inspecting this package I found a file with this path after extraction "/usr/share/java/xml-apis-1.3.04.jar" which looks like yours

**Comment by psibre** [comment]
I would strongly advise against trying to manage java dependencies using some linux package manager, trying to debug it is a can of worms, and any solutions will be specific to the linux distro, version, etc.

I would rather try to debug whether something else is going on.

Do you have a transitive dependency on `xalan` by any change?

**Comment by timobaumann** [comment]
I'm using ubuntu 15.04. Among other things, gradle depends (via apt-get) on the package that you mention -- some friends in Saarbrücken will be unhappy if I uninstall it..

**Comment by timobaumann** [comment]
@psibre I can't help my operating system installing jars somewhere. 
It's surprising that maven's behaviour for "-with-dependencies" depends on what is installed on the local machine. 
In any case, "grep xalan marytts-*/pom.xml" does not return anything.

**Comment by psibre** [comment]
gradle should remap transitive dependency conflict...
```
+--- edu.stanford.nlp:stanford-corenlp:3.5.2
|    |    +--- com.io7m.xom:xom:1.2.10
|    |    |    +--- xml-apis:xml-apis:1.3.03 -> 2.0.2
|    |    |    +--- xerces:xercesImpl:2.8.0
|    |    |    |    \--- xml-apis:xml-apis:1.3.03 -> 2.0.2
|    |    |    \--- xalan:xalan:2.7.0
|    |    |         \--- xml-apis:xml-apis:2.0.2
```
...and issue a warning:
```
POM relocation to an other version number is not fully supported in Gradle : xml-apis#xml-apis;2.0.2 relocated to xml-apis#xml-apis;1.0.b2.
Please update your dependency to directly use the correct version 'xml-apis#xml-apis;1.0.b2'.
Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
```
Crucially, however, the [gradle package in Ubuntu 15.04](http://packages.ubuntu.com/vivid/gradle) is outrageously obsolete. You really should use the [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html).

**Comment by timobaumann** [comment]
I'm building some software with Maven, on a computer that happens to have an outdated Gradle installed (alongside tons of other outdated software, but it's the most used linux distribution in its newest version). The software that I am building fails. What is at fault? The software? Maven? Gradle (which wasn't even close to working memory at that time)? I don't think that gradle is at fault here. I could just as well have mentioned fop (probably as outdated) as depending on the locally installed xml-apis.

**Comment by psibre** [comment]
I strongly recommend you just build the thing with gradle using the wrapper. Apart from the JDK installation, everything else would be platform-independent.

If your source code is public, feel free to link to it and we'll see if we can debug it.

**Comment by timobaumann** [comment]
"some software" was referring to Mary :-) So, what I was doing, was to call "mvn target" in my marycheckout and then to have a look at the mary....-with-dependencies.jar. And it turns out, some classes that mary actually depend on are not in that Jar. 

FATAL ERROR:  'Datentyp "void" kann nicht in "boolean" konvertiert werden.'
           :Datentyp "void" kann nicht in "boolean" konvertiert werden.
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:65)
	at inpro.synthesis.MaryAdapter5internal.<init>(MaryAdapter5internal.java:41)
	at inpro.synthesis.MaryAdapter.initializeMary(MaryAdapter.java:64)
	at inpro.synthesis.MaryAdapter.initializeMary(MaryAdapter.java:52)
	at inpro.synthesis.MaryAdapter.getInstance(MaryAdapter.java:78)
	at inpro.incremental.processor.SynthesisModule.<init>(SynthesisModule.java:56)
	at inpro.incremental.processor.SynthesisModule.<init>(SynthesisModule.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:507)
	at edu.cmu.sphinx.util.props.ConfigurationManager.lookup(ConfigurationManager.java:161)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponentList(PropertySheet.java:422)
	at inpro.apps.SimpleText.main(SimpleText.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:564)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:904)
Caused by: java.lang.Exception: Problem starting module EmotionmlParser
	at marytts.server.Mary.startModules(Mary.java:150)
	at marytts.server.Mary.startup(Mary.java:298)
	at marytts.server.Mary.startup(Mary.java:205)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:71)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
	... 21 more
Caused by: javax.xml.transform.TransformerConfigurationException: Datentyp "void" kann nicht in "boolean" konvertiert werden.
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1015)
	at marytts.modules.EmotionmlParser.startup(EmotionmlParser.java:78)
	at marytts.server.Mary.startModules(Mary.java:148)
	... 25 more
Caused by: Datentyp "void" kann nicht in "boolean" konvertiert werden.
	at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.typeCheck(CastExpr.java:187)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.<init>(CastExpr.java:143)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.LogicalExpr.typeCheck(LogicalExpr.java:148)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Predicate.typeCheck(Predicate.java:286)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.StepPattern.typeCheck(StepPattern.java:197)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:292)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:493)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:657)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:411)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:486)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:571)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:974)
	... 27 more
2015-10-02 15:43:48,124: INFO  inpro.synthesis.MaryAdapter  - could not start MaryAdapter
1565 [InproTk Type-to-Speech Demo] INFO inpro.synthesis.MaryAdapter  - could not start MaryAdapter
java.lang.RuntimeException: marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at inpro.synthesis.MaryAdapter5internal.<init>(MaryAdapter5internal.java:44)
	at inpro.synthesis.MaryAdapter.initializeMary(MaryAdapter.java:64)
	at inpro.synthesis.MaryAdapter.initializeMary(MaryAdapter.java:52)
	at inpro.synthesis.MaryAdapter.getInstance(MaryAdapter.java:78)
	at inpro.incremental.processor.SynthesisModule.<init>(SynthesisModule.java:56)
	at inpro.incremental.processor.SynthesisModule.<init>(SynthesisModule.java:48)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at edu.cmu.sphinx.util.props.PropertySheet.getOwner(PropertySheet.java:507)
	at edu.cmu.sphinx.util.props.ConfigurationManager.lookup(ConfigurationManager.java:161)
	at edu.cmu.sphinx.util.props.PropertySheet.getComponentList(PropertySheet.java:422)
	at inpro.apps.SimpleText.main(SimpleText.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:564)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:904)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:65)
	at inpro.synthesis.MaryAdapter5internal.<init>(MaryAdapter5internal.java:41)
	... 20 more
Caused by: java.lang.Exception: Problem starting module EmotionmlParser
	at marytts.server.Mary.startModules(Mary.java:150)
	at marytts.server.Mary.startup(Mary.java:298)
	at marytts.server.Mary.startup(Mary.java:205)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:71)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:63)
	... 21 more
Caused by: javax.xml.transform.TransformerConfigurationException: Datentyp "void" kann nicht in "boolean" konvertiert werden.
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1015)
	at marytts.modules.EmotionmlParser.startup(EmotionmlParser.java:78)
	at marytts.server.Mary.startModules(Mary.java:148)
	... 25 more
Caused by: Datentyp "void" kann nicht in "boolean" konvertiert werden.
	at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.typeCheck(CastExpr.java:187)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.<init>(CastExpr.java:143)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.LogicalExpr.typeCheck(LogicalExpr.java:148)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Predicate.typeCheck(Predicate.java:286)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.StepPattern.typeCheck(StepPattern.java:197)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:292)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:493)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:657)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:411)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:486)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:571)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:974)
	... 27 more

**Comment by timobaumann** [comment]
try: http://timobaumann.de/work/inprotk/webstart1.1/type-to-speech-en.jnlp . Works like a charm. 

Then, download the file, comment out the references to xalan2, serializer and xercesImpl and restart from the console (javaws). Get the above error in emotionML initialization.

**Comment by timobaumann** [comment]
I believe the problem could be connected with the first few lines in /marytts-runtime/src/main/resources/marytts/modules/emotionml-to-maryxml.xsl, in particular: xmlns:helpers="xalan://emotionml.xslt.Helpers". That's why /marytts-runtime/src/main/java/marytts/modules/EmotionmlParser.java can build without Xalan, but dies in startup when Xalan is not available. This missing-dependency bug is only exhibited by webstart as it ignores /usr/share/java/*.jar (whereas other Java instances apparently include it by default?) but not caused by webstart.

**Comment by seblemaguer** [comment]
Thanks for the precision. I will have a look at that
