### ISSUE TITLE
http://mary.dfki.de/ offline

### ISSUE THREAD

**Issue by lisitso** [marytts/marytts#396]
Hi, I'm unable to access the webite http://mary.dfki.de/
so any download from http://mary.dfki.de/download is not possible.

Please could you check it?

the component installer fails as follow:

Starting installation
Now installing istc-lucia-hsmm...
Trying location http://mary.dfki.de/download/5.1/voice-istc-lucia-hsmm-5.1.zip...
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at marytts.tools.install.ComponentDescription$Downloader.openAndRedirectIfRequired(ComponentDescription.java:662)
        at marytts.tools.install.ComponentDescription$Downloader.run(ComponentDescription.java:698)
        at marytts.tools.install.ComponentDescription.download(ComponentDescription.java:361)
        at marytts.tools.install.ProgressPanel.run(ProgressPanel.java:208)
        at java.lang.Thread.run(Thread.java:744)

**Comment by psibre** [comment]
Indeed, the main server is currently down following a power failure. But we already opened #395.

**Comment by psibre** [comment]
For the record, the server is back up.
