### ISSUE TITLE
Unsupported characters in Transcription Tool?

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#406]
Hi guys,

when generating a fst file with my lexicon it get this error:

```
ava.io.IOException: Cannot write transducer: too many arc-labels to be encoded in binary fst format (would need 12 bits, have 11)
	at marytts.fst.TransducerTrie.writeFST(TransducerTrie.java:90)
	at marytts.tools.transcription.TranscriptionTableModel.createLexicon(TranscriptionTableModel.java:498)
	at marytts.tools.transcription.TranscriptionTable.saveTranscription(TranscriptionTable.java:261)
	at marytts.tools.transcription.TranscriptionGUI.saveToFileActionPerformed(TranscriptionGUI.java:618)
	at marytts.tools.transcription.TranscriptionGUI.access$11(TranscriptionGUI.java:612)
	at marytts.tools.transcription.TranscriptionGUI$11.actionPerformed(TranscriptionGUI.java:477)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

probably because of a unsupported character on the left side (grapheme)?!

Generating lts rules works fine:
```
Training decision tree for: č
Training decision tree for: ș
Training decision tree for: ř
Training decision tree for: ń
Training decision tree for: ß
Training decision tree for: ł
Training decision tree for: ō
Training decision tree for: ň
Training decision tree for: null
Training decision tree for: f
Training decision tree for: î
Training decision tree for: g
Training decision tree for: d
Training decision tree for: í
Training decision tree for: e
Training decision tree for: b
Training decision tree for: ë
Training decision tree for: c
Training decision tree for: ê
Training decision tree for: é
Training decision tree for: a
Training decision tree for: è
Training decision tree for: n
Training decision tree for: ç
Training decision tree for: æ
Training decision tree for: o
Training decision tree for: l
Training decision tree for: å
Training decision tree for: m
Training decision tree for: ä
Training decision tree for: ž
Training decision tree for: j
Training decision tree for: ã
Training decision tree for: k
Training decision tree for: â
Training decision tree for: h
Training decision tree for: á
Training decision tree for: ź
Training decision tree for: i
Training decision tree for: à
Training decision tree for: w
Training decision tree for: v
Training decision tree for: ü
Training decision tree for: u
Training decision tree for: t
Training decision tree for: s
Training decision tree for: ú
Training decision tree for: š
Training decision tree for: r
Training decision tree for: q
Training decision tree for: ø
Training decision tree for: ù
Training decision tree for: p
Training decision tree for: ö
Training decision tree for: ô
Training decision tree for: ů
Training decision tree for: õ
Training decision tree for: ò
Training decision tree for: z
Training decision tree for: ó
Training decision tree for: y
Training decision tree for: ñ
Training decision tree for: x
```
 
Should there be a null character? Which characters could be handled as null? 

And what might trigger the arc-label error? 

Thanks

**Comment by seblemaguer** [comment]
@entenbein happy to see that you solved your problem but can you please indicate how do you manage to solve it ?

**Comment by entenbein** [comment]
Hi,

the code of `LTSTrainer` suggests that `null` represents the empty string. So I guess it's ok, that it appears there when training LTS rules.

Not quite sure what solved the error mentioned first though ...
