### ISSUE TITLE
Crash when running PhoneUnitFeatureComputer

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#419]
Hi folks,

I got a problem running PhoneUnitFeatureComputer which causes this error:

```
java.lang.Exception: The component PhoneUnitFeatureComputer produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module TargetFeatureLister: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:299)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No byte value known for string [4]
	at marytts.util.string.ByteStringTranslator.get(ByteStringTranslator.java:148)
	at marytts.features.MaryLanguageFeatureProcessors$PhoneFeature.process(MaryLanguageFeatureProcessors.java:215)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:140)
	at marytts.modules.TargetFeatureLister.listTargetFeatures(TargetFeatureLister.java:102)
	at marytts.modules.TargetFeatureLister.process(TargetFeatureLister.java:79)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:384)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:426)
	at marytts.client.MaryClient.process(MaryClient.java:631)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.computeFeaturesFor(PhoneUnitFeatureComputer.java:180)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.compute(PhoneUnitFeatureComputer.java:166)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:375)
	... 5 more
```

But when copying the whole request from the server.log and copying it to the web interface (input=ALLOPHONES, output=TARGETFEATURES), there is no error. Is it save / comparable to check it like this?

In this file there is no string like *4*. Might there be a mismapping or is this *4* not representable?

Thanks for your help!

**Comment by seblemaguer** [comment]
Have you checked the encoding of your input files ? You could have an unknown trailing character too

**Comment by entenbein** [comment]
Hi,

that's a good point. There seems to be no such thing in the sentence's file in `prompt_allophones` but in the `server.log` is one empty newline between a `<\t>` and the next `<t>`. 

Might this reference to such a character?

**Comment by seblemaguer** [comment]
The pause is not really a problem as the alignment part will solve that. However, have you checked the consistency between your phoneset and the labels ?

**Comment by entenbein** [comment]
Hi,

thanks for the hint. I found some unsupported/illegal phones. Not in the labels though (currently working on a small subset), but in my lexicon. This is fixed now, but the same error still occurs. 

Furthermore, there are more phones in the allophone set than in the subset of my data, but this shouldn't be a problem I guess...

**Comment by entenbein** [comment]
When training LTS rules, there **Training decision tree for: null**. The code of `LTSTrainer` suggests that this one represents the empty string. So is it ok, that it appears there when training LTS rules?
