### ISSUE TITLE
the system does not handle UTF-16 encoding

### ISSUE THREAD

**Issue by aitorme** [marytts/marytts#431]
while converting the [Assyria.txt](https://github.com/marytts/marytts/files/28882/Assyria.txt) file into phonemes, the system throws an error because of the UTF-16 encoding of the file, due possibly to the Akkadian cuneiform writing system. The error can be found, for instance after the text ```the city state of Ashur after which it was```
Other files with the same error found posteriorly are the following:
* [Bicycle.txt](https://github.com/marytts/marytts/files/28907/Bicycle.txt)
* [Cleopatra (disambiguation).txt](https://github.com/marytts/marytts/files/28908/Cleopatra.disambiguation.txt)
* [Delta (letter).txt](https://github.com/marytts/marytts/files/28909/Delta.letter.txt)
* [Deseret alphabet.txt](https://github.com/marytts/marytts/files/28910/Deseret.alphabet.txt) 
* [Enlil.txt](https://github.com/marytts/marytts/files/28912/Enlil.txt)

**Comment by YauhenMinsk** [comment]
@aitorme , could you attach the stacktrace?

**Comment by aitorme** [comment]
@YauhenMinsk sure, this is the stacktrace:
```
<stacktrace>groovy.lang.GroovyRuntimeException: org.xml.sax.SAXException: Invalid UTF-16 surrogate detected: d808 ?
java.io.IOException: Invalid UTF-16 surrogate detected: d808 ?
	at groovy.xml.XmlUtil.serialize(XmlUtil.java:451)
	at groovy.xml.XmlUtil.serialize(XmlUtil.java:437)
	at groovy.xml.XmlUtil.serialize(XmlUtil.java:55)
	at groovy.xml.XmlUtil$serialize.call(Unknown Source)
	at Text2Phonemes$_main_closure1.doCall(Text2Phonemes.groovy:32)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1038)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1056)
	at org.codehaus.groovy.runtime.dgm$790.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at Text2Phonemes.main(Text2Phonemes.groovy:27)
```

**Comment by psibre** [comment]
This has nothing to do with the MaryTTS code, but with [marytts-testing](/marytts/marytts-testing).
