### ISSUE TITLE
string of numbers too long to read

### ISSUE THREAD

**Issue by aitorme** [marytts/marytts#432]
while processing [Cifrario di Vernam.txt](https://github.com/marytts/marytts/files/30035/Cifrario.di.Vernam.txt), there is a 20-cipher-long number, which the system tries to read and synthesize.
Here is the stacktrace:
```
<stacktrace>marytts.exceptions.SynthesisException: cannot process
	at marytts.LocalMaryInterface.process(LocalMaryInterface.java:440)
	at marytts.LocalMaryInterface.generateXML(LocalMaryInterface.java:319)
	at marytts.MaryInterface$generateXML.call(Unknown Source)
	at Text2Phonemes$_main_closure1.doCall(Text2Phonemes.groovy:31)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1038)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1056)
	at org.codehaus.groovy.runtime.dgm$790.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at Text2Phonemes.main(Text2Phonemes.groovy:27)
Caused by: java.lang.Exception: Module Preprocess: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:550)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
	at marytts.server.Request.process(Request.java:327)
	at marytts.LocalMaryInterface.process(LocalMaryInterface.java:438)
	... 21 more
Caused by: java.lang.NumberFormatException: For input string: "10241056234530004000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:444)
	at java.lang.Long.parseLong(Long.java:483)
	at marytts.language.it.preprocess.NumberEP.expandInteger(NumberEP.java:258)
	at marytts.language.it.preprocess.NumberEP.expand(NumberEP.java:212)
	at marytts.language.it.preprocess.ExpansionPattern.process(ExpansionPattern.java:251)
	at marytts.language.it.Preprocess.matchAndExpandPatterns(Preprocess.java:105)
	at marytts.language.it.Preprocess.process(Preprocess.java:61)
	at marytts.server.Request.processOneChunk(Request.java:548)
	... 24 more
</stacktrace>
```
It also happens with [Coordinate bancarie.txt](https://github.com/marytts/marytts/files/31759/Coordinate.bancarie.txt), [Decadimento audioattivo.txt](https://github.com/marytts/marytts/files/31768/Decadimento.audioattivo.txt), [IEEE 754.txt](https://github.com/marytts/marytts/files/31769/IEEE.754.txt), [MDC-2.txt](https://github.com/marytts/marytts/files/31770/MDC-2.txt), [Numero automorfo.txt](https://github.com/marytts/marytts/files/31772/Numero.automorfo.txt), [Primoriale.txt](https://github.com/marytts/marytts/files/31773/Primoriale.txt), [Terna pitagorica.txt](https://github.com/marytts/marytts/files/31774/Terna.pitagorica.txt), [Test dei run.txt](https://github.com/marytts/marytts/files/31775/Test.dei.run.txt).

A solution to this issue could be to make the system read each cipher one by one when the length of the number is superior to 12 or ```one hundred billion```

**Comment by seblemaguer** [comment]
I think that's a good solution. Just make sure that the threshold can be parametrised. Set by default to 10^9.

**Comment by aitorme** [comment]
I just found out that this same number is skipped while using the English voice, whereas in German it is read as individual ciphers already.
For **Italian** the variable that is responsible for number processing is **```integer```**, 

```
DEBUG marytts.ExpansionPattern Found match, type number:integer: 10241056234530004000 (1 tokens)
```

For **German** the variable that is responsible for number processing is **```digits```**, 
```
DEBUG marytts.ExpansionPattern Found match, type number:digits: 10241056234530004000 (1 tokens)
```

**Comment by aitorme** [comment]
I close this issue, since it was solved with #437

**Comment by psibre** [comment]
@aitorme I don't see this solved by #437 since that PR only adds code for Italian.

@Rootex @seblemaguer Which languages are affected by this issue, and how?

**Comment by Rootex** [comment]
The issue only affects the italian language. 

The german language already handles this quite ok, which was where we got the idea to check the regex in the italian, and found out the expansion was to a hundred billion while the regex says till infinity.

However, while the other languages *en*, *fr*, *ru*, *Telugu* and *tur* skips the number totally because there is not *NumberExpansion* implemented in them. Maybe we should add a feature issue for this languages to support Number expansion?

**Comment by psibre** [comment]
@Rootex thanks for the clarification. Indeed, the output of
```bash
for locale in `curl -s http://localhost:59125/locales`
do
  curl -s -d LOCALE=$locale -d INPUT_TYPE=TEXT -d OUTPUT_TYPE=PHONEMES -d INPUT_TEXT=1234567890123456789 http://localhost:59125/process | xmllint --format -
done
```
by language is:

# German
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="de">
  <p>
    <s>
      <mtu accent="last" orig="1234567890123">
        <t g2p_method="lexicon" ph="' ? aI n s" pos="PIS">
eins
</t>
        <t g2p_method="lexicon" ph="' ts v aI" pos="CARD">
zwei
</t>
        <t g2p_method="lexicon" ph="' d R aI" pos="CARD">
drei
</t>
        <t g2p_method="lexicon" ph="' f i: 6" pos="CARD">
vier
</t>
        <t g2p_method="lexicon" ph="' f Y n f" pos="CARD">
fünf
</t>
        <t g2p_method="lexicon" ph="' z E k s" pos="CARD">
sechs
</t>
        <t g2p_method="lexicon" ph="' z i: - b @ n" pos="CARD">
sieben
</t>
        <t g2p_method="lexicon" ph="' ? a x t" pos="CARD">
acht
</t>
        <t g2p_method="lexicon" ph="' n OY n" pos="CARD">
neun
</t>
        <t g2p_method="lexicon" ph="' n U l" pos="CARD">
null
</t>
        <t g2p_method="lexicon" ph="' ? aI n s" pos="CARD">
eins
</t>
        <t g2p_method="lexicon" ph="' ts v aI" pos="CARD">
zwei
</t>
        <t g2p_method="lexicon" ph="' d R aI" pos="CARD">
drei
</t>
      </mtu>
    </s>
  </p>
</maryxml>
```

# Italian
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="it">
  <p>
    <s>
      <mtu accent="last" orig="1234567890123">
        <t g2p_method="lexicon" ph="' u1 - n o" pos="RI">
uno
</t>
        <t g2p_method="lexicon" ph="' d u1 - e" pos="N">
due
</t>
        <t g2p_method="rules" ph="' t r e" pos="N">
tre
</t>
        <t g2p_method="lexicon" ph="' k w a1 - tt r o" pos="N">
quattro
</t>
        <t g2p_method="lexicon" ph="' tS i1 NG - k w e" pos="N">
cinque
</t>
        <t g2p_method="lexicon" ph="' s E1 - i" pos="N">
sei
</t>
        <t g2p_method="lexicon" ph="' s E1 - tt e" pos="N">
sette
</t>
        <t g2p_method="lexicon" ph="' O1 - tt o" pos="N">
otto
</t>
        <t g2p_method="lexicon" ph="' n O1 - v e" pos="S">
nove
</t>
        <t g2p_method="lexicon" ph="' dz E1 - r o" pos="N">
zero
</t>
        <t g2p_method="lexicon" ph="' u1 - n o" pos="RI">
uno
</t>
        <t g2p_method="lexicon" ph="' d u1 - e" pos="N">
due
</t>
        <t g2p_method="rules" ph="' t r e" pos="N">
tre
</t>
      </mtu>
    </s>
  </p>
</maryxml>
```

# English
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
  <p>
    <s>
      <mtu orig="1234567890123">
        <t g2p_method="lexicon" ph="' w V n" pos="CD">
one
</t>
        <t g2p_method="lexicon" ph="' t r I l - j @ n" pos="CD">
trillion
</t>
        <t g2p_method="lexicon" ph="' t u" pos="CD">
two
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' T r= - d i" pos="CD">
thirty
</t>
        <t g2p_method="lexicon" ph="' f O r" pos="CD">
four
</t>
        <t g2p_method="lexicon" ph="' b I l - j @ n" pos="CD">
billion
</t>
        <t g2p_method="lexicon" ph="' f AI v" pos="CD">
five
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' s I k - s t i" pos="CD">
sixty
</t>
        <t g2p_method="lexicon" ph="' s E - v @ n" pos="CD">
seven
</t>
        <t g2p_method="lexicon" ph="' m I l - j @ n" pos="CD">
million
</t>
        <t g2p_method="lexicon" ph="' EI t" pos="CD">
eight
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' n AI n - t i" pos="CD">
ninety
</t>
        <t g2p_method="lexicon" ph="' T aU - z @ n d" pos="CD">
thousand
</t>
        <t g2p_method="lexicon" ph="' w V n" pos="CD">
one
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' t w E n - t i" pos="CD">
twenty
</t>
        <t g2p_method="lexicon" ph="' T r i" pos="CD">
three
</t>
      </mtu>
    </s>
  </p>
</maryxml>
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-GB">
  <p>
    <s>
      <mtu orig="1234567890123">
        <t g2p_method="lexicon" ph="' w V n" pos="CD">
one
</t>
        <t g2p_method="lexicon" ph="' t r I l - j @ n" pos="CD">
trillion
</t>
        <t g2p_method="lexicon" ph="' t u" pos="CD">
two
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' T r= - d i" pos="CD">
thirty
</t>
        <t g2p_method="lexicon" ph="' f O r" pos="CD">
four
</t>
        <t g2p_method="lexicon" ph="' b I l - j @ n" pos="CD">
billion
</t>
        <t g2p_method="lexicon" ph="' f AI v" pos="CD">
five
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' s I k - s t i" pos="CD">
sixty
</t>
        <t g2p_method="lexicon" ph="' s E - v @ n" pos="CD">
seven
</t>
        <t g2p_method="lexicon" ph="' m I l - j @ n" pos="CD">
million
</t>
        <t g2p_method="lexicon" ph="' EI t" pos="CD">
eight
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' n AI n - t i" pos="CD">
ninety
</t>
        <t g2p_method="lexicon" ph="' T aU - z @ n d" pos="CD">
thousand
</t>
        <t g2p_method="lexicon" ph="' w V n" pos="CD">
one
</t>
        <t g2p_method="lexicon" ph="' h V n - d r @ d" pos="CD">
hundred
</t>
        <t g2p_method="lexicon" ph="' t w E n - t i" pos="CD">
twenty
</t>
        <t g2p_method="lexicon" ph="' T r i" pos="CD">
three
</t>
      </mtu>
    </s>
  </p>
</maryxml>
```

# Russian
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="ru">
  <p>
    <s>
      <t pos="content">
1234567890123
</t>
    </s>
  </p>
</maryxml>
```

# Swedish
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="sv">
  <p>
    <s>
      <t pos="content">
1234567890123
</t>
    </s>
  </p>
</maryxml>
```

# Telugu
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="te">
  <p>
    <s>
      <t g2p_method="rules" ph="'" pos="content">
1234567890123
</t>
    </s>
  </p>
</maryxml>
```

# French
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="fr">
  <p>
    <s>
      <mtu orig="1234567890123">
        <t g2p_method="lexicon" ph="' 9~ - , b i - l j o~ - d @ - , s a~ - , t R a~ t - , k a - t R @ - , m i - l j a R - , s e~ k - , s a~ - , s w a - s a~ t - , s E t - , m i - l j o~ - , H i t - , s a~ - , k a - t R @ - , v e~ - , d i s - , m i l - , s a~ - , v e~ - , t R w a" pos="content">
un billion deux cent trente-quatre milliards cinq cent soixante-sept millions huit cent quatre-vingt-dix mille cent vingt-trois
</t>
      </mtu>
    </s>
  </p>
</maryxml>
```

# Luxembourgish
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="lb">
  <p>
    <s>
      <mtu orig="1234567890123">
        <t g2p_method="rules" ph="' { N - b i - l i - o - u n s - t v e: - h o - n @ R - t v 3 - I - @ - R A n - d R @ - s e - s m i - l i - A R - d @ n - f @ - n @ f - h o - n @ R - t s i - v { - n A - s i@ - { s - t s e - s m i - l i - o - u - n @ - n a: X - t h o - n @ R - t n o n - t s e s - d AU - z { n - d h o - n @ R t - d R {:I - A n s - t v A n - t s e s" pos="UNKN">
eng Billioun zweehonnertvéierandrësseg Milliarden fënnefhonnertsiwenasiechzeg Milliounen aachthonnertnonzegdausendhonnertdräianzwanzeg
</t>
      </mtu>
    </s>
  </p>
</maryxml>
```

# Turkish
```xml
<?xml version="1.0" encoding="UTF-8"?>
<maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="tr">
  <p>
    <s>
      <t pos="content">
1234567890123
</t>
    </s>
  </p>
</maryxml>
```

**Comment by psibre** [comment]
So Russian, Swedish, Telugu, and Turkish don't support (long) number expansion (and apparently never have). Which makes generic code, combined with language-specific `spellout-numbering` format rule resources even more attractive.

On the other hand, German and Italian just pronounce the digits.

Is it possible that there are language-specific limits to the number of digits that can be pronounced?

**Comment by aitorme** [comment]
@psibre which languages do you mean that could have limits to the number of digits?
Also, I was trying the French voice in the Mary server and it does not produce any output,was it lately changed in a particular commit? Maybe it can be taken from there to continue with the rest of the languages

**Comment by Rootex** [comment]
@psibre Yes, if i recall correctly the German and Italian say the number when its below a hundreds of billion e.g one hundred and twenty billion. However any number more than that it spells it out ( one, two e.t.c), as the implementation in their independent NumberExpansion does not go above that limit.

So in conclusion the the NumberEP for each has a limit of a hundred billion that can be pronounced for each of the two languages.

**Comment by Rootex** [comment]
@psibre I want to confirm if there is still more to this issue that needs handling?

**Comment by psibre** [comment]
@Rootex yes, you can close this issue again if there is no longer an exception thrown. I agree with your suggestion that there should be **enhancement** issues for those language that silently skip the numbers to pronounce them using spellout formatters instead. But those issues could then be assigned to a later milestone.

**Comment by Rootex** [comment]
Ok i will create the issue for those enhancements!
