### ISSUE TITLE
VoiceCompiler generates invalid package name from db.voicename property

### ISSUE THREAD

**Issue by entenbein** [marytts/marytts#458]
Hi guys,

Compiling a HMMVoice crashes at this stage:

```
[...]
INFO  HMMVoiceCompiler: Creating directories
INFO  HMMVoiceCompiler: Copying template files
INFO  HMMVoiceCompiler: Copying voice files
INFO  HMMVoiceCompiler: Compiling with Maven
maven out>Warning: JAVA_HOME environment variable is not set.
maven out>[INFO] Scanning for projects...
maven out>[ERROR] The build could not read 1 project -> [Help 1]
maven out>[ERROR] 
```  
`maven out>[ERROR]   The project de.dfki.mary:voice-20160107-ehmm-hmm/-hsmm:5.2-SNAPSHOT (/home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/`**`voice-cld.20160107-ehmm-hmm`**`/pom.xml) has 1 error`

`maven out>[ERROR]     'artifactId' with value '`**`voice-20160107-ehmm-hmm/-hsmm`**`' does not match a valid id pattern. @ line 9, column 14`
```
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
java.lang.Exception: The component HMMVoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:353)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:95)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

The voice name/ ID does not match the folder name and has a `/` in its name. That probably causes the crash. Where does the **/-hsmm** gets added to the voice name / ID? I didn't edit the templates in `marytts-builder/src/main/resources/marytts/tools/voiceimport/templates/` .

Thanks

**Comment by psibre** [comment]
Could you please paste or attach your `database.config`, and the `pom.xml` generated under the `mary/` subdirectory of your voicebuilding project?

**Comment by entenbein** [comment]
Hi,

**pom.xml:**
```
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>de.dfki.mary</groupId>
		<artifactId>marytts</artifactId>
		<version>5.2-SNAPSHOT</version>
	</parent>
	<artifactId>voice-20160107-ehmm-hmm/-hsmm</artifactId>
	<name>voice-20160107-ehmm-hmm/-hsmm</name>
	<description>A female German general voice</description>
	<licenses>
		<license>
			<name>Creative Commons License Attribution-NoDerivs 3.0 Unported</name>
			<url>http://mary.dfki.de/download/by-nd-3.0.html</url>
		</license>
	</licenses>
	<properties>
		<voicename>20160107-ehmm-hmm/-hsmm</voicename>
	</properties>
	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>marytts-common</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>marytts-runtime</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>marytts-lang-de</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-failsafe-plugin</artifactId>
				<executions>
					<execution>
						<id>integration-test</id>
						<goals>
							<goal>integration-test</goal>
						</goals>
					</execution>
					<execution>
						<id>verify</id>
						<goals>
							<goal>verify</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<argLine>-Xms256m -Xmx512m</argLine>
					<systemPropertyVariables>
						<!-- The MARY installation directory, setting to the project dir for 
							the purposes of our integration test: -->
						<mary.base>${basedir}</mary.base>
					</systemPropertyVariables>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>${project.artifactId}-${project.version}</finalName>
					<outputDirectory>${project.build.directory}</outputDirectory>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>src/main/descriptors/installable.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.gmaven</groupId>
				<artifactId>groovy-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>com.twmacinta</groupId>
						<artifactId>fast-md5</artifactId>
						<version>2.7.1</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>execute</goal>
						</goals>
						<configuration>
							<source>${project.basedir}/src/non-packaged-resources/generateComponentFile.groovy</source>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-artifacts</id>
						<phase>package</phase>
						<goals>
							<goal>attach-artifact</goal>
						</goals>
						<configuration>
							<artifacts>
								<artifact>
									<file>${project.build.directory}/${project.artifactId}-${project.version}-component.xml</file>
									<type>xml</type>
									<classifier>component</classifier>
								</artifact>
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

**database.config:**
```
# GlobalProperties:
db.allophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/allophones/
db.basenameFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/basenames.lst
db.domain general
db.estDir /home/host/marytts/lib/speech_tools/
db.gender female
db.halfphoneFeatureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/halfphonefeatures/
db.halfphoneLabDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/halfphonelab/
db.hplabExtension .hplab
db.labDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/lab/
db.labExtension .lab
db.locale de
db.maryServerHost localhost
db.maryServerPort 59125
db.marybase /home/host/marytts/marytts_at3/target/
db.marybaseversion 5.2-SNAPSHOT
db.maryxmlDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/rawmaryxml/
db.maryxmlExtension .xml
db.phoneFeatureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/phonefeatures/
db.phoneLabDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/phonelab/
db.pmDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/pm/
db.pmExtension .pm
db.promptAllophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/prompt_allophones/
db.ptcDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/ptc/
db.ptcExtension .ptc
db.rootDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/
db.samplingrate 16000
db.textDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/text/
db.textExtension .txt
db.vocalizationsDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/vocalizations/
db.voicename 20160107-ehmm-hmm/
db.wavDir /home/host/marytts/voices/cd/wav/

# Properties for module PraatPitchmarker:
PraatPitchmarker.command praat
PraatPitchmarker.maxPitch 500
PraatPitchmarker.minPitch 100
PraatPitchmarker.pmDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/pm/
PraatPitchmarker.waveDir /home/host/marytts/voices/cd/wav/

# Properties for module MCEPMaker:
MCEPMaker.mcepDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/mcep/

# Properties for module Festvox2MaryTranscripts:
Festvox2MaryTranscripts.transcriptFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/txt.done.data

# Properties for module AllophonesExtractor:
AllophonesExtractor.styleDefinitionFile 

# Properties for module EHMMLabeler:
EHMMLabeler.doAlignment true
EHMMLabeler.doTraining true
EHMMLabeler.eDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/ehmm/
EHMMLabeler.ehmmDir /home/host/marytts/lib/external/ehmm/
EHMMLabeler.nonDetEndFlag 0
EHMMLabeler.outputLabDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/lab/
EHMMLabeler.prepareFiles true
EHMMLabeler.promtallophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/prompt_allophones/
EHMMLabeler.reTrainFlag false
EHMMLabeler.startEHMMModelDir /

# Properties for module HTKLabeler:
HTKLabeler.awkbin /usr/bin/awk
HTKLabeler.htDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/htk/
HTKLabeler.htkDir /home/host/marytts/lib/htk/bin.linux/
HTKLabeler.maxNoOfIterations 150
HTKLabeler.maxshortPauseIteration 10
HTKLabeler.outputLabDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/htk/lab/
HTKLabeler.promtallophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/prompt_allophones/

# Properties for module LabelPauseDeleter:
LabelPauseDeleter.eDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/ehmm/
LabelPauseDeleter.outputLabDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/lab/
LabelPauseDeleter.pauseDurationThreshold 180

# Properties for module HalfPhoneUnitLabelComputer:
HalfPhoneUnitLabelComputer.energyBasedTransientSplitting false

# Properties for module FeatureSelection:
FeatureSelection.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/features.txt
FeatureSelection.maryServerHost localhost
FeatureSelection.maryServerPort 59125

# Properties for module PhoneUnitFeatureComputer:
PhoneUnitFeatureComputer.allophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/allophones/
PhoneUnitFeatureComputer.featureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/phonefeatures/
PhoneUnitFeatureComputer.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/features.txt
PhoneUnitFeatureComputer.maryServerHost localhost
PhoneUnitFeatureComputer.maryServerPort 59125

# Properties for module HalfPhoneUnitFeatureComputer:
HalfPhoneUnitFeatureComputer.allophonesDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/allophones/
HalfPhoneUnitFeatureComputer.featureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/halfphonefeatures/
HalfPhoneUnitFeatureComputer.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/features.txt
HalfPhoneUnitFeatureComputer.maryServerHost localhost
HalfPhoneUnitFeatureComputer.maryServerPort 59125

# Properties for module WaveTimelineMaker:
WaveTimelineMaker.waveTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_waveforms.mry

# Properties for module BasenameTimelineMaker:
BasenameTimelineMaker.timelineFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_basenames.mry

# Properties for module MCepTimelineMaker:
MCepTimelineMaker.mcepDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/mcep/
MCepTimelineMaker.mcepTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_mcep.mry

# Properties for module PhoneUnitfileWriter:
PhoneUnitfileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneUnits.mry

# Properties for module PhoneFeatureFileWriter:
PhoneFeatureFileWriter.featureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/phonefeatures/
PhoneFeatureFileWriter.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneFeatures.mry
PhoneFeatureFileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneUnits.mry
PhoneFeatureFileWriter.weightsFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneUnitFeatureDefinition.txt

# Properties for module DurationCARTTrainer:
DurationCARTTrainer.durTree /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/dur.tree
DurationCARTTrainer.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneFeatures.mry
DurationCARTTrainer.isHnmTimeline false
DurationCARTTrainer.stepwiseTraining false
DurationCARTTrainer.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneUnits.mry
DurationCARTTrainer.waveTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_waveforms.mry

# Properties for module F0CARTTrainer:
F0CARTTrainer.f0LeftTreeFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/f0.left.tree
F0CARTTrainer.f0MidTreeFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/f0.mid.tree
F0CARTTrainer.f0RightTreeFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/f0.right.tree
F0CARTTrainer.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneFeatures.mry
F0CARTTrainer.isHnmTimeline false
F0CARTTrainer.stepwiseTraining false
F0CARTTrainer.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/phoneUnits.mry
F0CARTTrainer.waveTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_waveforms.mry

# Properties for module HalfPhoneUnitfileWriter:
HalfPhoneUnitfileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry

# Properties for module HalfPhoneFeatureFileWriter:
HalfPhoneFeatureFileWriter.featureDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/halfphonefeatures/
HalfPhoneFeatureFileWriter.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures.mry
HalfPhoneFeatureFileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry
HalfPhoneFeatureFileWriter.weightsFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnitFeatureDefinition.txt

# Properties for module F0PolynomialFeatureFileWriter:
F0PolynomialFeatureFileWriter.f0FeatureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/syllableF0Polynomials.mry
F0PolynomialFeatureFileWriter.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures.mry
F0PolynomialFeatureFileWriter.interpolate true
F0PolynomialFeatureFileWriter.isHnmTimeline false
F0PolynomialFeatureFileWriter.maxPitch 500
F0PolynomialFeatureFileWriter.minPitch 100
F0PolynomialFeatureFileWriter.polynomOrder 3
F0PolynomialFeatureFileWriter.showGraph false
F0PolynomialFeatureFileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry
F0PolynomialFeatureFileWriter.waveTimeLine /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_waveforms.mry

# Properties for module AcousticFeatureFileWriter:
AcousticFeatureFileWriter.acFeatDef /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnitFeatureDefinition_ac.txt
AcousticFeatureFileWriter.acFeatureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures_ac.mry
AcousticFeatureFileWriter.contourFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/syllableF0Polynomials.mry
AcousticFeatureFileWriter.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures.mry
AcousticFeatureFileWriter.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry

# Properties for module JoinCostFileMaker:
JoinCostFileMaker.acfeatureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures_ac.mry
JoinCostFileMaker.joinCostFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/joinCostFeatures.mry
JoinCostFileMaker.mcepDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/mcep/
JoinCostFileMaker.mcepTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_mcep.mry
JoinCostFileMaker.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry
JoinCostFileMaker.weightsFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/joinCostWeights.txt

# Properties for module CARTBuilder:
CARTBuilder.acFeatureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneFeatures_ac.mry
CARTBuilder.callWagon false
CARTBuilder.cartFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/cart.mry
CARTBuilder.featureSeqFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/featureSequence.txt
CARTBuilder.maxLeafSize 10000000
CARTBuilder.mcepTimeline /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/timeline_mcep.mry
CARTBuilder.numProcesses 1
CARTBuilder.readFeatureSequence true
CARTBuilder.topLevelTreeFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/topLevel.tree
CARTBuilder.unitFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/halfphoneUnits.mry

# Properties for module HMMVoiceDataPreparation:
HMMVoiceDataPreparation.adaptScripts false
HMMVoiceDataPreparation.userRawDirectory 
HMMVoiceDataPreparation.userUttDirectory 

# Properties for module HMMVoiceConfigure:
HMMVoiceConfigure.adaptF0Ranges 'bdl 40 210 clb 130 260 jmk 50 180 rms 40 200 slt 110 280'
HMMVoiceConfigure.adaptHead b05
HMMVoiceConfigure.adaptScripts false
HMMVoiceConfigure.adaptSpkr cd
HMMVoiceConfigure.adaptSpkrMask */cd_%%%_*
HMMVoiceConfigure.adaptTrainSpkr 'bdl clb jmk rms'
HMMVoiceConfigure.adaptTransKind feat
HMMVoiceConfigure.adaptTreeKind dec
HMMVoiceConfigure.configureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/hts/configure
HMMVoiceConfigure.dataSet cd
HMMVoiceConfigure.fftLen 512
HMMVoiceConfigure.frameLen 400
HMMVoiceConfigure.frameShift 80
HMMVoiceConfigure.freqWarp 0.3
HMMVoiceConfigure.gamma 0
HMMVoiceConfigure.lf0BandWidth 1
HMMVoiceConfigure.lnGain 1
HMMVoiceConfigure.lowerF0 80
HMMVoiceConfigure.mgcBandWidth 35
HMMVoiceConfigure.mgcOrder 34
HMMVoiceConfigure.normalize 1
HMMVoiceConfigure.numIterations 5
HMMVoiceConfigure.numState 5
HMMVoiceConfigure.numTestFiles 5
HMMVoiceConfigure.questionsNum 001
HMMVoiceConfigure.sampfreq 16000
HMMVoiceConfigure.speaker cd
HMMVoiceConfigure.strBandWidth 5
HMMVoiceConfigure.strFilterFileName filters/mix_excitation_5filters_99taps_16Kz.txt
HMMVoiceConfigure.strOrder 5
HMMVoiceConfigure.upperF0 350
HMMVoiceConfigure.version 1
HMMVoiceConfigure.windowType 1

# Properties for module HMMVoiceFeatureSelection:
HMMVoiceFeatureSelection.featureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/features.txt
HMMVoiceFeatureSelection.hmmFeatureFile /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/hmmFeatures.txt

# Properties for module HMMVoiceMakeData:
HMMVoiceMakeData.adaptScripts false
HMMVoiceMakeData.featureListFile mary/hmmFeatures.txt
HMMVoiceMakeData.featureListMapFile mary/hmmFeaturesMap.txt
HMMVoiceMakeData.makeCMPMARY 1
HMMVoiceMakeData.makeLABELMARY 1
HMMVoiceMakeData.makeLF0 1
HMMVoiceMakeData.makeLIST 1
HMMVoiceMakeData.makeMGC 1
HMMVoiceMakeData.makeQUESTIONSMARY 1
HMMVoiceMakeData.makeSCP 1
HMMVoiceMakeData.makeSTR 1
HMMVoiceMakeData.questionsFile hts/data/questions/questions_qst001.hed
HMMVoiceMakeData.questionsUttFile hts/data/questions/questions_utt_qst001.hed
HMMVoiceMakeData.trickyPhonesFile mary/trickyPhones.txt

# Properties for module VoiceCompiler:
VoiceCompiler.compileDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/voice-cd.20151229-ehmm-22k/
VoiceCompiler.mavenBin /usr/local/apache-maven/bin/mvn

# Properties for module HMMVoiceCompiler:
HMMVoiceCompiler.compileDir /home/host/marytts/voices/cd/20160107-ehmm-hmm/mary/voice-cd.20160107-ehmm-hmm/
HMMVoiceCompiler.mavenBin /usr/bin/mvn


```

**Comment by psibre** [comment]
Thanks for the details!

The problem is your configuration, where your `database.config` contains the line:
> `db.voicename 20160107-ehmm-hmm/`

This is then used by the VoiceCompiler (without sanitizing) for the voice artifact ID when it generates the `pom.xml` and tries to run Maven. But of course, quoting from the [Maven docs](https://maven.apache.org/guides/mini/guide-naming-conventions.html),
> **artifactId** is the name of the jar without version. If you created it then you can choose whatever name you want with lowercase letters and no strange symbols. If it's a third party jar you have to take the name of the jar as it's distributed.
> eg. `maven`, `commons-math`

The trailing slash in your voicename counts as a "strange symbol" and needs to be removed.

**Comment by psibre** [comment]
On second thought, this could be considered a bug in [VoiceCompiler#toPackageName](../blob/c33638fc553a6f574e9c916a409b19195be7f1e8/marytts-builder/src/main/java/marytts/tools/voiceimport/VoiceCompiler.java#L397-L427)

**Comment by entenbein** [comment]
Wow, that worked like a charm. I Wasn't aware of the / in the voicename, that explains it. 

Thanks!

**Comment by psibre** [comment]
Glad it was easy to fix.
Looking at the code, this is also easy to avoid in the future. Although it turns out that it's not a bug in [VoiceCompiler#toPackageName](../blob/c33638fc553a6f574e9c916a409b19195be7f1e8/marytts-builder/src/main/java/marytts/tools/voiceimport/VoiceCompiler.java#L397-L427) (which *does* sanitize invalid characters), but the fact that that method is not used where it should be.

**Comment by psibre** [comment]
Although, having said that, it's not actually the toPackageName method we want (which returns camel case) but just a removal of invalid characters...
