### ISSUE TITLE
SIMPLEPHONEMES is broken

### ISSUE THREAD

**Issue by attacomsian** [marytts/marytts#467]
Input type: `SIMPLEPHONEMES`
Output type: `AUDIO`

Input Text
`'wEl-k@m t@ D@ 'wr=ld @v 'spitS 'sIn-T@-sIs`

```
Internal Server Error

2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.R 1 New request (input type "SIMPLEPHONEMES", output type "AUDIO", voice "cmu-slt-hsmm", effect "", audio "WAVE")
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.IO Setting text input: 'wEl-k@m t@ D@ 'wr=ld @v 'spitS 'sIn-T@-sIs

2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.server Read: 'wEl-k@m t@ D@ 'wr=ld @v 'spitS 'sIn-T@-sIs

2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.R 1 Now converting the following input data from SIMPLEPHONEMES to AUDIO:
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.IO Writing Text output:
'wEl-k@m t@ D@ 'wr=ld @v 'spitS 'sIn-T@-sIs

2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.R 1 Determining which modules to use
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.ModuleRegistry Module SimplePhoneme2AP converts SIMPLEPHONEMES into ACOUSTPARAMS (locale en_US, voice cmu-slt-hsmm)
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.ModuleRegistry Module Synthesis converts ACOUSTPARAMS into AUDIO (locale en_US, voice cmu-slt-hsmm)
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.ModuleRegistry found path through modules
2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.R 1 Handling request using the following modules:
2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.R 1 - SimplePhoneme2AP (marytts.modules.SimplePhoneme2AP)
2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.R 1 - Synthesis (marytts.modules.Synthesis)
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.R 1 Handing the following data to the next module:
2016-02-01 14:46:48,901 [I/O dispatcher 4] DEBUG marytts.IO Writing Text output:
'wEl-k@m t@ D@ 'wr=ld @v 'spitS 'sIn-T@-sIs

2016-02-01 14:46:48,901 [I/O dispatcher 4] INFO  marytts.R 1 Next module: SimplePhoneme2AP
2016-02-01 14:46:48,903 [I/O dispatcher 4] DEBUG marytts.R 1 Handing the following data to the next module:
2016-02-01 14:46:48,907 [I/O dispatcher 4] DEBUG marytts.IO <?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<voice name="cmu-slt-hsmm">
<t accent="*" ph="'wEl-k@m">
<syllable accent="*" ph="'wEl"/>
<ph d="70" end="70" p="w"/>
<ph d="150" end="220" p="E"/>
<ph d="70" end="290" p="l"/>
<syllable ph="k@m"/>
<ph d="70" end="360" p="k"/>
<ph d="100" end="460" p="@"/>
<ph d="70" end="530" p="m"/>
</t>
<t ph="t@">
<syllable ph="t@"/>
<ph d="70" end="600" p="t"/>
<ph d="100" end="700" p="@"/>
</t>
<t ph="D@">
<syllable ph="D@"/>
<ph d="70" end="770" p="D"/>
<ph d="100" end="870" p="@"/>
</t>
<t accent="*" ph="'wr=ld">
<syllable accent="*" ph="'wr=ld"/>
<ph d="70" end="940" p="w"/>
<ph d="150" end="1090" p="r="/>
<ph d="70" end="1160" p="l"/>
<ph d="70" end="1230" p="d"/>
</t>
<t ph="@v">
<syllable ph="@v"/>
<ph d="100" end="1330" p="@"/>
<ph d="70" end="1400" p="v"/>
</t>
<t accent="*" ph="'spitS">
<syllable accent="*" ph="'spitS"/>
<ph d="70" end="1470" p="s"/>
<ph d="70" end="1540" p="p"/>
<ph d="150" end="1690" p="i"/>
<ph d="70" end="1760" p="tS"/>
</t>
<t accent="*" ph="'sIn-T@-sIs">
<syllable accent="*" ph="'sIn"/>
<ph d="70" end="1830" p="s"/>
<ph d="150" end="1980" p="I"/>
<ph d="70" end="2050" p="n"/>
<syllable ph="T@"/>
<ph d="70" end="2120" p="T"/>
<ph d="100" end="2220" p="@"/>
<syllable ph="sIs"/>
<ph d="70" end="2290" p="s"/>
<ph d="100" end="2390" p="I"/>
<ph d="70" end="2460" p="s"/>
</t>
<boundary bi="4" duration="400"/>
</voice>
</maryxml>

2016-02-01 14:46:48,912 [I/O dispatcher 4] INFO  marytts.R 1 Next module: Synthesis
2016-02-01 14:46:48,912 [I/O dispatcher 4] INFO  marytts.HMMSynthesizer Synthesizing one sentence.
2016-02-01 14:46:48,913 [I/O dispatcher 4] ERROR marytts.server Processing failed.
java.lang.AssertionError: Unexpected tag name: expected syllable, got t
	at marytts.features.MaryGenericFeatureProcessors$SyllableNavigator.getElement(MaryGenericFeatureProcessors.java:277)
	at marytts.features.MaryGenericFeatureProcessors$Accented.process(MaryGenericFeatureProcessors.java:745)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:140)
	at marytts.modules.TargetFeatureLister.getListTargetFeatures(TargetFeatureLister.java:126)
	at marytts.modules.synthesis.HMMSynthesizer.synthesize(HMMSynthesizer.java:268)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:527)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:252)
	at marytts.modules.Synthesis.process(Synthesis.java:222)
	at marytts.server.Request.processOneChunk(Request.java:566)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:299)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
2016-02-01 14:46:48,914 [I/O dispatcher 4] DEBUG marytts.http Returning HTTP status 500: Processing failed.
java.lang.AssertionError: Unexpected tag name: expected syllable, got t
	at marytts.features.MaryGenericFeatureProcessors$SyllableNavigator.getElement(MaryGenericFeatureProcessors.java:277)
	at marytts.features.MaryGenericFeatureProcessors$Accented.process(MaryGenericFeatureProcessors.java:745)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:140)
	at marytts.modules.TargetFeatureLister.getListTargetFeatures(TargetFeatureLister.java:126)
	at marytts.modules.synthesis.HMMSynthesizer.synthesize(HMMSynthesizer.java:268)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:527)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:252)
	at marytts.modules.Synthesis.process(Synthesis.java:222)
	at marytts.server.Request.processOneChunk(Request.java:566)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:299)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by psibre** [comment]
It looks like the generated XML is malformed; for example:
```xml
<t accent="*" ph="'wEl-k@m">
  <syllable accent="*" ph="'wEl"/>
  <ph d="70" end="70" p="w"/>
  <ph d="150" end="220" p="E"/>
  <ph d="70" end="290" p="l"/>
  <syllable ph="k@m"/>
  <ph d="70" end="360" p="k"/>
  <ph d="100" end="460" p="@"/>
  <ph d="70" end="530" p="m"/>
</t>
```
The `ph` elements need to be child nodes of the `syllable`, but somehow they're all siblings within the `t` element. This XML fragment should look like this:
```xml
<?xml version="1.0"?>
<t accent="*" ph="'wEl-k@m">
  <syllable accent="*" ph="'wEl">
    <ph d="70" end="70" p="w"/>
    <ph d="150" end="220" p="E"/>
    <ph d="70" end="290" p="l"/>
  </syllable>
  <syllable ph="k@m">
    <ph d="70" end="360" p="k"/>
    <ph d="100" end="460" p="@"/>
    <ph d="70" end="530" p="m"/>
  </syllable>
</t>
```

**Comment by psibre** [comment]
OK, I didn't even realize there *was* a SimplePhonemes2AP module... and apparently it's been [broken](../blob/dfa26816a90bd3296df89820f2804a9213fd205c/marytts-runtime/src/main/java/marytts/modules/SimplePhoneme2AP.java#L126) since the [dawn of time](../commit/723a1aed58ab7f0a381c57ef7b6701ee4a892004).

**Comment by psibre** [comment]
#280 depends on this
