### ISSUE TITLE
rules based used in isolation

### ISSUE THREAD

**Issue by kingjr** [marytts/marytts#471]
I apologize for opening multiple issues recently, but they seem partially distinct.

I encounter an error when I synthesize a unique phoneme that isn't in the lexicon.

For example, `Qo` (but not `Qo.` !) gives the error below for `dfki-prudence en_GB female unitselection general` but not for all voices.

```
Processing failed.

java.lang.Exception: Module Synthesis: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:551)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:389)
	at marytts.server.Request.process(Request.java:336)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:272)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:98)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:144)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.w3c.dom.DOMException: NOT_SUPPORTED_ERR: Der angeforderte Typ des Objekts oder Vorgangs wird nicht von der Implementierung unterstützt. 
	at com.sun.org.apache.xerces.internal.dom.DocumentImpl.createTreeWalker(DocumentImpl.java:269)
	at marytts.util.dom.DomUtils.createTreeWalker(DomUtils.java:848)
	at marytts.features.MaryGenericFeatureProcessors$UnitLogF0.process(MaryGenericFeatureProcessors.java:2580)
	at marytts.features.MaryGenericFeatureProcessors$UnitLogF0.process(MaryGenericFeatureProcessors.java:2514)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:143)
	at marytts.unitselection.select.FFRTargetCostFunction.computeTargetFeatures(FFRTargetCostFunction.java:298)
	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.computeTargetFeatures(DiphoneFFRTargetCostFunction.java:133)
	at marytts.unitselection.select.UnitSelector.selectUnits(UnitSelector.java:110)
	at marytts.unitselection.UnitSelectionSynthesizer.synthesize(UnitSelectionSynthesizer.java:169)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:501)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:263)
	at marytts.modules.Synthesis.process(Synthesis.java:232)
	at marytts.server.Request.processOneChunk(Request.java:549)
	... 19 more
```

**Comment by Rootex** [comment]
Hello,
Please can you elaborate more on information to recreate this bug, it seems to be ok on my end.
I want to know exactly what your did so i can't recreate it and then help with a fix.

Thanks.

**Comment by kingjr** [comment]
![marytts](https://cloud.githubusercontent.com/assets/4881164/12749579/9a496fea-c97f-11e5-9aa3-6ead47c948b7.png)

Is this sufficient?

**Comment by Rootex** [comment]
@kingjr Thanks, it is. I will get back to you as soon as i can.

**Comment by psibre** [comment]
Aha, the error is thrown by TargetFeatureComputer#computeFeatureVector, which doesn't catch any exceptions, and the root of the problem is that UnitLogF0#process requires a `phrase` ancester in the MaryXML, which is not created for some bizarre reason.

**Comment by attacomsian** [comment]
@psibre can you please add some further details into this issue? I am trying to figure it out where exactly I should create `phrase` ancestor.

**Comment by attacomsian** [comment]
Not able to produce in 5.2-beta3.
