### ISSUE TITLE
JPhonemiser_de: Problem processing the data -> Allophone `-' could not be found in AllophoneSet `sampa'

### ISSUE THREAD

**Issue by qwertologe** [marytts/marytts#481]
I stumbled over "Bestätigung" (german). I did some tests and there are some other letters which produce the problem, too: 

- Bestä
- Besta
- Besti
- Besto
- Bestö
- Bestr
- Bestu
- Bestü
- Besty

A friend sent me this problem document. I think, he uses 5.1. I tested with 5.1.2.
 
```
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module JPhonemiser_de: Problem processing the data.              
  at marytts.server.Request.processOneChunk(Request.java:549)
  at marytts.server.Request.processOrLookupOneChunk(Request.java:385)
  at marytts.server.Request.process(Request.java:327)
  at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
  at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
  at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
  at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
  at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
  at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
  at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
  at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
  at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
  at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
  at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
  at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
  at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Allophone `-' could not be found in AllophoneSet `sampa' (Locale: de)
  at marytts.modules.phonemiser.AllophoneSet.getAllophone(AllophoneSet.java:224)
  at marytts.modules.phonemiser.Syllabifier.correctStressSymbol(Syllabifier.java:297)
  at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:252)
  at marytts.modules.phonemiser.Syllabifier.syllabify(Syllabifier.java:52)
  at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:166)
  at marytts.language.de.JPhonemiser.phonemise(JPhonemiser.java:349)
  at marytts.language.de.JPhonemiser.process(JPhonemiser.java:232)
  at marytts.server.Request.processOneChunk(Request.java:547)
  ... 19 more
</pre></body></html

**Comment by psibre** [comment]
I'm pretty sure this has been fixed for a while. Could you please test with v5.2beta2?

**Comment by qwertologe** [comment]
hmm until now i downloaded the voices with the component-installer. The bin-folder is gone...
so i tried it in the new folder but this does not work. What do i miss?
```
~/marytts-5.2beta2$ LANG= ./marytts-assembly/assembly-runtime/src/runtime/bin/marytts-component-installer
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Error: Could not find or load main class marytts.tools.install.InstallerGUI

**Comment by psibre** [comment]
Wait... are you trying to run it from the raw source code? Without building it first?
The beta releases don't have full packages attached, so you need to follow the instructions in the README.

**Comment by qwertologe** [comment]
ah - thanks - i just searched and started - sorry.
now in beta2 this works fine... have look at the next issue :-)
