### ISSUE TITLE
New Language Phonemes Transcription help(HINDI LAnguage)

### ISSUE THREAD

**Issue by BibekBazaz** [marytts/marytts#502]
Hello Everyone, I am using  marytts to build a Hindi Text to speech converter. I have prepared a Hindi phone set that i have attached along with this issue and also a list of 300 hindi words that i tried to train manually. However only a few of them get trained and for the rest it shows : 

java.lang.IllegalArgumentException: Cannot syllabify empty phone string

i need immediate help with this problem. I will be really grateful if someone can please look into it and tell me where I am making the mistakes.

THANK YOU IN ADVANCE.
[allophones.hi_IN.txt](https://github.com/marytts/marytts/files/175416/allophones.hi_IN.txt)
[hi_in_300.txt](https://github.com/marytts/marytts/files/175417/hi_in_300.txt)

**Comment by entenbein** [comment]
Could you provide the correspondent part from the log file?

**Comment by BibekBazaz** [comment]
prev: Serif
next: Serif
alignment ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
alignment completed.
training ... 
      Training decision tree for: ं
      Training decision tree for: े
      Training decision tree for: त
      Training decision tree for: थ
      Training decision tree for: द
      Training decision tree for: ु
      Training decision tree for: न
      Training decision tree for: ए
      Training decision tree for: म
      Training decision tree for: ै
      Training decision tree for: य
      Training decision tree for: ल
      Training decision tree for: ऐ
      Training decision tree for: व
      Training decision tree for: ख
      Training decision tree for: क
      Training decision tree for: श
      Training decision tree for: ह
      Training decision tree for: स
      Training decision tree for: ि
      Training decision tree for: null
      Training decision tree for: ज
      Training decision tree for: ा
training completed.
java.lang.IllegalArgumentException: Cannot syllabify empty phone string
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:479)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:176)
	at marytts.tools.transcription.TranscriptionTable.trainPredict(TranscriptionTable.java:221)
	at marytts.tools.transcription.TranscriptionGUI.trainPredictActionPerformed(TranscriptionGUI.java:816)
	at marytts.tools.transcription.TranscriptionGUI.access$8(TranscriptionGUI.java:810)
	at marytts.tools.transcription.TranscriptionGUI$8.actionPerformed(TranscriptionGUI.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by BibekBazaz** [comment]
this is the complete log file. i am attaching the phoneset and words that i have used for training here.
[allophones.hi_IN.txt](https://github.com/marytts/marytts/files/176539/allophones.hi_IN.txt)
[Uploading hi_in_300.txt…]()

**Comment by entenbein** [comment]
You should start in `marytts-builder/src/main/java/marytts/tools/newlanguage/LTSTrainer.java` and try to output the lexicon entry which is currently processed. The word which, probably, has a character that is not allowed will be the one after the entry which is displayed last (because after the last entry that is processed the whole thing crashes). Did you check for unsupported characters? They might even be *invisible*.
