### ISSUE TITLE
Can we use an other classloader ?

### ISSUE THREAD

**Issue by Kawrantin** [marytts/marytts#524]
Hi, 

I have a problem with the classloader while running MaryTTS.  It can't found the jar files to init MaryTTS. 

The exception come from : 

``` java
public class LocalMaryInterface implements MaryInterface {

private MaryDataType inputType;
.....
private boolean isStreaming;

public LocalMaryInterface() throws MaryConfigurationException {
        try {
            MaryRuntimeUtils.ensureMaryStarted();
        } catch (Exception e) {
            throw new MaryConfigurationException("Cannot start MARY server", e);
        }
        init();
    }
```

Is it possible to use my own classloader instead of the default MaryTTS's classloader ?

**Comment by seblemaguer** [comment]
Before anything else, have you checked that your jar is in the classpath ?

**Comment by Kawrantin** [comment]
Yes they are ! 

I load MaryTTS with a classloader, and ServiceLoader (from MaryConfig) should use my classloader insted of the default classloader. Is it possible ?

And are there other places where there would be this classloader problem ?

Thanks,

**Comment by Munzey** [comment]
Can you provide a stack trace? Similar to what @seblemaguer has suggested, have you checked that the Mary base class path is set correctly?

**Comment by Kawrantin** [comment]
I printed all the counts and the main config is null, this is why I get the NullPointerException.
The default classloader load MaryTTS, insted of my classloader..

`Could not initialize MaryTTS interface: Cannot start MARY server
--> MaryConfig.countVoiceConfigs()    = 0
--> MaryConfig.countLanguageConfigs() = 0
--> MaryConfig.countConfigs()         = 0
--> MaryConfig.getMainConfig()        = null
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at fr.horoquartz.tts.MaryTTS.startEngine(MaryTTS.java:46)
	at fr.horoquartz.abcx.tts.TTSServlet.doGet(TTSServlet.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fr.horoquartz.abcx.plugs.PlugsServlet.doGet(PlugsServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.hqarchivage.HQArchivageFilter.doFilter(HQArchivageFilter.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.ewox.servlet.GzipFilter.doFilter(GzipFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.abcx.util.JdbcResourceFilter.doFilter(JdbcResourceFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.abcx.util.XSSFilter.doFilter(XSSFilter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:69)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 42 more
Could not initialize MaryTTS interface: Cannot start MARY server
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at fr.horoquartz.tts.MaryTTS.startEngine(MaryTTS.java:46)
	at fr.horoquartz.abcx.tts.TTSServlet.doGet(TTSServlet.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fr.horoquartz.abcx.plugs.PlugsServlet.doGet(PlugsServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.hqarchivage.HQArchivageFilter.doFilter(HQArchivageFilter.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.ewox.servlet.GzipFilter.doFilter(GzipFilter.java:38)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.abcx.util.JdbcResourceFilter.doFilter(JdbcResourceFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at fr.horoquartz.abcx.util.XSSFilter.doFilter(XSSFilter.java:27)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:69)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 42 more`

**Comment by seblemaguer** [comment]
Ok so you are already defining a new classloader ? Why do you need it ? How is it implemented ?

**Comment by Kawrantin** [comment]
My tomcat starts with a minimum of jar files (for quick start !)
When I'm requesting for a specific servlet, I load all jars for MaryTTS.
It's just to get a lightweight loading of Tomcat (I've tons of jar files to load...).

Then I use a specific classloader depending on the Thread context for the requested servlet (`Thread.currentThread().getContextClassLoader()`).
In MaryTTS, `MaryConfig` class loads configurations from jars in the default classloader that doesn't contain MaryTTS jars.
I think I need to give MaryTTS my own classloader to use it in `ServiceLoader` in `MaryConfig` class (and maybe elsewhere ?)

**Comment by plukanek** [comment]
Same problem here.

public abstract class MaryConfig {
private static final ServiceLoader<MaryConfig> configLoader = ServiceLoader.load(MaryConfig.class);
....
}
Is it possible to arrange it that **load(MaryConfig.class, ownClassLoader)** can be used

**Comment by ZGorlock** [comment]
I have been having the exact same problem, I am loading the class with a custom class loader and getting a NullPointerException when trying to intialize the configLoader.

Has anyone come up with a solution for this yet?
