### ISSUE TITLE
FeatureMaker exception

### ISSUE THREAD

**Issue by buhar** [marytts/marytts#550]
Hi,
I am in the 5th stage of building a new language support for Albanian.
I'm getting this exception when I run the feature program.

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

FeatureMaker parameters:
  -locale sq
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=sq
Mysql connection created successfully.
    TABLE = "sq_dbselection" does not exist, it will be created.Checking if sq_dbselection already exist.
TABLE = sq_dbselection succesfully created.
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from sq_cleanText
Number of unprocessed clean_text records to process --> [4135]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:14_06_2016_06:59:10

Exception in thread "main" java.lang.NullPointerException
    at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:202)
    at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:231)
    at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:170)
```

**Comment by attacomsian** [comment]
Can you please share the full error log? It is uncleared what happened exactly from what you shared.

**Comment by Nandutu** [comment]
Hello, I also have the same error like above, here is my log. However i edited my local and it affected the name of the tables i had created earlier. Here are my logs.
I am on step 5. Run feature maker with the minimal NLP components using https://github.com/marytts/marytts/wiki/New-Language-Support
1. Running future maker
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_featuremaker.sh wkdb.conf
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

FeatureMaker parameters:
  -locale lg
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
    TABLE = "lg_dbselection" does not exist, it will be created.Checking if lg_dbselection already exist.
TABLE = lg_dbselection succesfully created.
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from lg_cleanText
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'wiki.lg_cleanText' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2619)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2569)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1510)
	at marytts.tools.dbselection.DBHandler.queryTable(DBHandler.java:1777)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:887)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7139)
	at marytts.tools.dbselection.DBHandler.queryTable(DBHandler.java:1783)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:887)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:888)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_cleaning_up.sh wkdb.conf
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

WikipediaMarkupCleaner parameters:
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -listFile wikilist.txt
  -minPage 10000
  -minText 1000
  -maxText 15000

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
    TABLE = "lg_cleanText" does not exist, it will be created.
Mysql connection closed.
File already procesed: xml_splits/page1.xml
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_featuremaker.sh wkdb.conf
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

FeatureMaker parameters:
  -locale lg
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
    TABLE = "lg_dbselection" already exists, should it be deleted (y/n)?n
    ADDING sentences TO EXISTING dbselection TABLE "lg_dbselection" (y/n)?y
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from lg_cleanText
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'wiki.lg_cleanText' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2619)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2569)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1510)
	at marytts.tools.dbselection.DBHandler.queryTable(DBHandler.java:1777)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:887)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:794)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:7139)
	at marytts.tools.dbselection.DBHandler.queryTable(DBHandler.java:1783)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:887)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at marytts.tools.dbselection.DBHandler.getUnprocessedTextIds(DBHandler.java:888)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:152)
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_create_database.sh wkdb.conf
Please insert your mysql root password below.
Enter password: 
ERROR 1007 (HY000) at line 1: Can't create database 'wiki'; database exists
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ ./wkdb_featuremaker.sh wkdb.conf
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

FeatureMaker parameters:
  -locale lg
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=lg
Mysql connection created successfully.
    TABLE = "lg_dbselection" already exists, should it be deleted (y/n)?n
    ADDING sentences TO EXISTING dbselection TABLE "lg_dbselection" (y/n)?y
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from lg_cleanText
Number of unprocessed clean_text records to process --> [30]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:04_07_2016_22:05:48

Exception in thread "main" java.lang.NullPointerException
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:202)
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:231)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:170)
irene@irene-HP-650-Notebook-PC:~/TTS/mary/marytts/target/marytts-builder-5.2-SNAPSHOT/bin$ 

2. The prompt i used to change my database tables.
 irene@irene-HP-650-Notebook-PC:~$ mysql -u root -p wiki
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 40
Server version: 5.5.49-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> lug_cleanText
    -> ^CCtrl-C -- exit!
Aborted
irene@irene-HP-650-Notebook-PC:~$ mysql -u root -p wiki
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 41
Server version: 5.5.49-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> desc lug_cleanText;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| cleanText | mediumblob       | NO   |     | NULL    |                |
| processed | tinyint(1)       | YES  |     | NULL    |                |
| page_id   | int(10) unsigned | NO   |     | NULL    |                |
| text_id   | int(10) unsigned | NO   |     | NULL    |                |
+-----------+------------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

mysql> desc lg_cleanText;
ERROR 1146 (42S02): Table 'wiki.lg_cleanText' doesn't exist
mysql> RENAME TABLE lug_cleanText TO lg_cleanText
    -> RENAME TABLE lug_cleanText TO lg_cleanText;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RENAME TABLE lug_cleanText TO lg_cleanText' at line 2
mysql> RENAME TABLE lug_cleanText TO lg_cleanText;
Query OK, 0 rows affected (0.12 sec)

mysql> desc lug_cleanText;
ERROR 1146 (42S02): Table 'wiki.lug_cleanText' doesn't exist
mysql> desc lg_cleanText;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| cleanText | mediumblob       | NO   |     | NULL    |                |
| processed | tinyint(1)       | YES  |     | NULL    |                |
| page_id   | int(10) unsigned | NO   |     | NULL    |                |
| text_id   | int(10) unsigned | NO   |     | NULL    |                |
+-----------+------------------+------+-----+---------+----------------+
5 rows in set (0.01 sec)

mysql> desc en_US_wordList;
ERROR 1146 (42S02): Table 'wiki.en_US_wordList' doesn't exist
mysql> desc lug_wordList;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(11)          | NO   | PRI | NULL    | auto_increment |
| word      | tinyblob         | NO   |     | NULL    |                |
| frequency | int(10) unsigned | NO   |     | NULL    |                |
+-----------+------------------+------+-----+---------+----------------+
3 rows in set (0.00 sec)

mysql> RENAME TABLE lug_wordList TO lg_wordList;
Query OK, 0 rows affected (0.07 sec)

mysql> desc lug_wordList;
ERROR 1146 (42S02): Table 'wiki.lug_wordList' doesn't exist
mysql> desc lg_wordList;
+-----------+------------------+------+-----+---------+----------------+
| Field     | Type             | Null | Key | Default | Extra          |
+-----------+------------------+------+-----+---------+----------------+
| id        | int(11)          | NO   | PRI | NULL    | auto_increment |
| word      | tinyblob         | NO   |     | NULL    |                |
| frequency | int(10) unsigned | NO   |     | NULL    |                |
+-----------+------------------+------+-----+---------+----------------+
3 rows in set (0.01 sec)

mysql>

**Comment by BaimAT** [comment]
I encounter similar problem but found a solution. referring [here](https://github.com/marytts/marytts/issues/84) by @arpitgoyal2008 .
1. go to `/marytts-master/marytts-assembly/assembly-builder/src/builder/bin`
2. edit the file `wkdb_featuremaker.sh` as follow:

In line 
`java -showversion -ea -cp "$MARY_BASE/lib/*" marytts.tools.dbselection.FeatureMaker` change `marytts.tools.dbselection.FeatureMaker` to `marytts.tools.dbselection.FeatureMakerMaryServer'

3. cd to marytts-master
4. mvn install (not sure if this is necessary)
5. run marytts-server
6. wkdb_featuremaker.sh wkdb.conf

note: my work is still unfinished, so I'm not sure whether changing this will affect any other part of marytts.
