### ISSUE TITLE
HMMModel generates malformed XML duration attributes

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#555]
The input text "Welcome!" with the default voice-cmu-slt-hsmm generates the following `ACOUSTPARAMS`:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<phrase>
<t accent="H*" g2p_method="lexicon" ph="' w E l - k @ m" pos="UH">
Welcome
<syllable accent="H*" ph="w E l" stress="1">
<ph d="60" end="0.06" f0="(8,225)(16,215)(25,220)(33,223)(41,210)(50,189)(58,185)(66,183)(75,182)(83,181)(91,180)(100,178)" p="w"/>
<ph d="65" end="0.125" f0="(7,176)(15,174)(23,172)(30,170)(38,170)(46,169)(53,168)(61,168)(69,167)(76,166)(84,165)(92,164)(100,163)" p="E"/>
<ph d="65" end="0.19" f0="(7,163)(15,162)(23,161)(30,161)(38,160)(46,160)(53,159)(61,159)(69,159)(76,159)(84,157)(92,155)(100,150)" p="l"/>
</syllable>
<syllable ph="k @ m">
<ph d="100" end="0.29" p="k"/>
<ph d="95" end="0.385" f0="(5,187)(10,180)(15,171)(21,171)(26,170)(31,169)(36,168)(42,167)(47,166)(52,165)(57,164)(63,163)(68,162)(73,161)(78,160)(84,159)(89,157)(94,156)(100,156)" p="@"/>
<ph d="125" end="0.51" f0="(4,156)(8,162)(12,163)(16,164)(20,166)(24,167)(28,167)(32,169)(36,170)(40,171)(44,173)(48,174)(52,176)(56,178)(60,179)(64,180)(68,180)(72,180)(76,179)(80,176)(84,169)(88,164)(92,161)(96,158)(100,157)" p="m"/>
</syllable>
</t>
<t pos=".">
!
</t>
<boundary breakindex="5" duration="400" tone="L-L%"/>
</phrase>
</s>
</p>
</maryxml>
```
Using the same XML string as the input for `RAWMARYXML` and setting the output type to `REALISED_ACOUSTPARAMS` throws an exception!
```
java.lang.Exception: Module AcousticModeller: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "60 0.07499999552965164"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
	at java.lang.Float.parseFloat(Float.java:452)
	at marytts.modules.AcousticModeller.hackSegmentDurations(AcousticModeller.java:277)
	at marytts.modules.AcousticModeller.process(AcousticModeller.java:195)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more
```

**Comment by seblemaguer** [comment]
are you sure the input xml is RAWMARYXML? or is it ACOUSTPARAMS ?

**Comment by psibre** [comment]
@seblemaguer definitely `RAWMARYXML`. If the input type is `ACOUSTPARAMS`, then there is no error.

**Comment by seblemaguer** [comment]
for info, we have duplicated code between `HMMModel` and `HTSEngine`. That explains why modifying `HMMModel` doesn't impact the audio part

**Comment by psibre** [comment]
@seblemaguer thanks for investigating! 👍

**Comment by psibre** [comment]
@seblemaguer using your fixes in `upstream/fix-555`, I can confirm that the errors are fixed. However, certain other things are going wrong.

`acoust_before.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<phrase>
<t accent="H*" g2p_method="lexicon" ph="' w E l - k @ m" pos="UH">
Welcome
<syllable accent="H*" ph="w E l" stress="1">
<ph d="60" end="0.06" f0="(8,225)(16,215)(25,220)(33,223)(41,210)(50,189)(58,185)(66,183)(75,182)(83,181)(91,180)(100,178)" p="w"/>
<ph d="65" end="0.125" f0="(7,176)(15,174)(23,172)(30,170)(38,170)(46,169)(53,168)(61,168)(69,167)(76,166)(84,165)(92,164)(100,163)" p="E"/>
<ph d="65" end="0.19" f0="(7,163)(15,162)(23,161)(30,161)(38,160)(46,160)(53,159)(61,159)(69,159)(76,159)(84,157)(92,155)(100,150)" p="l"/>
</syllable>
<syllable ph="k @ m">
<ph d="100" end="0.29" p="k"/>
<ph d="95" end="0.385" f0="(5,187)(10,180)(15,171)(21,171)(26,170)(31,169)(36,168)(42,167)(47,166)(52,165)(57,164)(63,163)(68,162)(73,161)(78,160)(84,159)(89,157)(94,156)(100,156)" p="@"/>
<ph d="125" end="0.51" f0="(4,156)(8,162)(12,163)(16,164)(20,166)(24,167)(28,167)(32,169)(36,170)(40,171)(44,173)(48,174)(52,176)(56,178)(60,179)(64,180)(68,180)(72,180)(76,179)(80,176)(84,169)(88,164)(92,161)(96,158)(100,157)" p="m"/>
</syllable>
</t>
<t pos=".">
!
</t>
<boundary breakindex="5" duration="400" tone="L-L%"/>
</phrase>
</s>
</p>
</maryxml>
```
`acoust_after.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<phrase>
<t accent="H*" g2p_method="lexicon" ph="' w E l - k @ m" pos="UH">
Welcome
<syllable accent="H*" ph="w E l" stress="1">
<ph d="60" end="600.0" f0="(8,225)(16,215)(25,220)(33,223)(41,210)(50,189)(58,185)(66,183)(75,182)(83,181)(91,180)(100,178)" p="w"/>
<ph d="65" end="1250.0" f0="(7,176)(15,174)(23,172)(30,170)(38,170)(46,169)(53,168)(61,168)(69,167)(76,166)(84,165)(92,164)(100,163)" p="E"/>
<ph d="65" end="1900.0" f0="(7,163)(15,162)(23,161)(30,161)(38,160)(46,160)(53,159)(61,159)(69,159)(76,159)(84,157)(92,155)(100,150)" p="l"/>
</syllable>
<syllable ph="k @ m">
<ph d="100" end="2900.0" p="k"/>
<ph d="95" end="3850.0" f0="(5,187)(10,180)(15,171)(21,171)(26,170)(31,169)(36,168)(42,167)(47,166)(52,165)(57,164)(63,163)(68,162)(73,161)(78,160)(84,159)(89,157)(94,156)(100,156)" p="@"/>
<ph d="125" end="5100.0" f0="(4,156)(8,162)(12,163)(16,164)(20,166)(24,167)(28,167)(32,169)(36,170)(40,171)(44,173)(48,174)(52,176)(56,178)(60,179)(64,180)(68,180)(72,180)(76,179)(80,176)(84,169)(88,164)(92,161)(96,158)(100,157)" p="m"/>
</syllable>
</t>
<t pos=".">
!
</t>
<boundary breakindex="5" duration="400" tone="L-L%"/>
</phrase>
</s>
</p>
</maryxml>
```
`real_acoust_after.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?><maryxml xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.5" xml:lang="en-US">
<p>
<s>
<prosody pitch="+5%" range="+20%">
<phrase>
<prosody pitch="-5%" range="-20%">
<phrase>
<t accent="H*" g2p_method="lexicon" ph="' w E l - k @ m" pos="UH">
Welcome
<syllable accent="H*" ph="w E l" stress="1">
<ph d="60" end="600.0" f0="(8,177)(16,177)(25,177)(33,177)(41,177)(50,177)(58,177)(66,177)(75,177)(83,177)(91,177)(100,177)" p="w"/>
<ph d="65" end="1250.0" f0="(7,162)(15,162)(23,162)(30,162)(38,162)(46,162)(53,162)(61,162)(69,162)(76,162)(84,162)(92,162)(100,162)" p="E"/>
<ph d="65" end="1900.0" f0="(7,148)(15,148)(23,148)(30,148)(38,148)(46,148)(53,148)(61,148)(69,148)(76,148)(84,148)(92,148)(100,148)" p="l"/>
</syllable>
<syllable ph="k @ m">
<ph d="100" end="2900.0" f0="" p="k"/>
<ph d="95" end="3850.0" f0="(5,154)(10,154)(15,154)(21,154)(26,154)(31,154)(36,154)(42,154)(47,154)(52,154)(57,154)(63,154)(68,154)(73,154)(78,154)(84,154)(89,154)(94,154)(100,154)" p="@"/>
<ph d="125" end="5100.0" f0="(4,156)(8,156)(12,156)(16,156)(20,156)(24,156)(28,156)(32,156)(36,156)(40,156)(44,156)(48,156)(52,156)(56,156)(60,156)(64,156)(68,156)(72,156)(76,156)(80,156)(84,156)(88,156)(92,156)(96,156)(100,156)" p="m"/>
</syllable>
</t>
<t pos=".">
!
</t>
<boundary breakindex="5" duration="185" tone="L-L%"/>
</phrase>
</prosody>
</phrase>
</prosody>
</s>
</p>
</maryxml>
```

A couple of things:
- the `end` attributes are multiplied by a factor of 1000 when they shouldn't be
- the `<boundary>` element's `duration` attribute is changed when it shouldn't be
- the `<phrase>` is wrapped into several useless `<prosody>` elements
- the frequencies in the `f0` attributes are flattened to a single, repeated value for each `<ph>`
- unvoiced `<ph>` segments should probably not get an empty `f0` attribute

A few of these might be a side-effect of the fix, but it's more than likely that the others are prior bugs that we couldn't even expose without the fix.
