### ISSUE TITLE
New language support issues: Incorrect string value when run wkdb_cleaning_up.sh

### ISSUE THREAD

**Issue by jetaudio** [marytts/marytts#583]
I ran `wkdb_cleaning_up.sh wkdb.conf` and got this error 
Processing xml file:xml_splits/page15.xml

Mysql driver loaded, set locale=vi_VI
Creating connection to DB server...
Mysql connection created successfully.
Creating and loading TABLES: page, text and revision. (The loading can take a while...)

Mysql driver loaded, set locale=vi_VI
Using mwdumper to convert xml file into sql source file and loading text, page and revision tables into the DB.
Creating connection to DB server...
Mysql connection created successfully.
Creating empty wikipedia tables: checking if tables text, page and revision already exist.

 **_To continue please check if the table "text" is used by another user/process.**_ 
    Tables "text", "page" and "revision" are temporary tables used by mwdumper to extract wikipedia pages. 
    Just one user/process can use these tables at the same time in the same DataBase, please use other DataBase if possible.
    If the tables are not in use by any other user/process please use the option for deleting.

```
TABLE = "text" already exists deleting (y/n)?y
```

 **_To continue please check if the table "revision" is used by another user/process.**_ 
    Tables "text", "page" and "revision" are temporary tables used by mwdumper to extract wikipedia pages. 
    Just one user/process can use these tables at the same time in the same DataBase, please use other DataBase if possible.
    If the tables are not in use by any other user/process please use the option for deleting.

```
TABLE = "revision" already exists deleting (y/n)?y
```

  Creating table: text
  Creating table: page
  Creating table: revision
Exception in thread "main" java.io.IOException: java.sql.SQLException: Incorrect string value: '\xF0\xA0\x84\xA9\xE5\xA9...' for column 'page_title' at row 337
    at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
    at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:257)
    at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1088)
    at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:444)
Caused by: org.xml.sax.SAXException: java.sql.SQLException: Incorrect string value: '\xF0\xA0\x84\xA9\xE5\xA9...' for column 'page_title' at row 337
    at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1776)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2964)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
    at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
    ... 3 more

Can anyone help me solve this? Please help :(

**Comment by BaimAT** [comment]
I am not sure if I had the same problem as yours, but it sounded similar. What I did was, I manually delete the tables in `mysql` that were previously created in this step. (text, revision, page) or any tables that contains these words. then rerun `wkdb_cleaning_up.sh wkdb.conf`

**Comment by jetaudio** [comment]
I got the same result. Can it be the problem of the data type of page_title column?

**Comment by BaimAT** [comment]
Possibly. What I would do is delete any created files in directory and database in mysql. Then, redo step 2.2 again.

On a side note, I found out that we can just go to step 3 directly by doing something else and without relying on wikipedia. However, this might be case to case basis. Anyway, if you are ok with following the steps one by one, please ignore this side note.

**Comment by jetaudio** [comment]
I've just deleted everything and taken a new clone of marytts. I'll report back as soon as I repeat anything from the start. Thanks for your advice.

**Comment by jetaudio** [comment]
Just delete ruined file from wikilist.txt and everything will be alright. Thanks for your help @BaimAT :)))
