### ISSUE TITLE
Voice compile : fail to start module synthesis

### ISSUE THREAD

**Issue by yusufardi97** [marytts/marytts#588]
Hi,
I encouter this problem after i run all the previous step in building unit selection voice. All the previous step run just fine (got all of them success and giving expected outcome), but when i try to compile the voice i get this error
```
Opening GUI....... 
Loading database layout:
Reading config file /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/database.config
Loading basename list from file /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/basenames.lst
Found 339 files in basename list
Loading features from file /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/features.txt
INFO  VoiceCompiler: Creating directories
INFO  VoiceCompiler: Copying template files
INFO  VoiceCompiler: Copying voice files
INFO  VoiceCompiler: Compiling with Maven
maven out>[INFO] Scanning for projects...
maven out>[INFO]                                                                         
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Building voice-in 5.2-SNAPSHOT
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] 
maven out>[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ voice-in ---
maven out>[INFO] 
maven out>[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ voice-in ---
maven out>[INFO] Executing: /bin/sh -c cd '/media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in' && 'git' 'rev-parse' '--verify' 'HEAD'
maven out>[INFO] Working directory: /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in
maven out>[INFO] Storing buildNumber: null at timestamp: 1473142568625
maven out>[INFO] Storing buildScmBranch: master
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ voice-in ---
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] Copying 9 resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ voice-in ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ voice-in ---
maven out>[INFO] Using 'UTF-8' encoding to copy filtered resources.
maven out>[INFO] skip non existing resourceDirectory /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in/src/test/resources
maven out>[INFO] 
maven out>[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ voice-in ---
maven out>[INFO] Changes detected - recompiling the module!
maven out>[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
maven out>[INFO] 
maven out>[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ voice-in ---
maven out>[INFO] 
maven out>[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ voice-in ---
maven out>[INFO] Building jar: /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in/target/voice-in-5.2-SNAPSHOT.jar
maven out>[INFO] 
maven out>[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ voice-in ---
maven out>[INFO] Reading assembly descriptor: src/main/descriptors/installable.xml
maven out>[WARNING] The assembly descriptor contains a filesystem-root relative reference, which is not cross platform compatible /
maven out>[INFO] Building zip: /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in/target/voice-in-5.2-SNAPSHOT.zip
maven out>[INFO] 
maven out>[INFO] --- groovy-maven-plugin:2.0:execute (default) @ voice-in ---
maven out>[INFO] 
maven out>[INFO] --- build-helper-maven-plugin:1.10:attach-artifact (attach-artifacts) @ voice-in ---
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (integration-test) @ voice-in ---
maven out>
maven out>-------------------------------------------------------
maven out> T E S T S
maven out>-------------------------------------------------------
maven out>Running marytts.voice.In.LoadVoiceIT
**maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.773 sec <<< FAILURE! - in marytts.voice.In.LoadVoiceIT
maven out>marytts.voice.In.LoadVoiceIT  Time elapsed: 5.768 sec  <<< ERROR!
maven out>java.lang.Exception: Problem starting module Synthesis
maven out>	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.MaryConfigurationException: Cannot build unit selection voice 'in'
maven out>	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>Caused by: marytts.exceptions.NoSuchPropertyException: Missing value `voice.in.exampleTextFile' in configuration files
maven out>	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
maven out>
maven err>Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
maven err>	at marytts.server.Mary.shutdown(Mary.java:371)
maven err>	at marytts.server.Mary$2.run(Mary.java:290)**
maven out>
maven out>Results :
maven out>
maven out>Tests in error: 
maven out>  LoadVoiceIT.beforeClass:14 »  Problem starting module Synthesis
maven out>
maven out>Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
maven out>
maven out>[INFO] 
maven out>[INFO] --- maven-failsafe-plugin:2.19.1:verify (verify) @ voice-in ---
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] BUILD FAILURE
maven out>[INFO] ------------------------------------------------------------------------
maven out>[INFO] Total time: 01:22 min
maven out>[INFO] Finished at: 2016-09-06T13:17:10+07:00
maven out>[INFO] Final Memory: 29M/288M
maven out>[INFO] ------------------------------------------------------------------------
maven out>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (verify) on project voice-in: There are test failures.
maven out>[ERROR] 
maven out>[ERROR] Please refer to /media/yusufardi97/LinuxData/Dropbox/resourceTA/vb/gaib14/mary/voice-in/target/failsafe-reports for the individual test results.
maven out>[ERROR] -> [Help 1]
maven out>[ERROR] 
maven out>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
maven out>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
maven out>[ERROR] 
maven out>[ERROR] For more information about the errors and possible solutions, please read the following articles:
**maven out>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Maven compilation did not succeed -- check console for details.
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.compileWithMaven(VoiceCompiler.java:375)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:95)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)**
```

when i check fail-safe report it said:
```
-------------------------------------------------------------------------------
Test set: marytts.voice.In.LoadVoiceIT
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.773 sec <<< FAILURE! - in marytts.voice.In.LoadVoiceIT
marytts.voice.In.LoadVoiceIT  Time elapsed: 5.768 sec  <<< ERROR!
java.lang.Exception: Problem starting module Synthesis
	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot build unit selection voice 'in'
	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.NoSuchPropertyException: Missing value `voice.in.exampleTextFile' in configuration files
	at marytts.voice.In.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
```
I don't know how should i solve this, since it should appear to be generated file and not part of any configuration files within voice building folder that i use nor it inside configuration within the language folder. Could you give me insight about how to solve this?

nb: for alternative i'm trying to use the voice building gradle plugin, but without wiki like the legacy tools and experience running gradle projects, i feel at lost, so if the answer is to run the voice building gradle plugin, would you mind to elaborate the step needed? like where should i run the gradle and what to expect from the command. Thank you

**Comment by yusufardi97** [comment]
sorry for inconvenience, i feel stupid these past 3 days because i try to find whats wrong with this issue. After remembering that at some point i **change the domain into limited from general**, when i revert it back, the compiler work just fine.

**Comment by psmlbhor** [comment]
I have encountered the same issue. My **domain is set to general** but I am still getting the issue

**Comment by psibre** [comment]
@psmlbhor This issue is caused by a misconfiguration. In this case, the resource named by the `voice.in.exampleTextFile` property is missing.
