### ISSUE TITLE
LocalMaryInterface, adding maven voice dependencies properly

### ISSUE THREAD

**Issue by gnom7** [marytts/marytts#601]
Hello, I faced with some trouble when tried to use LocalMaryInterface I couldn't add some maven voice dependencies properly for it.
Can you help me please?
Some voice dependencies work fine, for example this one:
```
<dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-cmu-slt-hsmm</artifactId>
            <version>5.2</version>
</dependency>
```
But when I tried to add these:
```
<dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-upmc-pierre-hsmm</artifactId>
            <version>5.2</version>
</dependency>
<dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-istc-lucia-hsmm</artifactId>
            <version>5.2</version>
</dependency>
```
maven just unable to find them.
Can you please help me and explain why I can't add some voices?

P.S.
If I add for example `voice-istc-lucia-hsmm-5.2.jar` manually, I catch this Exception when instantiation of new LocalMaryInterface performed:
```
"C:\Program Files\Java\jdk1.8.0_101\bin\java" -Didea.launcher.port=7534 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_101\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_101\jre\lib\rt.jar;C:\op\target\classes;C:\Users\Super\.m2\repository\de\dfki\mary\voice-cmu-slt-hsmm\5.2\voice-cmu-slt-hsmm-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-common\5.2\marytts-common-5.2.jar;C:\Users\Super\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\Super\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Super\.m2\repository\log4j\log4j\1.2.16\log4j-1.2.16.jar;C:\Users\Super\.m2\repository\com\twmacinta\fast-md5\2.7.1\fast-md5-2.7.1.jar;C:\Users\Super\.m2\repository\org\codehaus\groovy\groovy-all\2.4.5\groovy-all-2.4.5.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-runtime\5.2\marytts-runtime-5.2.jar;C:\Users\Super\.m2\repository\com\ibm\icu\icu4j\54.1.1\icu4j-54.1.1.jar;C:\Users\Super\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\emotionml-checker-java\1.1\emotionml-checker-java-1.1.jar;C:\Users\Super\.m2\repository\de\dfki\lt\jtok\jtok-core\1.9.3\jtok-core-1.9.3.jar;C:\Users\Super\.m2\repository\org\slf4j\slf4j-api\1.6.1\slf4j-api-1.6.1.jar;C:\Users\Super\.m2\repository\org\slf4j\slf4j-log4j12\1.6.1\slf4j-log4j12-1.6.1.jar;C:\Users\Super\.m2\repository\com\google\guava\guava\14.0.1\guava-14.0.1.jar;C:\Users\Super\.m2\repository\net\sf\trove4j\trove4j\2.0.2\trove4j-2.0.2.jar;C:\Users\Super\.m2\repository\org\apache\httpcomponents\httpcore\4.1\httpcore-4.1.jar;C:\Users\Super\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.1\httpcore-nio-4.1.jar;C:\Users\Super\.m2\repository\org\apache\opennlp\opennlp-maxent\3.0.3\opennlp-maxent-3.0.3.jar;C:\Users\Super\.m2\repository\org\apache\opennlp\opennlp-tools\1.5.3\opennlp-tools-1.5.3.jar;C:\Users\Super\.m2\repository\net\sf\jwordnet\jwnl\1.3.3\jwnl-1.3.3.jar;C:\Users\Super\.m2\repository\org\hsqldb\hsqldb\2.0.0\hsqldb-2.0.0.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-lang-en\5.2\marytts-lang-en-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\voice-dfki-pavoque-neutral-hsmm\5.2\voice-dfki-pavoque-neutral-hsmm-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-lang-de\5.2\marytts-lang-de-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\voice-dfki-prudence-hsmm\5.2\voice-dfki-prudence-hsmm-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\voice-enst-dennys-hsmm\5.2\voice-enst-dennys-hsmm-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-lang-fr\5.2\marytts-lang-fr-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-client\5.2\marytts-client-5.2.jar;C:\Users\Super\.m2\repository\de\dfki\mary\marytts-signalproc\5.2\marytts-signalproc-5.2.jar;C:\Users\Super\.m2\repository\gov\nist\math\Jampack\1.0\Jampack-1.0.jar;C:\Users\Super\.m2\repository\gov\nist\math\jama\1.0.3\jama-1.0.3.jar;C:\Users\Super\.m2\repository\org\swinglabs\swing-layout\1.0.3\swing-layout-1.0.3.jar;C:\Users\Super\.m2\repository\org\incava\java-diff\1.1\java-diff-1.1.jar;C:\Users\Super\.m2\repository\com\sauron\jave\1.0.2\jave-1.0.2.jar;C:\Spring\HERE\project\marytts-5.2\marytts-5.2\lib\voice-istc-lucia-hsmm-5.2.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain Local
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at Local.main(Local.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.Exception: Problem starting module Synthesis
	at marytts.server.Mary.startModules(Mary.java:151)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 6 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'istc-lucia-hsmm'
	at marytts.modules.synthesis.Voice.<init>(Voice.java:184)
	at marytts.htsengine.HMMVoice.<init>(HMMVoice.java:94)
	at marytts.modules.synthesis.HMMSynthesizer.startup(HMMSynthesizer.java:157)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
	at marytts.modules.Synthesis.startup(Synthesis.java:65)
	at marytts.server.Mary.startModules(Mary.java:149)
	... 10 more
Caused by: marytts.exceptions.MaryConfigurationException: No allophone set specified -- neither for voice 'istc-lucia-hsmm' nor for locale 'it'
	at marytts.modules.synthesis.Voice.init(Voice.java:207)
	at marytts.modules.synthesis.Voice.<init>(Voice.java:182)
	... 15 more
Caused by: marytts.exceptions.MaryConfigurationException: No such property: it.allophoneset
	at marytts.util.MaryRuntimeUtils.needAllophoneSet(MaryRuntimeUtils.java:315)
	at marytts.modules.synthesis.Voice.init(Voice.java:205)
	... 16 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)

Process finished with exit code 1
```
So some languages (for example Italian, which has only one voice, which I can't add) become unavailable for local use.

My pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>op</groupId>
    <artifactId>op</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.0</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>


    <repositories>
        <!-- Mary TTS -->
        <repository>
            <id>MaryTTS</id>
            <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Local MaryTTS -->
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-cmu-slt-hsmm</artifactId>
            <version>5.2</version>
        </dependency>
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-dfki-pavoque-neutral-hsmm</artifactId>
            <version>5.2</version>
        </dependency>
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-dfki-prudence-hsmm</artifactId>
            <version>5.2</version>
        </dependency>
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-enst-dennys-hsmm</artifactId>
            <version>5.2</version>
        </dependency>
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-upmc-pierre-hsmm</artifactId>
            <version>5.2</version>
        </dependency>
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>voice-istc-lucia-hsmm</artifactId>
            <version>5.2</version>
        </dependency>

        <!-- Remote MaryTTS -->
        <dependency>
            <groupId>de.dfki.mary</groupId>
            <artifactId>marytts-client</artifactId>
            <version>5.2</version>
        </dependency>
```

**Comment by psibre** [comment]
The HSMM voices are hosted on Bintray, and can be resolved from [JCenter](https://bintray.com/bintray/jcenter). Unfortunately, it seems that a few of these voices were not indexed in JCenter as expected, but this should be resolved very soon.
In the meantime, *all* voices and marytts artifacts can be resolved by adding a maven repository with the URL https://dl.bintray.com/marytts/marytts.

**Comment by gnom7** [comment]
Thank you a lot, now it works!

**Comment by psibre** [comment]
For the record, it should now also work as before, using https://jcenter.bintray.com for any of the HSMM voices.
