### ISSUE TITLE
VoiceImportTool external libs

### ISSUE THREAD

**Issue by proewer** [marytts/marytts#612]
I create a wav and text dir with my own program. After that I want to create a new voice for marytts.
I used the step by step instruction from the project wiki (HMMVoiceCreation). At step 9- Run the HMMVoiceDataPreparation I get problems. No error massage. I have installed all external libs. I use the check and install script. Is there a download link/script with all external libs for windows or ubuntu? How can I check if a lib is missing or does not work?

**Comment by seblemaguer** [comment]
Hello,

can you describe the problems ? Because from here it is difficult to see :D

**Comment by proewer** [comment]
of course :) my workflow:

1. download marytts-5.2, unpack and start the server
2. download marytts-builder-5.2, unpack and go in the lib dir
3. create a external dir and put the check_install_external_programs.sh from the github master
4. sudo apt-get install mc libc6-dev-i386 libx11-dev libncurses5-dev git
sox g++, tcl, tcl-snack, mawk, gawk, original-awk, bc, perl
5. install speech tools (speech tools-2.4-release.tar.gz -> tar, configure, make)
6. install festvox (festvox-2.7.0-release.tar.gz -> tar, configure, make)
7. install festival (festival-2.4-release.tar.gz -> tar, configure, make)
8. put the files HTK-3.4.1tar.gz, HDecode-3.4.1.tar.gz and ehmm.tar.gz in the external dir
9. run check_install_external_programs.sh -install
10. start ./voiceimport.sh
11. steps from the wiki article HMMVoiceCreation up to step 9- Run the HMMVoiceDataPreparation -> fail

i think 5. -7. are no effected and not impossible.
maybe some settings or configs are wrong? see attached.

i have noticed, that the folling file not exsis. it is impossible, if yes how to create this file?
HMMVoiceConfigure.configureFile /home/paul/Schreibtisch/Paul/hts/configure

[configs.zip](https://github.com/marytts/marytts/files/520054/configs.zip)

my terminal output:
```
paul@paul-pc:~$ cd Schreibtisch/marytts-builder-5.2/bin/
paul@paul-pc:~/Schreibtisch/marytts-builder-5.2/bin$ ./voiceimport.sh 
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~14.04-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Opening GUI....... 
Loading database layout:
db.fileDir /home/paul/Schreibtisch/Paul/mary/ does not exist; Created successfully.
db.tempDir /home/paul/Schreibtisch/Paul/temp/ does not exist; Created successfully.
db.maryxmlDir /home/paul/Schreibtisch/Paul/rawmaryxml/ does not exist; Created successfully.
db.promptAllophonesDir /home/paul/Schreibtisch/Paul/prompt_allophones/ does not exist; Created successfully.
db.allophonesDir /home/paul/Schreibtisch/Paul/allophones/ does not exist; Created successfully.
db.labDir /home/paul/Schreibtisch/Paul/lab/ does not exist; Created successfully.
Loading basename list from wav files
Found 3 files in basename list
PhoneUnitFeatureComputer.featureDir /home/paul/Schreibtisch/Paul/phonefeatures/ does not exist; Created successfully.
HalfPhoneUnitFeatureComputer.featureDir /home/paul/Schreibtisch/Paul/halfphonefeatures/ does not exist; Created successfully.
Label directory /home/paul/Schreibtisch/Paul/phonelab/ does not exist; Created successfully.
Label directory /home/paul/Schreibtisch/Paul/halfphonelab/ does not exist; Created successfully.
Computing ALLOPHONES files for 3 files
Mary TTS client 5.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2 (impl. unknown)
    1
    2
    3
...Done.
Preparing voice database for labelling using EHMM :
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Setting up EHMM directory ...
 ... done.
Getting Phone Sequence from Phone Features...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Dumping required files ....
( cd /home/paul/Schreibtisch/Paul/ehmm; perl /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/phfromutt.pl /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.align /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.phoneList 5; perl /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/getwavlist.pl /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.align /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.waveList; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Computing MFCCs ...
( cd /home/paul/Schreibtisch/Paul/ehmm; /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/FeatureExtraction /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.featSettings /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.waveList >> log.txt; perl /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/comp_dcep.pl /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.waveList /home/paul/Schreibtisch/Paul/ehmm/feat mfcc ft 0 0 >> log.txt ; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Scaling Feature Vectors ...
( cd /home/paul/Schreibtisch/Paul/ehmm; perl /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/scale_feat.pl /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.waveList /home/paul/Schreibtisch/Paul/ehmm/feat /home/paul/Schreibtisch/Paul/ehmm/mod ft 4 >> log.txt; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Converting Feature Vectors to Binary Format ...
( cd /home/paul/Schreibtisch/Paul/ehmm/feat; for file in *.ft; do /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/ConvertFeatsFileToBinaryFormat $file ${file%%.ft}.bft >> ../log.txt; done; exit )

 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Intializing EHMM Model ...
 ... done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
EHMM baum-welch re-estimation ...
It may take more time (may be 1 or 2 days) depending on voice database ...
( cd /home/paul/Schreibtisch/Paul/ehmm; /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/ehmm /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.phoneList.int /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.align.int 1 0 /home/paul/Schreibtisch/Paul/ehmm/feat bft /home/paul/Schreibtisch/Paul/ehmm/mod 0 0 0 48 4 >> log.txt; exit )

.... Done.
See $ROOTDIR/ehmm/log.txt for EHMM Labelling status... 
Aligning EHMM for labelling ...
( cd /home/paul/Schreibtisch/Paul/ehmm; /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/edec /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.phoneList.int /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.align.int 1 /home/paul/Schreibtisch/Paul/ehmm/feat bft /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.featSettings /home/paul/Schreibtisch/Paul/ehmm/mod 0 /home/paul/Schreibtisch/Paul/ehmm/lab 4 >> log.txt; perl /home/paul/Schreibtisch/marytts-builder-5.2/lib/external//bin/sym2nm.pl /home/paul/Schreibtisch/Paul/ehmm/lab /home/paul/Schreibtisch/Paul/ehmm/etc/ehmm.phoneList.int >> log.txt; exit )

Label file Generation Successfully completed using EHMM !
Copying label files into lab directory ...
    1
    2
    3
 ... done.
traversing through 3 files
1
/home/paul/Schreibtisch/Paul/lab/1.lab
Orig   : _|?|I|C|_|h|aI|?|_|p|aU|l|_|?|U|n|t|_|v|o:|n|@|_|?|I|n|_|n|OY|b|R|a|n|d|@|n|b|U|6|k|_
Correct: _|?|I|C|h|aI|?|p|aU|l|?|U|n|t|v|o:|n|@|?|I|n|n|OY|b|R|a|n|d|@|n|b|U|6|k|_
Alignments:  _ # ? # I # C # # h # aI # ? # # p # aU # l # # ? # U # n # t # # v # o: # n # @ # # ? # I # n # # n # OY # b # R # a # n # d # @ # n # b # U # 6 # k # _ 
Boundary, align =  _ 
Ph = ?, align =  ? 
Ph = I, align =  I 
Ph = C, align =  C 
Ph = h, align =  h 
Ph = aI, align =  aI 
Ph = ?, align =  ? 
Ph = p, align =  p 
Ph = aU, align =  aU 
Ph = l, align =  l 
Ph = ?, align =  ? 
Ph = U, align =  U 
Ph = n, align =  n 
Ph = t, align =  t 
Ph = v, align =  v 
Ph = o:, align =  o: 
Ph = n, align =  n 
Ph = @, align =  @ 
Ph = ?, align =  ? 
Ph = I, align =  I 
Ph = n, align =  n 
Ph = n, align =  n 
Ph = OY, align =  OY 
Ph = b, align =  b 
Ph = R, align =  R 
Ph = a, align =  a 
Ph = n, align =  n 
Ph = d, align =  d 
Ph = @, align =  @ 
Ph = n, align =  n 
Ph = b, align =  b 
Ph = U, align =  U 
Ph = 6, align =  6 
Ph = k, align =  k 
Boundary, align =  _ 
2
/home/paul/Schreibtisch/Paul/lab/2.lab
Orig   : _|?|a|m|_|l|i:|p|s|t|@|n|_|z|I|ts|t|@|_|?|I|C|_|?|a|n|_|m|aI|n|@|m|_|k|O|m|p|j|u:|t|6|_|?|U|n|t|_|p|R|o:|g|R|a|m|i:|6|R|@|_|k|o:|o:|l|@|_|z|a|x|@|n|_
Correct: _|?|a|m|l|i:|p|s|t|@|n|z|I|ts|t|@|?|I|C|?|a|n|m|aI|n|@|m|k|O|m|p|j|u:|t|6|?|U|n|t|p|R|o:|g|R|a|m|i:|6|R|@|k|o:|o:|l|@|z|a|x|@|n|_
Alignments:  _ # ? # a # m # # l # i: # p # s # t # @ # n # # z # I # ts # t # @ # # ? # I # C # # ? # a # n # # m # aI # n # @ # m # # k # O # m # p # j # u: # t # 6 # # ? # U # n # t # # p # R # o: # g # R # a # m # i: # 6 # R # @ # # k # o: # o: # l # @ # # z # a # x # @ # n # _ 
Boundary, align =  _ 
Ph = ?, align =  ? 
Ph = a, align =  a 
Ph = m, align =  m 
Ph = l, align =  l 
Ph = i:, align =  i: 
Ph = p, align =  p 
Ph = s, align =  s 
Ph = t, align =  t 
Ph = @, align =  @ 
Ph = n, align =  n 
Ph = z, align =  z 
Ph = I, align =  I 
Ph = ts, align =  ts 
Ph = t, align =  t 
Ph = @, align =  @ 
Ph = ?, align =  ? 
Ph = I, align =  I 
Ph = C, align =  C 
Ph = ?, align =  ? 
Ph = a, align =  a 
Ph = n, align =  n 
Ph = m, align =  m 
Ph = aI, align =  aI 
Ph = n, align =  n 
Ph = @, align =  @ 
Ph = m, align =  m 
Ph = k, align =  k 
Ph = O, align =  O 
Ph = m, align =  m 
Ph = p, align =  p 
Ph = j, align =  j 
Ph = u:, align =  u: 
Ph = t, align =  t 
Ph = 6, align =  6 
Ph = ?, align =  ? 
Ph = U, align =  U 
Ph = n, align =  n 
Ph = t, align =  t 
Ph = p, align =  p 
Ph = R, align =  R 
Ph = o:, align =  o: 
Ph = g, align =  g 
Ph = R, align =  R 
Ph = a, align =  a 
Ph = m, align =  m 
Ph = i:, align =  i: 
Ph = 6, align =  6 
Ph = R, align =  R 
Ph = @, align =  @ 
Ph = k, align =  k 
Ph = o:, align =  o: 
Ph = o:, align =  o: 
Ph = l, align =  l 
Ph = @, align =  @ 
Ph = z, align =  z 
Ph = a, align =  a 
Ph = x, align =  x 
Ph = @, align =  @ 
Ph = n, align =  n 
Boundary, align =  _ 
3
/home/paul/Schreibtisch/Paul/lab/3.lab
Orig   : _|R|a|m|o:|n|a:|_|g|i:|t|_|?|i:|R|@|_|b|l|u:|m|@|n|_|?|U|n|t|_|6|g|6|t|_|z|I|C|_|b|@|6|_|d|i:|_|k|f|E|6|_
Correct: _|R|a|m|o:|n|a:|g|i:|t|?|i:|R|@|b|l|u:|m|@|n|?|U|n|t|6|g|6|t|z|I|C|b|@|6|d|i:|k|f|E|6|_
Alignments:  _ # R # a # m # o: # n # a: # # g # i: # t # # ? # i: # R # @ # # b # l # u: # m # @ # n # # ? # U # n # t # # 6 # g # 6 # t # # z # I # C # # b # @ # 6 # # d # i: # # k # f # E # 6 # _ 
Boundary, align =  _ 
Ph = R, align =  R 
Ph = a, align =  a 
Ph = m, align =  m 
Ph = o:, align =  o: 
Ph = n, align =  n 
Ph = a:, align =  a: 
Ph = g, align =  g 
Ph = i:, align =  i: 
Ph = t, align =  t 
Ph = ?, align =  ? 
Ph = i:, align =  i: 
Ph = R, align =  R 
Ph = @, align =  @ 
Ph = b, align =  b 
Ph = l, align =  l 
Ph = u:, align =  u: 
Ph = m, align =  m 
Ph = @, align =  @ 
Ph = n, align =  n 
Ph = ?, align =  ? 
Ph = U, align =  U 
Ph = n, align =  n 
Ph = t, align =  t 
Ph = 6, align =  6 
Ph = g, align =  g 
Ph = 6, align =  6 
Ph = t, align =  t 
Ph = z, align =  z 
Ph = I, align =  I 
Ph = C, align =  C 
Ph = b, align =  b 
Ph = @, align =  @ 
Ph = 6, align =  6 
Ph = d, align =  d 
Ph = i:, align =  i: 
Ph = k, align =  k 
Ph = f, align =  f 
Ph = E, align =  E 
Ph = 6, align =  6 
Boundary, align =  _ 
Mary TTS client 5.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2 (impl. unknown)
Saving features to /home/paul/Schreibtisch/Paul/mary/features.txt
Loading features from file /home/paul/Schreibtisch/Paul/mary/features.txt
Computing unit features for 3 files
Mary TTS client 5.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.2 (impl. unknown)
    1
    2
    3
Finished computing the unit features.
Verifying feature-label alignment for 3 utterances.
    1 No label file /home/paul/Schreibtisch/Paul/phonelab/1.lab
    2 No label file /home/paul/Schreibtisch/Paul/phonelab/2.lab
    3 No label file /home/paul/Schreibtisch/Paul/phonelab/3.lab
Found 3 problems
    1    2    3Remaining problems: 0
Removed [0/3] utterances from the list, [3] utterances remain, among which [0/3] still have problems.

HMMVoiceDataPreparation:
Checking paths of external programs
  *Missing path for awk
  *Missing path for perl
  *Missing path for bc
  *Missing path for tclsh
  *Missing path for sox
  *Missing path for hts/htk
  *Missing path for hts_engine
  *Missing path for sptk
  *Missing path for ehmm
Please run MARYBASE/lib/external/check_install_external_programs.sh and check/install the missing programs
```

**Comment by psibre** [comment]
Several things:
- You can install `speech-tools` through `apt`.
- There is no need to install festvox or festival.
- You should separate your voicebuilding project from the MaryTTS source code.
- You cannot hope to build a voice with only three short utterances. You need at least an hour or two of recordings.
- You should not force-align your data as part of the main build process; but if you must, take care to not run the EHMMLabeler more than once.
- Your external tools are not configured correctly. Please see [the wiki](../wiki/HMMVoiceCreation#stepII) or [here](584#issuecomment-242301685).

**Comment by proewer** [comment]
- I install speech-tools through apt
- run the check_install_external_programs.sh -check
- I use a short example for testing the voice building, later big recordings
- I use the wiki page, at step HMMVoiceDataPreparation fail, your link is not helpful

It is possible that someone send me the external lib dir for linux or windows?

**Comment by nshmyrev** [comment]
> It is possible that someone send me the external lib dir for linux or windows?

I doubt its reasonable to share binaries. Instead you need to:

1. Provide the output of check_install_external_programs.sh -check
2. Provide contents of $PATH variable
3. Provide actuals paths of installed tools
4. Provide database.config from voice build

The more information you provide the faster you get solution to your problem.

**Comment by proewer** [comment]
paul@paul-pc:~/Schreibtisch/marytts-builder-5.2/lib/external$ ./check_install_external_programs.sh -check
MARY_BASE=/home/paul/Schreibtisch/marytts-builder-5.2

option=-check
awk: /usr/bin/awk
ok

perl: /usr/bin/perl
ok

tclsh: /usr/bin/tclsh
tclsh was found and supports snack
ok

bc: /usr/bin/bc
bc: checking -l (mathlib)
ok

sox: /usr/bin/sox
ok

HTK HHEd exists
HTK version: 3.4.1
HTK HHED contains HTS commands like CM 
HTK ok

hts_engine exists
hts_engine: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin/hts_engine
ok

SPTK mgcep exists
SPTK mgcep: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin/mgcep
SPTK gmm exist, SPTK version >= 3.2
ok

festvox ehmm exists
festvox ehmm: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin/ehmm
ehmm exist
ok

________________________________________________________________
Programs status (detailed information above):
The following paths should be in the PATH variable
  awk: /usr/bin
  perl: /usr/bin
  bc: /usr/bin
The following paths are used when running HMMVoiceConfigure
  tclsh: /usr/bin
  sox: /usr/bin
  hts/htk: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin
  hts_engine: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin
  sptk: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin
This path is used when running the EHMMlabeler
  ehmm: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/bin

List of paths in: /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/externalBinaries.config

paul@paul-pc:~/Schreibtisch/marytts-builder-5.2/lib/external$

**Comment by proewer** [comment]
paul@paul-pc:~/Schreibtisch/marytts-builder-5.2/lib/external$ echo $PATH/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
paul@paul-pc:~/Schreibtisch/marytts-builder-5.2/lib/external$

**Comment by proewer** [comment]
thanks for your support :)

[database.config.tar.gz](https://github.com/marytts/marytts/files/545062/database.config.tar.gz)

**Comment by psibre** [comment]
The hacky way in which the `externalBinaries.config` is integrated, [requires `db.marybase` to be set correctly](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-builder/src/main/java/marytts/tools/voiceimport/DatabaseLayout.java#L234-L243), so you need to configure the line
```
db.marybase /path/to/marybase/
```
in your `database.config` correctly.

**Comment by proewer** [comment]
what is the path to marybase??? localhost or path to mary server bin dir?

**Comment by psibre** [comment]
If you click on the hyperlink in my previous comment, you will see.

**Comment by proewer** [comment]
it's work but i get the following exception:

```
Opening GUI....... 
Loading database layout:
Reading config file /home/paul/Schreibtisch/Paul/database.config
Reading external binaries config file /home/paul/Schreibtisch/marytts-builder-5.2/lib/external/externalBinaries.config
Loading basename list from wav files
Found 3 files in basename list
Loading features from file /home/paul/Schreibtisch/Paul/mary/features.txt

HMMVoiceDataPreparation:
Checking paths of external programs
Paths for all external programs are defined.
Source folder does not exist!

Checking wav/raw and text directories and files for running HTS speaker independent training scripts...
Checking if /home/paul/Schreibtisch/Paul/wav contains files
Converting wav files to raw from: /home/paul/Schreibtisch/Paul/wav  to: /home/paul/Schreibtisch/Paul/hts/data/raw
chmod: Zugriff auf »/home/paul/Schreibtisch/Paul/hts/data/scripts/wav2raw.sh“ nicht möglich: Datei oder Verzeichnis nicht gefunden
java.lang.Exception: The component HMMVoiceDataPreparation produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException: wav2raw computation failed on file [/home/paul/Schreibtisch/Paul/]!
Command line was: [chmod +x /home/paul/Schreibtisch/Paul/hts/data/scripts/wav2raw.sh].
	at marytts.util.io.General.launchProc(General.java:549)
	at marytts.tools.voiceimport.HMMVoiceDataPreparation.convertWav2Raw(HMMVoiceDataPreparation.java:376)
	at marytts.tools.voiceimport.HMMVoiceDataPreparation.compute(HMMVoiceDataPreparation.java:199)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```

which hts folder is mean?

**Comment by BenjaminPoilve** [comment]
Hi ,
Got the very same error. It turned out the script didn't automatically made the copy of the hts folder. Simply copy/paste this folder (should be in lib/external/ if you ran the check_install_external_programs script)
