### ISSUE TITLE
Can't install marytts on Ubuntu - TESTS fail

### ISSUE THREAD

**Issue by haquynh1505** [marytts/marytts#626]
Hi you guys,
I'm brand new in the field and I've been trying to install marytts on Ubuntu 16.04 
Everything was fine until I bumped into this annoying error while running "mvn install". 
I have yet to figure out how to fix it, so please take a look and help me with this.
Thanks in advance for your help! 

```
mhn@mhn:/voice/sources/marytts$ JAVA_HOME=/voice/soft/java /voice/soft/maven/bin/mvn -X install
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T23:41:47+07:00)
Maven home: /voice/soft/maven
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /voice/soft/java/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-45-generic", arch: "amd64", family: "unix"


-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[DEBUG] boot classpath:  /home/hanguyen/.m2/repository/org/apache/maven/surefire/surefire-booter/2.19.1/surefire-booter-2.19.1.jar  /home/hanguyen/.m2/repository/org/apache/maven/surefire/surefire-api/2.19.1/surefire-api-2.19.1.jar  /voice/sources/marytts/marytts-common/target/test-classes  /voice/sources/marytts/marytts-common/target/classes  /home/hanguyen/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar  /home/hanguyen/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar  /home/hanguyen/.m2/repository/junit/junit/4.12/junit-4.12.jar  /home/hanguyen/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar  /home/hanguyen/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar  /home/hanguyen/.m2/repository/com/twmacinta/fast-md5/2.7.1/fast-md5-2.7.1.jar  /home/hanguyen/.m2/repository/org/codehaus/groovy/groovy-all/2.4.5/groovy-all-2.4.5.jar  /home/hanguyen/.m2/repository/org/testng/testng/6.9.11/testng-6.9.11.jar  /home/hanguyen/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar  /home/hanguyen/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar  /home/hanguyen/.m2/repository/org/apache/ant/ant/1.7.0/ant-1.7.0.jar  /home/hanguyen/.m2/repository/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar  /home/hanguyen/.m2/repository/org/apache/maven/surefire/surefire-testng-utils/2.19.1/surefire-testng-utils-2.19.1.jar  /home/hanguyen/.m2/repository/org/apache/maven/surefire/surefire-grouper/2.19.1/surefire-grouper-2.19.1.jar  /home/hanguyen/.m2/repository/org/apache/maven/surefire/surefire-testng/2.19.1/surefire-testng-2.19.1.jar  /home/hanguyen/.m2/repository/org/apache/maven/surefire/common-java5/2.19.1/common-java5-2.19.1.jar
[DEBUG] boot(compact) classpath:  surefire-booter-2.19.1.jar  surefire-api-2.19.1.jar  test-classes  classes  commons-lang-2.6.jar  commons-io-2.5.jar  junit-4.12.jar  hamcrest-core-1.3.jar  log4j-1.2.16.jar  fast-md5-2.7.1.jar  groovy-all-2.4.5.jar  testng-6.9.11.jar  bsh-2.0b4.jar  jcommander-1.48.jar  ant-1.7.0.jar  ant-launcher-1.7.0.jar  surefire-testng-utils-2.19.1.jar  surefire-grouper-2.19.1.jar  surefire-testng-2.19.1.jar  common-java5-2.19.1.jar
Forking command line: /bin/sh -c cd /voice/sources/marytts/marytts-common && /voice/soft/java/jre/bin/java -Xms256m -Xmx512m -XX:MaxPermSize=128m -jar /voice/sources/marytts/marytts-common/target/surefire/surefirebooter2491858978837272470.jar /voice/sources/marytts/marytts-common/target/surefire/surefire1145511622047945376tmp /voice/sources/marytts/marytts-common/target/surefire/surefire_04616053325804941999tmp
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
Running TestSuite
Configuring TestNG with: TestNG60Configurator
Test version expected null
Tests run: 84, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.148 sec <<< FAILURE! - in TestSuite
testVersion(marytts.VersionTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at marytts.VersionTest.testVersion(VersionTest.java:12)


Results :

Failed tests: 
  VersionTest.testVersion:12 expected object to not be null

Tests run: 84, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ............................................ SUCCESS [  2.195 s]
[INFO] marytts-common ..................................... FAILURE [  5.851 s]
[INFO] marytts-signalproc ................................. SKIPPED
[INFO] marytts-runtime .................................... SKIPPED
[INFO] marytts-lang-de .................................... SKIPPED
[INFO] marytts-lang-en .................................... SKIPPED
[INFO] marytts-lang-te .................................... SKIPPED
[INFO] marytts-lang-tr .................................... SKIPPED
[INFO] marytts-lang-ru .................................... SKIPPED
[INFO] marytts-lang-it .................................... SKIPPED
[INFO] marytts-lang-fr .................................... SKIPPED
[INFO] marytts-lang-sv .................................... SKIPPED
[INFO] marytts-lang-lb .................................... SKIPPED
[INFO] marytts-languages .................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................. SKIPPED
[INFO] marytts-client ..................................... SKIPPED
[INFO] marytts-builder .................................... SKIPPED
[INFO] marytts-redstart ................................... SKIPPED
[INFO] marytts-transcription .............................. SKIPPED
[INFO] marytts-assembly-builder ........................... SKIPPED
[INFO] marytts-assembly-runtime ........................... SKIPPED
[INFO] marytts-assembly ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.590 s
[INFO] Finished at: 2016-10-26T15:21:22+07:00
[INFO] Final Memory: 21M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project marytts-common: There are test failures.
[ERROR] 
[ERROR] Please refer to /voice/sources/marytts/marytts-common/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project marytts-common: There are test failures.

Please refer to /voice/sources/marytts/marytts-common/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /voice/sources/marytts/marytts-common/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:320)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:892)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-common
```

**Comment by psibre** [comment]
@haquynh1505 Could you please edit your question so that we don't have to go through thousands of lines of debug output? What's the error?

**Comment by haquynh1505** [comment]
@psibre : I'm sorry for the inconvenience! I've shortened the question already. Is it clear enough now?

**Comment by seblemaguer** [comment]
thanks, I managed to reproduce it too

**Comment by seblemaguer** [comment]
so if you use gradle it is working

```sh
./gradlew b
```

but maven is failing as there is no property ```project.version```.

is the normal compilation moved to gradle completely ?

**Comment by psibre** [comment]
> Did the normal compilation moved to gradle completely ?

Actually, the integration test classpath is different with gradle and maven, which led to one test failing (it was expecting failure with maven, but "unexpectedly" working with gradle). I'd inverted that test, and now it's working with gradle, but unexpectedly failing with maven.

My fault -- I hadn't thought that people would still try to build 6.0-SNAPSHOT (the master branch) with maven, but in hindsight that's perfectly reasonable, because the POM files are still there and the README hasn't been updated yet...

**Comment by psibre** [comment]
Wait, I got confused. I was talking about a different test (see 46122eaa6000a8c785d3599f80b81de29d07fb6c). This issue is actually about something else.

**Comment by haquynh1505** [comment]
@psibre @seblemaguer : Can you guys make it more easily? I'm so new with all these stuffs, so I hardly get all of them. I've been following the following instructions that my teacher gave me. What should I do now to fix it? 

cd /voice/sources/
git clone https://github.com/marytts/marytts.git
cd marytts/lib/external/ehmm
make
cd ..
PATH=$PATH:/voice/soft/hts/bin:/voice/soft/hts_engine/bin:/voice/soft/SPTK/bin:/voice/sources/marytts/lib/external/ehmm/bin
./check_install_external_programs.sh –check
cd /voice/sources/marytts
JAVA_HOME=/voice/soft/java /voice/soft/maven/bin/mvn install

**Comment by psibre** [comment]
@haquynh1505 What you just posted has *nothing* to do with this issue.

Quick solution: use the `5.x` branch. Also tell your teacher.

**Comment by psibre** [comment]
For the record, version 6.0-SNAPSHOT is intended to be built with gradle, and then this is a non-issue. In the meantime (i.e., until we've updated the documentation), the hotfix in b37863976c497135cdc50a63f0791ac7298de5cc will take care of cases where maven is inadvertently used when building from the master branch.

**Comment by haquynh1505** [comment]
@psibre @seblemaguer Thank you so much you guys! I followed @psibre's instructions. It works now :+1:
