### ISSUE TITLE
HMMVoiceCompiler Errors 

### ISSUE THREAD

**Issue by haquynh1505** [marytts/marytts#630]
Hi guys, 
I've been importing a new voice to Mary for several days. Yesterday, I successfully ran HMMVoiceMakeData and HMMVoiceMakeVoice. Therefore, this morning I continued running, first by GUI, HMMVoiceCompiler and I got the following Errors:

-----------------------------------------------------------------------------------------------------------
java.lang.Exception: The component VoiceCompiler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.FileNotFoundException: Source '/voice/data/demo/mary/cart.mry' does not exist
	at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
	at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:1012)
	at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:973)
	at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.copyVoiceFiles(VoiceCompiler.java:356)
	at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:92)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

-----------------------------------------------------------------------------------------------------------

Then I ran it by these commands 
cd /voice/data/mary/voice-my_voice-hsmm
JAVA_HOME=/voice/soft/java  /voice/soft/maven/bin/mvn install
But I still got no luck. I bumped into the following errors while running these commands 

------------------------------------------------------------------------------------------------------------
T E S T S
-------------------------------------------------------
Running marytts.voice.My_voice.LoadVoiceIT
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.752 sec <<< FAILURE! - in marytts.voice.My_voice.LoadVoiceIT
marytts.voice.My_voice.LoadVoiceIT  Time elapsed: 0.751 sec  <<< ERROR!
java.lang.Exception: Problem starting module Synthesis
	at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'my_voice'
	at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.MaryConfigurationException: For property 'voice.my_voice.duration.data', no classpath resource available at '/marytts/voice/My_voice/dur.tree'
	at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)
Results :
Tests in error: 
  LoadVoiceIT.beforeClass:14 »  Problem starting module Synthesis
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

-----------------------------------------------------------------------------------------------------------------------------

and

-------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (verify) on project voice-my_voice: There are test failures.
[ERROR] 
[ERROR] Please refer to /voice/data/demo/mary/voice-my_voice/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (verify) on project voice-my_voice: There are test failures.

Please refer to /voice/data/demo/mary/voice-my_voice/target/failsafe-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /voice/data/demo/mary/voice-my_voice/target/failsafe-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:91)
	at org.apache.maven.plugin.failsafe.VerifyMojo.execute(VerifyMojo.java:202)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

---------------------------------------------------------------------------------------------------

Anybody knows how to fix this? Thank you so much!

**Comment by psibre** [comment]
```
java.lang.Exception: The component VoiceCompiler produced the following exception:
at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.FileNotFoundException: Source '/voice/data/demo/mary/cart.mry' does not exist
at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1072)
at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:1012)
at org.apache.commons.io.FileUtils.copyFileToDirectory(FileUtils.java:973)
at marytts.tools.voiceimport.VoiceCompiler$MavenVoiceCompiler.copyVoiceFiles(VoiceCompiler.java:356)
at marytts.tools.voiceimport.VoiceCompiler.compute(VoiceCompiler.java:92)
at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
The (unit-selection) **VoiceCompiler** cannot find the resources that should have been created in previous steps. But the **HMMVoiceCompiler** should not try to copy them anyway.

```
java.lang.Exception: Problem starting module Synthesis
at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'my_voice'
at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Caused by: marytts.exceptions.MaryConfigurationException: For property 'voice.my_voice.duration.data', no classpath resource available at '/marytts/voice/My_voice/dur.tree'
at marytts.voice.My_voice.LoadVoiceIT.beforeClass(LoadVoiceIT.java:14)
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
at marytts.server.Mary.shutdown(Mary.java:371)
at marytts.server.Mary$2.run(Mary.java:290)
```
Manually running Maven also fails, because the unit-selection resources is missing.

Both of these symptoms indicate that you might have run the **VoiceCompiler** by mistake, and not the **HMMVoiceCompiler**. Please remove all Maven project directories under `mary/`, and run *only* the **HMMVoiceCompiler**.
