### ISSUE TITLE
wkdb_database_selector.sh wkdb.conf

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#650]
hi,
please help me to fix the following issue.

openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

Starting Database Selection...
Reading arguments ...
Current directory: /local/mary/marytts2/target/marytts-builder-5.1.2/bin  MARY_BASE=/local/mary/marytts2/target/marytts-builder-5.1.2
  locale : as
  mysqlHost : localhost
  mysqlUser : mary
  mysqlPasswd : redhat
  mysqlDB : wiki
  selectedSentencesTable name: wiki
  tableDescription: Testing table for selected sentences. Wikipedia locale:  
  stop criterion : numSentences 90 simpleDiphones simpleProsody 
  logCoverageDevelopment
  verbose

Checking if there is [locale]_featureDefinition.txt in the current directory
Using as_featureDefinition.txt in current directory.

Checking if there is already a covDef.config in the current directory
Using covDef.config in current directory.
covDefConfigFileName = /local/mary/marytts2/target/marytts-builder-5.1.2/bin/covDef.config

Checking stop criterion:
Stop: num sentences 90
Stop: simpleDiphones
Stop: simpleProsody

Mysql driver loaded, set locale=as
Current selected sentences table name = as_wiki_selectedSentences
Mysql connection created successfully.

Loading feature definition...
TARGETFEATURES:3 =  phone next_phone selection_prosody
Getting a list of ids for all the sentences in the DB...
(if the number of sentences is large, this can take a while)

Will also load feature vectors into memory (increase memory if this fails)
1988 sentences to retrieve...

Initiating coverage...
TARGETFEATURES used:
  feature(0)=phone
  feature(1)=next_phone
  feature(2)=selection_prosody

Checking if as_wiki_selectedSentences already exist.
  TABLE = as_wiki_selectedSentences already exist. New selected sentences will be added to this table.
  A description for the table as_wiki_selectedSentences already exist in TABLE = tablesDescription.
Num Tokens: 21748

Add to cover already selected sentences marked as unwanted=false.

Adding previously selected sentences ...
Added to cover 1 selected sentences

Removing selected sentences marked as unwanted=true.

Removing unwanted sentences ...
WARNING empty list for: SELECT dbselection_id FROM as_wiki_selectedSentences where unwanted=true;
There is no unwanted sentences to remove.
Startup took 77 milliseconds

Selecting sentences...
Starting builtin MARY TTS... MARY TTS started.
Total number of selected sentences in TABLE: as_wiki_selectedSentences = 1
Saving selected sentences in ./selected.log
Saving selected sentences and transcriptions in ./selected_text_transcription.log
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at marytts.tools.dbselection.SelectionFunction.transcribe(SelectionFunction.java:291)
	at marytts.tools.dbselection.SelectionFunction.select(SelectionFunction.java:256)
	at marytts.tools.dbselection.DatabaseSelector.main2(DatabaseSelector.java:295)
	at marytts.tools.dbselection.DatabaseSelector.main(DatabaseSelector.java:114)

**Comment by jayanta1122** [comment]
someone please give a solution
