### ISSUE TITLE
Publishing voice

### ISSUE THREAD

**Issue by Nandutu** [marytts/marytts#662]
I added a new language successful and build a voice. 
My local exists http://localhost:59125/locales
But when doing the step of publishing the voice
'[https://github.com/marytts/marytts/wiki/Publishing-a-MARY-TTS-Voice]' 
i happened to run the server and i come into an error below
`~/marytts/target/marytts-5.2-SNAPSHOT/bin$ ./marytts-server
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK Server VM (build 24.95-b01, mixed mode)

MARY server 5.2-SNAPSHOT starting as a HTTP server...Exception in thread "main" java.lang.Exception: Problem starting module Synthesis
	at marytts.server.Mary.startModules(Mary.java:151)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.server.Mary.main(Mary.java:513)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate voice 'my_voice'
	at marytts.modules.synthesis.Voice.<init>(Voice.java:184)
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:81)
	at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:94)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
	at marytts.modules.Synthesis.startup(Synthesis.java:65)
	at marytts.server.Mary.startModules(Mary.java:149)
	... 3 more
Caused by: marytts.exceptions.MaryConfigurationException: No allophone set specified -- neither for voice 'my_voice' nor for locale 'lg'
	at marytts.modules.synthesis.Voice.init(Voice.java:207)
	at marytts.modules.synthesis.Voice.<init>(Voice.java:182)
	... 8 more
Caused by: marytts.exceptions.MaryConfigurationException: No such property: lg.allophoneset
	at marytts.util.MaryRuntimeUtils.needAllophoneSet(MaryRuntimeUtils.java:315)
	at marytts.modules.synthesis.Voice.init(Voice.java:205)
	... 9 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)
~/marytts/target/marytts-5.2-SNAPSHOT/bin$ `

What could be the problem?
Thanks

**Comment by seblemaguer** [comment]
you should put the jars of the language and the voice in the classpath

**Comment by Nandutu** [comment]
wonderful this worked. Thanks @seblemaguer

**Comment by JudeAshan98** [comment]
@seblemaguer @Nandutu  I also getting the same error but I tried the solution that you provided. Still not working.
