### ISSUE TITLE
HMMVoiceMakeVoice 	at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:189)

### ISSUE THREAD

**Issue by baaslaawe** [marytts/marytts#663]
[state-5_stream-5_mgc-105_lf0-3_str-15.prt.txt](https://github.com/marytts/marytts/files/665825/state-5_stream-5_mgc-105_lf0-3_str-15.prt.txt)
hello guys 
when i do HMMVoiceMakeVoice i got this error
please helpe

 me 

Training voice: my_voice
The following is general information about execution of training steps:
```
Step: Start preparing environments at Wed Dec 21 11:14:50 EAT 2016

Step: Start computing variance floors at Wed Dec 21 11:14:50 EAT 2016
java.lang.Exception: The component HMMVoiceMakeVoice produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.RuntimeException:  computation failed on file [/home/abdullahi/voice/somali/]!
Command line was: [/usr/bin/perl /home/abdullahi/voice/somali/hts/scripts/Training.pl /home/abdullahi/voice/somali/hts/scripts/Config.pm].
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.launchProcWithLogFile(HMMVoiceMakeVoice.java:189)
	at marytts.tools.voiceimport.HMMVoiceMakeVoice.compute(HMMVoiceMakeVoice.java:127)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)




**this is report

** 
baaska@linked-clone-of-ubuntu-linux-16--1-:~/voice/sources/marytts/target/marytts-builder-5.2/bin$ **/usr/bin/perl /home/baaska/voice/somali/hts/scripts/Training.pl /home/baaska/voice/somali/hts/scripts/Config.pm**

==============================================================
Start preparing environments at Wed Dec 21 11:17:16 EAT 2016
==============================================================


=================================================================
Start computing variance floors at Wed Dec 21 11:17:16 EAT 2016
=================================================================

/home/baaska/voice/soft/hts/bin/HCompV -A -C /home/baaska/voice/somali/hts/configs/trn.cnf -D -T 1 -S /home/baaska/voice/somali/hts/data/scp/train.scp -m -M /home/baaska/voice/somali/hts/models/qst001/ver1/cmp -o /home/baaska/voice/somali/hts/models/qst001/ver1/cmp/average.mmf /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt 

HTK Configuration Parameters[8]
  Module/Tool     Parameter                  Value
#                 MINDUR                         5
#                 MAXSTDDEVCOEF                 10
#                 APPLYDURVARFLOOR              TRUE
#                 DURVARFLOORPERCENTILE          1.000000
#                 VFLOORSCALESTR  Vector 5 0.01 0.01 0.01 0.01 0.01
#                 NATURALWRITEORDER              TRUE
#                 NATURALREADORDER              TRUE
#                 APPLYVFLOOR                 TRUE

HMM Def Error: GetToken: Unknown symbol MSDINFO at line 1/col 41/char 40 in /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
  ERROR [+7050]  HMError:
HMM Def Error: GetOption: GetToken failed at line 1/col 42/char 41 in /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
  ERROR [+7050]  HMError:
HMM Def Error: GetOptions: GetOption failed at line 1/col 43/char 42 in /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
  ERROR [+7050]  HMError:
HMM Def Error: LoadHMMSet: GetOptions failed at line 1/col 0/char -1 in /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
  ERROR [+7050]  HMError:
  ERROR [+2028]  Initialise: LoadHMMSet failed
 FATAL ERROR - Terminating program /home/baaska/voice/soft/hts/bin/HCompV
Error in /home/baaska/voice/soft/hts/bin/HCompV    -A    -C /home/baaska/voice/somali/hts/configs/trn.cnf -D -T 1 -S /home/baaska/voice/somali/hts/data/scp/train.scp -m  -M /home/baaska/voice/somali/hts/models/qst001/ver1/cmp -o /home/baaska/voice/somali/hts/models/qst001/ver1/cmp/average.mmf /home/baaska/voice/somali/hts/proto/qst001/ver1/state-5_stream-5_mgc-105_lf0-3_str-15.prt
baaska@linked-clone-of-ubuntu-linux-16--1-:~/voice/sources/marytts/target/marytts-builder-5.2/bin$ 
```

**Comment by nshmyrev** [comment]
You didn't compile HTS properly (didn't properly apply HTS patch)

http://hts.sp.nitech.ac.jp/hts-users/spool/2008/msg00572.html

**Comment by baaslaawe** [comment]
thank you @nshmyrev 
but last time i was test to finish english CMU_ARCTIC , but i didn't get like that error 

can i know is there problem come from X-sampa i use  special symbol  like d~ 

please help me

**Comment by nshmyrev** [comment]
~ symbols also have special meaning for HTK, I would not use them.
