### ISSUE TITLE
MCEPMaker fails on unexpected input files

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#68]
Building a voice from wav files where some random ones use [Broadcast Wave Format (BWF)](http://www.ebu.ch/fr/technical/publications/userguides/bwf_user_guide.php) for metadata encoding. Using 4.x, this is what happens:

```
fnord0018
fnord0019
fnord0020
Cannot recognize file format or cannot access file: "/path/to/fnord0020.wav"
java.lang.Exception: The component MCEPMaker produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
Caused by: java.lang.RuntimeException: Mel-Cepstrum  computation failed on file [fnord0020]!
Command line was: [/path/to/speech_tools/bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /path/to/user.dir/pm/fnord0020.pm -o /path/to/user.dir/mcep/fnord0020.mcep /path/to/user.dir/wav/fnord0020.wav].
	at marytts.tools.voiceimport.General.launchProc(General.java:532)
	at marytts.tools.voiceimport.ESTCaller.make_mcep(ESTCaller.java:275)
	at marytts.tools.voiceimport.MCEPMaker.compute(MCEPMaker.java:257)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:291)
```
The actual error returned by invoking that command line is gobbled, but running the command line manually does this:
```
$ /path/to/speech_tools/bin/sig2fv -window_type hamming -factor 2.5 -otype est_binary -coefs melcep -melcep_order 12 -fbank_order 24 -shift 0.01 -preemph 0.97 -pm /path/to/user.dir/pm/fnord0020.pm -o /path/to/user.dir/mcep/fnord0020.mcep /path/to/user.dir/wav/fnord0020.wav
Cannot recognize file format or cannot access file: "/path/to/user.dir/wav/fnord0020.wav"
```
So it appears that `sig2fv` from the Edinburgh Speech Tools cannot cope with certain files. The audio format is identical to that of the previous file, which worked as expected:
```
$ soxi fnord0019.wav fnord0020.wav

Input File     : 'fnord0019.wav'
Channels       : 1
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:02.47 = 109028 samples = 185.422 CDDA sectors
File Size      : 222k
Bit Rate       : 719k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : 'fnord0020.wav'
Channels       : 1
Sample Rate    : 44100
Precision      : 16-bit
Duration       : 00:00:03.25 = 143438 samples = 243.942 CDDA sectors
File Size      : 289k
Bit Rate       : 711k
Sample Encoding: 16-bit Signed Integer PCM

Total Duration of 2 files: 00:00:05.72
```
However, inspection of the header reveals that `fnord0019.wav` uses the standard `WAVEfmt` chunk in the header, while `fnord0020.wav` has `WAVEbext`, i.e., uses the Broadcast Wave extension.

This is essentially an EST bug (I'm using speech_tools 2.1, compiled on OSX 10.6.8), but MCEPMaker should either gracefully handle this Exception, or at the very least, provide some useful indication why processing failed.

**Comment by seblemaguer** [comment]
I think if this exception happen again, the architecture will be different so a new issue can be open
