### ISSUE TITLE
voice-dfki-prudence-5.2 jar file error

### ISSUE THREAD

**Issue by baveen** [marytts/marytts#688]
I am using MaryTTS 5.2 in eclipse. I downloaded  "voice-dfki-prudence-5.2" from the component installer. When I add this jar file to my project and run the project with this voice cause me error in starting the Mary Server. I don't know how to solve this issue. Is there any proper way to add jar file to a project?. How can I solve this issue

**Comment by psibre** [comment]
We can only help you if you provide details about the error.

**Comment by baveen** [comment]
I got the following error, 
`Feb 16, 2017 2:41:02 PM model.TextToSpeech <init>
SEVERE: null
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at model.TextToSpeech.<init>(TextToSpeech.java:27)
	at model.MainGUI$1.actionPerformed(MainGUI.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.Exception: Problem starting module Synthesis
	at marytts.server.Mary.startModules(Mary.java:151)
	at marytts.server.Mary.startup(Mary.java:297)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 38 more
Caused by: marytts.exceptions.MaryConfigurationException: Cannot build unit selection voice 'dfki-prudence'
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:218)
	at marytts.unitselection.UnitSelectionSynthesizer.startup(UnitSelectionSynthesizer.java:94)
	at marytts.modules.Synthesis.startupSynthesizers(Synthesis.java:73)
	at marytts.modules.Synthesis.startup(Synthesis.java:65)
	at marytts.server.Mary.startModules(Mary.java:149)
	... 42 more
Caused by: marytts.exceptions.NoSuchPropertyException: Cannot read file `.\lib\voices\dfki-prudence\halfphoneFeatures_ac.mry'. Check property `voice.dfki-prudence.featureFile' in configuration files
	at marytts.server.MaryProperties.needFilename(MaryProperties.java:389)
	at marytts.unitselection.UnitSelectionVoice.<init>(UnitSelectionVoice.java:107)
	... 46 more

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at model.TextToSpeech.setVoice(TextToSpeech.java:49)
	at model.MainGUI$1.actionPerformed(MainGUI.java:57)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
`

**Comment by seblemaguer** [comment]
According to this line

```Caused by: marytts.exceptions.NoSuchPropertyException: Cannot read file `.\lib\voices\dfki-prudence\halfphoneFeatures_ac.mry'. Check property `voice.dfki-prudence.featureFile' in configuration files```

it seems that you are missing a file. For which reason I don't know but did you check that this file exists ?

**Comment by psibre** [comment]
Please have a look at the [Eclipse documentation on the wiki](../wiki/Eclipse_5.X#running-or-debugging-the-marytts-server) and confirm that you have configured the `mary.base` property correctly.

**Comment by baveen** [comment]
Yeah I have read the documentation. I don't know how o set the property. I downloaded the Mary 5.1.2 zip file and I installed voices using marytts-component-installer.bat file and added the jar files to my project directly. Here, I didn't find any base file. I am new to Mary platform. Please help me to solve this.

**Comment by seblemaguer** [comment]
it is not a file it is a variable as said in the wiki page  indicated by @psibre : 
``` -Dmary.base="${workspace_loc:marytts}/target/marytts-VERSION"```
you should define this variable to point to the directory which contains ```lib/voices/....```

**Comment by baveen** [comment]
So,  if I have a path like "C:/MaryTTS/marytts/lib/voices", then I can set the VM arguments - Dmary.base="${C:/MaryTTS/marytts/lib/voices}/target/marytts-5.1.2"?. Is it correct?.

**Comment by seblemaguer** [comment]
can I/you close this issue ?

**Comment by baveen** [comment]
Yes. Sure.
