### ISSUE TITLE
marytts.exceptions.MaryConfigurationException: Cannot start MARY server

### ISSUE THREAD

**Issue by jonyt** [marytts/marytts#690]
I wrote an application that uses MaryTTS. It works fine from IntelliJ but when I package it into a jar and run it I get:
```
Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at org.deadio.tts.MaryTTS.<init>(MaryTTS.java:22)
	at org.deadio.Main.main(Main.java:27)
Caused by: java.lang.NullPointerException
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:70)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 2 more
```

Apparently this is due to `MainConfig.java` not being loaded (although `VoiceConfig.java` is loaded). Any ideas on how to solve this?

**Comment by psibre** [comment]
Did you merge the service loaders? If not, e.g. [this comment](673#issuecomment-280449765) might help.

**Comment by jonyt** [comment]
Not 100% sure I understood you correctly, but if I did then it didn't work. Here's what I have:

```
<build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                </plugin>
                <plugin>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>2.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.deadio.Main</mainClass>
                                </transformer>
                            </transformers>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

**Comment by psibre** [comment]
That POM snippet looks OK, but you can verify that the service loaders were successfully merged by running the equivalent of
```
$ unzip -c target/txt2wav-1.0-SNAPSHOT.jar META-INF/services/marytts.config.MaryConfig
Archive:  target/txt2wav-1.0-SNAPSHOT.jar
  inflating: META-INF/services/marytts.config.MaryConfig  
marytts.voice.CmuSltHsmm.Config
marytts.config.MainConfig
marytts.language.en.EnglishConfig
```

Meanwhile, could you please check the DEBUG level log output from MaryTTS? That would provide further details on the NPE at startup.

**Comment by jonyt** [comment]
I guess not:

```
unzip -c target/sound-1.0-SNAPSHOT-jar-with-dependencies.jar META-INF/services/marytts.config.MaryConfig
Archive:  target/sound-1.0-SNAPSHOT-jar-with-dependencies.jar
  inflating: META-INF/services/marytts.config.MaryConfig  
marytts.voice.CmuSltHsmm.Config
```

**Comment by psibre** [comment]
Are you sure the shade plugin is being executed? How are you invoking `mvn`?

**Comment by jonyt** [comment]
Pretty sure. I see multiple `Including ... in the shaded jar` during `mvn package`.

**Comment by psibre** [comment]
Hmm... could you push your repo to GitHub, then I can take a direct look at what might be going on...

**Comment by jonyt** [comment]
Done: https://github.com/jonyt/deadio

**Comment by psibre** [comment]
Following the solution of jonyt/deadio#1 and running `mvn package`, I see
```
$ unzip -c target/sound-1.0-SNAPSHOT.jar META-INF/services/marytts.config.MaryConfig
Archive:  target/sound-1.0-SNAPSHOT.jar
  inflating: META-INF/services/marytts.config.MaryConfig  
marytts.voice.CmuSltHsmm.Config
marytts.config.MainConfig
marytts.language.en.EnglishConfig
```
So that's working now.

**Comment by jonyt** [comment]
Wow. That's super strange. Thanks a lot for taking the time to help! Much appreciated.
