### ISSUE TITLE
Using multithreading to synthesize emotionml speech gives error

### ISSUE THREAD

**Issue by murtraja** [marytts/marytts#716]
I am spawning multiple threads (7) to fetch voice data from a running instance of MaryTTS server. Interestingly, first 5 threads, got the data but the next two gave the following errors:

status_code = 500
BAD REQUEST given by url u'http://localhost:59125/process?LOCALE=en_US&INPUT_TYPE=EMOTIONML&AUDIO=WAVE_FILE&INPUT_TEXT=%3Cemotionml+category-set%3D%22http%3A%2F%2Fwww.w3.org%2FTR%2Femotion-voc%2Fxml%23big6%22+version%3D%221.0%22+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2009%2F10%2Femotionml%22%3EI+don%27t+have+anything+to+do.%3C%2Femotionml%3E&OUTPUT_TYPE=AUDIO'
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module EmotionmlParser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:290)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: emotionml.exceptions.NotValidEmotionmlException: Cannot get vocabulary definition from http://www.w3.org/TR/emotion-voc/xml#big6
	at emotionml.Checker.validateVocabularySets(Checker.java:184)
	at emotionml.Checker.validateStandaloneManually(Checker.java:80)
	at emotionml.Checker.validate(Checker.java:64)
	at marytts.modules.EmotionmlParser.process(EmotionmlParser.java:88)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more
Caused by: emotionml.exceptions.NoSuchVocabularyException: Cannot parse vocabulary definition
	at emotionml.EmotionVocabulary.parseVocabularyDocument(EmotionVocabulary.java:157)
	at emotionml.EmotionVocabulary.getVocabularyDOM(EmotionVocabulary.java:129)
	at emotionml.EmotionVocabulary.<init>(EmotionVocabulary.java:75)
	at emotionml.EmotionVocabulary.get(EmotionVocabulary.java:53)
	at emotionml.Checker.validateVocabularySets(Checker.java:181)
	... 23 more
Caused by: org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:271)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at emotionml.EmotionVocabulary.parseVocabularyDocument(EmotionVocabulary.java:152)
	... 27 more
</pre></body></html>
Exception in thread Thread-7:

status_code = 500
BAD REQUEST given by url u'http://localhost:59125/process?LOCALE=en_US&INPUT_TYPE=EMOTIONML&AUDIO=WAVE_FILE&INPUT_TEXT=%3Cemotionml+category-set%3D%22http%3A%2F%2Fwww.w3.org%2FTR%2Femotion-voc%2Fxml%23big6%22+version%3D%221.0%22+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2009%2F10%2Femotionml%22%3EUgh%21%3C%2Femotionml%3E&OUTPUT_TYPE=AUDIO'
<html><body><h1>Internal server error</h1><p>Processing failed.<pre>java.lang.Exception: Module EmotionmlParser: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:290)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
Caused by: emotionml.exceptions.NotValidEmotionmlException: Cannot get vocabulary definition from http://www.w3.org/TR/emotion-voc/xml#big6
	at emotionml.Checker.validateVocabularySets(Checker.java:184)
	at emotionml.Checker.validateStandaloneManually(Checker.java:80)
	at emotionml.Checker.validate(Checker.java:64)
	at marytts.modules.EmotionmlParser.process(EmotionmlParser.java:88)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more
Caused by: emotionml.exceptions.NoSuchVocabularyException: Cannot parse vocabulary definition
	at emotionml.EmotionVocabulary.parseVocabularyDocument(EmotionVocabulary.java:157)
	at emotionml.EmotionVocabulary.getVocabularyDOM(EmotionVocabulary.java:129)
	at emotionml.EmotionVocabulary.<init>(EmotionVocabulary.java:75)
	at emotionml.EmotionVocabulary.get(EmotionVocabulary.java:53)
	at emotionml.Checker.validateVocabularySets(Checker.java:181)
	... 23 more
Caused by: java.lang.NullPointerException
	at com.sun.org.apache.xerces.internal.parsers.AbstractDOMParser.ignorableWhitespace(AbstractDOMParser.java:1274)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.ignorableWhitespace(XMLSchemaValidator.java:835)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.characters(XMLSchemaValidator.java:797)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:454)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at emotionml.EmotionVocabulary.parseVocabularyDocument(EmotionVocabulary.java:152)
	... 27 more
</pre></body></html>

Exception in thread Thread-6:

And this happens randomly. If i run these threads 10 times, everything works perfectly 2 out of 10 times. Please suggest a solution to this problem.

I am contemplating of running multiple instances of MaryTTS on different ports and firing requests on them simultaneously instead of firing requests on one MaryTTS server.

**Comment by psibre** [comment]
> containers, each with an isolated JVM.

Incidentally, I recently made [a simple example Dockerfile](/psibre/marytts-dockerfiles/blob/master/marytts/Dockerfile) which could easily be used for this purpose.

**Comment by murtraja** [comment]
Thank you very much!
