### ISSUE TITLE
Fail on training LTS

### ISSUE THREAD

**Issue by trangntt** [marytts/marytts#72]
I met the following exception when try to training for Vietnamese language. Thanks in advanced for answer this issue.

java.lang.RuntimeException: couldn't train decisiontree using weka: 
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:240)
	at marytts.tools.transcription.TranscriptionTable.trainLTS(TranscriptionTable.java:175)
	at marytts.tools.transcription.TranscriptionTable.saveTranscription(TranscriptionTable.java:259)
	at marytts.tools.transcription.TranscriptionGUI.saveToFileActionPerformed(TranscriptionGUI.java:598)
	at marytts.tools.transcription.TranscriptionGUI.access$11(TranscriptionGUI.java:592)
	at marytts.tools.transcription.TranscriptionGUI$11.actionPerformed(TranscriptionGUI.java:453)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:337)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:778)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1645)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2851)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:670)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:678)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:649)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:267)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:254)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2928)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2920)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2814)
	at javax.swing.JComboBox.processKeyEvent(JComboBox.java:1397)
	at java.awt.Component.processEvent(Component.java:6152)
	at java.awt.Container.processEvent(Container.java:2083)
	at java.awt.Component.dispatchEventImpl(Component.java:4737)
	at java.awt.Container.dispatchEventImpl(Container.java:2141)
	at java.awt.Component.dispatchEvent(Component.java:4565)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1836)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:712)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:990)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:855)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:676)
	at java.awt.Component.dispatchEventImpl(Component.java:4609)
	at java.awt.Container.dispatchEventImpl(Container.java:2141)
	at java.awt.Window.dispatchEventImpl(Window.java:2482)
	at java.awt.Component.dispatchEvent(Component.java:4565)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:684)
	at java.awt.EventQueue.access$000(EventQueue.java:85)
	at java.awt.EventQueue$1.run(EventQueue.java:643)
	at java.awt.EventQueue$1.run(EventQueue.java:641)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
	at java.awt.EventQueue$2.run(EventQueue.java:657)
	at java.awt.EventQueue$2.run(EventQueue.java:655)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:654)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: weka.core.UnsupportedAttributeTypeException: weka.classifiers.trees.j48.C45PruneableClassifierTreeWithUnary: Cannot handle multi-valued nominal class!
	at weka.core.Capabilities.test(Capabilities.java:940)
	at weka.core.Capabilities.test(Capabilities.java:1109)
	at weka.core.Capabilities.test(Capabilities.java:1022)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1301)
	at weka.classifiers.trees.j48.C45PruneableClassifierTree.buildClassifier(C45PruneableClassifierTree.java:120)
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:233)
	... 56 more

**Comment by Munzey** [comment]
closing for inactivity

**Comment by BibekBazaz** [comment]
@ftesser  hello , did you solve the above problem? If yes please tell me how. I am building a tts for HINDI language and finding the same exception.

**Comment by ftesser** [comment]
@BibekBazaz: I was not able to work into this issue because I was not able to reprocude the error.
I can try to work on it If you share  your allophones.xml and a minimal set of your lexicon, so I can try to reproduce the problem.

**Comment by BibekBazaz** [comment]
i did solve the problem by following instructions given by another user.
However , thanks for replying.

**Comment by ZellNguyen** [comment]
@BibekBazaz: Hello, could you please tell me the solution for the problem? I found the same one.

**Comment by BibekBazaz** [comment]
Use a different version of mary and transcribe using that. Once
transcription is done bring back the output files and continue working with
the version you want to.
That worked in my case.
