### ISSUE TITLE
Build failed with complaining about en_US_lexicon.fst resource missing

### ISSUE THREAD

**Issue by idoor88** [marytts/marytts#730]
Hi, I downloaded the source code and did a mvn package build, the build failed with this exception:

```
ests run: 43, Failures: 1, Errors: 0, Skipped: 42, Time elapsed: 0.633 sec <<< FAILURE! - in TestSuite
setUpBeforeClass(marytts.language.en.PreprocessTest)  Time elapsed: 0.463 sec  <<< FAILURE!
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.language.en.PreprocessTest.setUpBeforeClass(PreprocessTest.java:38)
Caused by: marytts.exceptions.MaryConfigurationException: Cannot instantiate object from 'marytts.modules.JPhonemiser(en_US.)': For property 'en_US.lexicon', no classpath resource available at '/marytts/language/en_US/lexicon/en_US_lexicon.fst'
	at marytts.language.en.PreprocessTest.setUpBeforeClass(PreprocessTest.java:38)
Caused by: java.lang.reflect.InvocationTargetException
	at marytts.language.en.PreprocessTest.setUpBeforeClass(PreprocessTest.java:38)
Caused by: marytts.exceptions.MaryConfigurationException: For property 'en_US.lexicon', no classpath resource available at '/marytts/language/en_US/lexicon/en_US_lexicon.fst'
	at marytts.language.en.PreprocessTest.setUpBeforeClass(PreprocessTest.java:38)

Exception in thread "Thread-2" java.lang.IllegalStateException: MARY system is not running
	at marytts.server.Mary.shutdown(Mary.java:371)
	at marytts.server.Mary$2.run(Mary.java:290)

Results :

Failed tests: 
  PreprocessTest.setUpBeforeClass:38 » MaryConfiguration Cannot start MARY serve...
```

**Comment by psibre** [comment]
Has this been solved? If not, could you please paste the output of `git status` and `git describe`?

**Comment by tarasfrompir** [comment]
marytts-common/target/
	marytts-languages/marytts-lang-de/target/
	marytts-languages/marytts-lang-en/src/main/resources/marytts/language/en_US/lexicon/
	marytts-languages/marytts-lang-en/target/
	marytts-runtime/target/
	marytts-signalproc/target/
	target/

**Comment by psibre** [comment]
MaryTTS is not using Maven anymore in the master branch.
Please run `./gradlew clean build` and see the [README](../blob/8ffb91313868d21d3e99eef2e4643759a6e73de6/README.md) for details.
