### ISSUE TITLE
Problem starting module EmotionmlParser. Cannot convert data-type 'void' to 'boolean'.

### ISSUE THREAD

**Issue by akprats33** [marytts/marytts#740]
This works fine when I import the jars directly, but when I add dependencies using the artifact, I get error during parsing `Emotionml Parser`. Following is the stacktrace -

```
WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
ERROR:  'The first argument to the non-static Java function 'expressedThrough' is not a valid object reference.'
FATAL ERROR:  'Cannot convert data-type 'void' to 'boolean'.'
           :Cannot convert data-type 'void' to 'boolean'.

marytts.exceptions.MaryConfigurationException: Cannot start MARY server
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
        at tts.Synthesizer.<init>(Synthesizer.java:30)
        at tts.Synthesizer$$FastClassByGuice$$4b6741ed.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
Caused by: java.lang.Exception: Problem starting module EmotionmlParser
        at marytts.server.Mary.startModules(Mary.java:151)
        at marytts.server.Mary.startup(Mary.java:297)
        at marytts.server.Mary.startup(Mary.java:204)
        at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
        at tts.Synthesizer.<init>(Synthesizer.java:30)
        at tts.Synthesizer$$FastClassByGuice$$4b6741ed.newInstance(<generated>)

        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
Caused by: javax.xml.transform.TransformerConfigurationException: Cannot convert data-type 'void' to 'boolean'.
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
        at marytts.modules.EmotionmlParser.startup(EmotionmlParser.java:72)
        at marytts.server.Mary.startModules(Mary.java:149)
        at marytts.server.Mary.startup(Mary.java:297)
        at marytts.server.Mary.startup(Mary.java:204)
        at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
        at tts.Synthesizer.<init>(Synthesizer.java:30)
        at tts.Synthesizer$$FastClassByGuice$$4b6741ed.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
Caused by: com.sun.org.apache.xalan.internal.xsltc.compiler.util.TypeCheckError: Cannot convert data-type 'void' to 'boolean'.
        at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.typeCheck(CastExpr.java:190)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.CastExpr.<init>(CastExpr.java:145)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.LogicalExpr.typeCheck(LogicalExpr.java:148)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Predicate.typeCheck(Predicate.java:286)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.StepPattern.typeCheck(StepPattern.java:197)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.typeCheck(Template.java:291)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.typeCheckContents(SyntaxTreeNode.java:487)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.typeCheck(Stylesheet.java:653)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:412)
        at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:483)

```

`build.sbt`

```
name := """play-java"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.11"

libraryDependencies += cache
libraryDependencies += javaWs

resolvers += "Bintray Jcenter" at "https://jcenter.bintray.com"

libraryDependencies ++= Seq(
  "de.dfki.mary" % "voice-cmu-slt-hsmm" % "5.2"
)

```

**Comment by psibre** [comment]
I can't help but notice that the warnings refer to classes that are misinterpreted as (invalid) URLs, which are then converted to invalid properties.
My guess is that Scala is using a different, incompatible TransformerFactory implementation.

**Comment by akprats33** [comment]
Thanks for the suggestion. The problem was in the xslt processor. I changed the processor and it worked. I used the following processor -

```
libraryDependencies += "net.sf.saxon" % "Saxon-HE" % "9.7.0-18"
```
