### ISSUE TITLE
problem during HTKLabeler execution

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#750]
following exception is shown during execution of HTKLabeler of Database import

java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+3031]  ProcessBoBiGram: Word ŋ in LM not in WordList
	at marytts.tools.voiceimport.HTKLabeler.htkExtraModels(HTKLabeler.java:1393)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:255)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)

Please help

**Comment by psibre** [comment]
I'm afraid the HTKLabeler is not maintained. In any case, this error is caused by an HTK problem, so you should check elsewhere for possible solutions.

**Comment by jayanta1122** [comment]
ok thank you for reply

**Comment by guliashvili** [comment]
@jayanta1122 
hello,
Could you solve this problem? I face to the same problem for my language.

**Comment by jayanta1122** [comment]
Hiii,

I used EHMM Labeler as an alternative
