### ISSUE TITLE
TranscriptionAligner is not working

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#754]
I found the following error while running TranscriptionAligner of Voiceimport

root@jayantasPC:/local/mary/marytts2/target/marytts-builder-5.1.2/bin# ./voiceimport.sh 
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

Opening GUI....... 
Loading database layout:
Reading config file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/database.config
Loading basename list from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/basenames.lst
Found 663 files in basename list
traversing through 663 files
s0001
/local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/lab/s0001.lab
Orig   : -|a|d|j|ɒ|-
Correct: _|a|d|j|ɒ|_
Alignments:  # _ a # d # j # ɒ _ # 
Boundary, align =  
  deleted boundary from xml
Ph = a, align =  _ a 
Ph = d, align =  d 
Ph = j, align =  j 
Ph = ɒ, align =  ɒ _ 
Boundary, align =  
  deleted boundary from xml
java.lang.Exception: The component TranscriptionAligner produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: marytts.exceptions.InvalidDataException: Allophone `' could not be found in AllophoneSet `assamese' (Locale: as)
	at marytts.tools.analysis.MaryTranscriptionAligner.alignXmlTranscriptions(MaryTranscriptionAligner.java:99)
	at marytts.tools.voiceimport.TranscriptionAligner.alignTranscription(TranscriptionAligner.java:152)
	at marytts.tools.voiceimport.TranscriptionAligner.compute(TranscriptionAligner.java:122)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)

please help

**Comment by psibre** [comment]
Please use v5.2.

**Comment by wittamer123** [comment]
I have the same problem, and I use v5.2.
The error is 


java.lang.Exception: The component TranscriptionAligner produced the following exception: 
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.InvalidDataException: Allophone `dh' could not be found in AllophoneSet `sampa' (Locale: en_US)
    at marytts.tools.analysis.MaryTranscriptionAligner.alignXmlTranscriptions(MaryTranscriptionAligner.java:99)
    at marytts.tools.voiceimport.TranscriptionAligner.alignTranscription(TranscriptionAligner.java:152)
    at marytts.tools.voiceimport.TranscriptionAligner.compute(TranscriptionAligner.java:122)
    at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)

Could you help me?

**Comment by psibre** [comment]
>`Allophone dh' could not be found in AllophoneSetsampa' (Locale: en_US)`

Where does this `dh'` come from?

**Comment by doaaobiedat** [comment]
i have the same error 

Computing unit labels for 360 files.
From phonetic label files: /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/trial3/lab/*.lab
To       unit label files: /media/hiyassat/Data/Training_EqraFemale1Voice/training_all/trial3/phonelab*.lab
Finished computing unit labels
traversing through 360 files
s-1
/media/hiyassat/Data/Training_EqraFemale1Voice/training_all/trial3/lab/s-1.lab
Orig   : _|o|a|b|q|a|r|i|j|t|u|_|A|l|sˤ|d|i|j|q|_
Correct: _|o|a|b|q|a|r|i|j|t|u|A|l|sˤ|d|i|j|q|_
Alignments:  _ # o # a # b # q # a # r # i # j # t # u # # A # l # sˤ # d # i # j # q # _ 
Boundary, align =  _ 
Ph = o, align =  o 
Ph = a, align =  a 
Ph = b, align =  b 
Ph = q, align =  q 
Ph = a, align =  a 
Ph = r, align =  r 
Ph = i, align =  i 
Ph = j, align =  j 
Ph = t, align =  t 
Ph = u, align =  u 
Ph = A, align =  A 
Ph = l, align =  l 
Ph = sˤ, align =  sˤ 
Ph = d, align =  d 
Ph = i, align =  i 
Ph = j, align =  j 
Ph = q, align =  q 
Boundary, align =  _ 
java.lang.Exception: The component TranscriptionAligner produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:297)
Caused by: marytts.exceptions.InvalidDataException: Label "A" not found in AllophoneSet for Locale ar
	at marytts.tools.analysis.MaryTranscriptionAligner.alignXmlTranscriptions(MaryTranscriptionAligner.java:95)
	at marytts.tools.voiceimport.TranscriptionAligner.alignTranscription(TranscriptionAligner.java:164)
	at marytts.tools.voiceimport.TranscriptionAligner.compute(TranscriptionAligner.java:133)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:294)
