### ISSUE TITLE
problem in phoneUnitFeatureComputer

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#760]
Following error is found while running phoneUnitFeatureComputer

root@jayantasPC:/local/mary/marytts2/target/marytts-builder-5.1.2/bin# ./voiceimport.sh 
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK Server VM (build 25.66-b01, mixed mode)

Opening GUI....... 
Loading database layout:
Reading config file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/database.config
Loading basename list from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/basenames.lst
Found 663 files in basename list
Loading features from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/mary/features.txt
Loading features from file /local/mary/marytts2/target/marytts-builder-5.1.2/bin/voice/mary/features.txt
Computing unit features for 663 files
Mary TTS client 5.1.2 (impl. unknown)
Connected to localhost:59125, Mary TTS server 5.1.2 (impl. unknown)
java.lang.Exception: The component PhoneUnitFeatureComputer produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: java.io.IOException: Error message from server:
<html><body><h1>Internal server error</h1><p>Problem reading input<pre>org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at marytts.util.dom.DomUtils.parseDocument(DomUtils.java:142)
	at marytts.util.dom.DomUtils.parseDocument(DomUtils.java:121)
	at marytts.datatypes.MaryData.setData(MaryData.java:221)
	at marytts.server.Request.setInputData(Request.java:245)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:220)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:745)
</pre></body></html>
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:397)
	at marytts.client.http.MaryHttpClient._process(MaryHttpClient.java:439)
	at marytts.client.MaryClient.process(MaryClient.java:653)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.computeFeaturesFor(PhoneUnitFeatureComputer.java:180)
	at marytts.tools.voiceimport.PhoneUnitFeatureComputer.compute(PhoneUnitFeatureComputer.java:166)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:59125/process
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at marytts.client.http.MaryHttpClient.requestInputStream(MaryHttpClient.java:388)
	... 5 more
plz help

**Comment by psibre** [comment]
Please upgrade to v5.2, which may solve the issue.

**Comment by jayanta1122** [comment]
ok thanks

**Comment by psibre** [comment]
Did the upgrade solve the issue? If not, please feel free to reopen it!
