### ISSUE TITLE
Problem in DurationCARTTrainer

### ISSUE THREAD

**Issue by jayanta1122** [marytts/marytts#761]
I found following error while running DurationCARTTrainer.plz help

Number of processed units: 9836
Can read right number of units
Duration CART trainer: exporting duration features
java.lang.Exception: The component DurationCARTTrainer produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:280)
Caused by: java.lang.IndexOutOfBoundsException: Byte value out of range: 34
	at marytts.util.string.ByteStringTranslator.get(ByteStringTranslator.java:155)
	at marytts.features.FeatureDefinition.getFeatureValueAsString(FeatureDefinition.java:1007)
	at marytts.features.FeatureDefinition.toFeatureString(FeatureDefinition.java:1474)
	at marytts.tools.voiceimport.DurationCARTTrainer.compute(DurationCARTTrainer.java:140)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)

**Comment by psibre** [comment]
Without knowing the details, I would assume that the working state of your voicebuilding project has become "corrupted" by changes to the data and non re-running all components in the expected order. I suggest you delete everything except the `wav`, `text`, and `lab` directories, and start over.

**Comment by jayanta1122** [comment]
ok thanks
