### ISSUE TITLE
transcription.sh problem

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#799]
transcription.sh has not generated *_pos.fst file. Am I doing something wrong?

in transcription.sh working directory, list of files are
```
ka$ ls
allophones.ka_GE.xml
done.txt
kawiki-latest-pages-articles-backup-201709012055.xml.bz2
kawiki-latest-pages-articles.xml
log
wikilist.txt
wkdb.conf
wkdb_download_timestamp.txt
wordlist-freq.txt
words_lexicon.dict
words_lexicon.fst
words.lts
words.txt
xml_splits
```

**Comment by psibre** [comment]
Extra tags (historically, part-of-speech, but actually just any "functional" tag) can be be added to the lexicon, but are used *only* for homograph disambiguation. If your lexicon resource has no functional tags, then [no `*_pos.fst` is created](../blob/master/marytts-transcription/src/main/java/marytts/tools/transcription/LTSLexiconPOSBuilder.java#L224-L230).

**Comment by guliashvili** [comment]
@psibre 
In adding new language support tutorial ( https://github.com/marytts/marytts/wiki/New-Language-Support ), they ask for *_pos.fst . Is it okay if I just omit this part?

**Comment by psibre** [comment]
Yes.

**Comment by guliashvili** [comment]
@psibre Could you please give me your contact information, so that we can communicate more efficiently?

**Comment by neouyghur** [comment]
@psibre, however, I encountered the following the problem 
```
MARY server 6.0-SNAPSHOT starting as an HTTP server...Exception in thread "main" java.lang.Exception: Problem starting module OpenNLPPosTagger
        at marytts.server.Mary.startModules(Mary.java:151)
        at marytts.server.Mary.startup(Mary.java:294)
        at marytts.server.Mary.startup(Mary.java:204)
        at marytts.server.Mary.main(Mary.java:510)
Caused by: marytts.exceptions.MaryConfigurationException: For property 'ug.partsofspeech.fst', no classpath resource available at '/marytts/language/ug/tagger/ug_pos.fst'
        at marytts.server.MaryProperties.getStream(MaryProperties.java:436)
        at marytts.modules.MinimalisticPosTagger.startup(MinimalisticPosTagger.java:69)
        at marytts.server.Mary.startModules(Mary.java:149)
        ... 3 more
Exception in thread "Thread-1" java.lang.IllegalStateException: MARY system is not running
        at marytts.server.Mary.shutdown(Mary.java:368)
        at marytts.server.Mary$3.run(Mary.java:287)
:run FAILED
```
Then I copy the tr_pos.fst as ug_pos.fst, the problem is solved. But could you tell me how I can avoid this problem? And can you give us a part of speech example? Thanks.

**Comment by psibre** [comment]
@neouyghur If you define config properties which trigger loading of classpath resources that don't exist, this is inevitable. Please open a new issue (potentially with references to older relevant issues), instead of continuing the discussion on old, closed issues.
