### ISSUE TITLE
wkdb_featuremaker problem

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#803]
Hi,
I'm trying to develop text to speech for Georgian language and I'm going through this tutorial https://github.com/marytts/marytts/wiki/New-Language-Support .

However when I run (It's 5.x branch)

./wkdb_featuremaker.sh wkdb.conf
I get this error

```
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=773
Processing(773) text id=774 text length=5856
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=774
Processing(774) text id=775 text length=5064
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=775
Processing(775) text id=776 text length=1905
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=776
Processing(776) text id=777 text length=1776
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=777
Processing(777) text id=778 text length=4663
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=778
Processing(778) text id=779 text length=2340
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=779
Processing(779) text id=780 text length=3341
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=780
Processing(780) text id=781 text length=1007
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=781
Processing(781) text id=782 text length=1865
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=782
Processing(782) text id=783 text length=2600
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=783
Processing(783) text id=784 text length=1018
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=784
Processing(784) text id=785 text length=3186
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=785
Processing(785) text id=786 text length=3051
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=786
Processing(786) text id=787 text length=3075
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=787
Processing(787) text id=788 text length=4007
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=788
Processing(788) text id=789 text length=3149
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=789
Processing(789) text id=790 text length=3724
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=790
Processing(790) text id=791 text length=3347
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=791
Processing(791) text id=792 text length=3351
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=792
Processing(792) text id=793 text length=3658
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=793
^CProcessing(793) text id=794 text length=3883
java.lang.UnsupportedOperationException: No known way of generating output (PHONEMES) from input(RAWMARYXML), no processing path through modules.
	at marytts.server.Request.processOneChunk(Request.java:524)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:518)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=794
Processing(794) text id=795 text length=1231
java.lang.IllegalStateException: MARY system is not running
	at marytts.tools.dbselection.FeatureMaker.phonemiseText(FeatureMaker.java:511)
	at marytts.tools.dbselection.FeatureMaker.splitIntoSentences(FeatureMaker.java:548)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:182)
PhonemiseText: problem processing text id=795
```

How should fix it?

**Comment by seblemaguer** [comment]
it says you don't have any phonemiser modules or any module going before the phonemiser for georgian in your classpath

**Comment by guliashvili** [comment]
@seblemaguer 
I copied and edited things from russian language.
It also has the phonemiser

Here is the folder structure
`~/marytts/marytts-languages$ tree marytts-lang-ka/
marytts-lang-ka/
├── lib
│   └── modules
│       └── ka
│           └── lexicon
│               ├── allophones.ka.xml
│               └── ka.txt
├── marytts-lang-ka.iml
├── pom.xml
├── src
│   ├── main
│   │   ├── java
│   │   │   └── marytts
│   │   │       └── language
│   │   │           └── ka
│   │   │               ├── kaConfig.java
│   │   │               ├── Phonemiser.java
│   │   │               └── Tokenizer.java
│   │   └── resources
│   │       ├── marytts
│   │       │   └── language
│   │       │       └── ka
│   │       │           ├── datatypes
│   │       │           │   └── TEXT.ka.example
│   │       │           ├── ka.config
│   │       │           ├── lexicon
│   │       │           │   ├── allophones.ka.xml
│   │       │           │   ├── ka_lexicon.fst
│   │       │           │   └── ka.lts
│   │       │           └── tagger
│   │       │               └── ka_pos.fst
│   │       └── META-INF
│   │           └── services
│   │               └── marytts.config.MaryConfig
│   └── test
│       └── java
│           └── marytts
│               └── language
│                   └── ka
│                       └── kaConfigTest.java
└── target
    ├── classes
    │   ├── marytts
    │   │   └── language
    │   │       └── ka
    │   │           ├── datatypes
    │   │           │   └── TEXT.ka.example
    │   │           ├── ka.config
    │   │           ├── kaConfig.class
    │   │           ├── lexicon
    │   │           │   ├── allophones.ka.xml
    │   │           │   ├── ka_lexicon.fst
    │   │           │   └── ka.lts
    │   │           ├── Phonemiser.class
    │   │           ├── tagger
    │   │           │   └── ka_pos.fst
    │   │           └── Tokenizer.class
    │   └── META-INF
    │       └── services
    │           └── marytts.config.MaryConfig
    ├── failsafe-reports
    │   └── failsafe-summary.xml
    ├── marytts-lang-ka-5.3-SNAPSHOT.jar
    ├── marytts-lang-ka-5.3-SNAPSHOT-sources.jar
    ├── maven-archiver
    │   └── pom.properties
    ├── maven-status
    │   └── maven-compiler-plugin
    │       ├── compile
    │       │   └── default-compile
    │       │       ├── createdFiles.lst
    │       │       └── inputFiles.lst
    │       └── testCompile
    │           └── default-testCompile
    │               ├── createdFiles.lst
    │               └── inputFiles.lst
    ├── surefire-reports
    │   ├── marytts.language.ka.kaConfigTest.txt
    │   └── TEST-marytts.language.ka.kaConfigTest.xml
    └── test-classes
        └── marytts
            └── language
                └── ka
                    └── kaConfigTest.class

47 directories, 36 files
`

And here is the config file

```
cat ka.config
##########################################################################
# Copyright (C) 2006 DFKI GmbH.
# All rights reserved. Use is subject to license terms.
#
# Permission is hereby granted, free of charge, to use and distribute
# this software and its documentation without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of this work, and to
# permit persons to whom this work is furnished to do so, subject to
# the following conditions:
# 
#  1. The code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Any modifications must be clearly marked as such.
#  3. Original authors' names are not deleted.
#  4. The authors' names are not used to endorse or promote products
#     derived from this software without specific prior written
#     permission.
# 
# DFKI GMBH AND THE CONTRIBUTORS TO THIS WORK DISCLAIM ALL WARRANTIES WITH 
# REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF 
# MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL DFKI GMBH NOR THE 
# CONTRIBUTORS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR 
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS 
# ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF 
# THIS SOFTWARE.
##########################################################################
# MARY TTS configuration file.
##########################################################################

name = ka
ka.version = 4.3.0

locale = ka


###########################################################################
############################## The Modules  ###############################
###########################################################################
# For keys ending in ".list", values will be appended across config files,
# so that .list keys can occur in several config files.
# For all other keys, values will be copied to the global config, so
# keys should be unique across config files.


# Java classes to use as the modules, as a whitespace-separated list.
# These have to implement de.dfki.lt.mary.modules.MaryModule.
# For each input type + output type, only one Module may be listed
# across all components, or an Exception will be thrown.
# No particular order is required -- a processing pipeline from input data type
# to output data type will be computed on-line.

modules.classes.list = \
	    marytts.language.ka.Tokenizer \
	    marytts.modules.DummyTokens2Words \
        marytts.modules.JPhonemiser(ka.) \
        marytts.modules.ProsodyGeneric \
        marytts.modules.MinimalisticPosTagger(ka,ka)
        marytts.modules.CARTDurationModeller(ka,ka.duration.,marytts.features.FeatureProcessorManager(ka)) \
        marytts.modules.CARTF0Modeller(ka,ka.f0.,marytts.features.FeatureProcessorManager(ka))

       
# marytts.modules.OpenNLPPosTagger(ru.pos)

####################################################################
####################### Module settings  ###########################
####################################################################

ka.allophoneset = jar:/marytts/language/ka/lexicon/allophones.ka.xml
ka.userdict = MARY_BASE/user-dictionaries/userdict-ka.txt
ka.lexicon = jar:/marytts/language/ka/lexicon/ka_lexicon.fst
ka.lettertosound = jar:/marytts/language/ka/lexicon/ka.lts

ka.partsofspeech.punctuation = ,.?!;
	
featuremanager.classes.list = \
	marytts.features.FeatureProcessorManager(ka)



```

**Comment by psibre** [comment]
I think it's best if you put your project on GitHub, similar to the other "standalone" marytts-lang-* projects we have.

**Comment by guliashvili** [comment]
@psibre  @seblemaguer 
thanks for suggestion.
Here is the project.
https://github.com/guliashvili/marytts-ka
I have no idea what is wrong with it :(

**Comment by guliashvili** [comment]
I had problems in allophones @nshmyrev helped me. thanks
