### ISSUE TITLE
EHMMLabeler

### ISSUE THREAD

**Issue by guliashvili** [marytts/marytts#807]
When I use 6 or more voice files to train the model on EHMMLabeler(during voice import).
It's not the problem of specific voice or transcirpt. I tried every possible 5 voice of this 6 voice and when I just leave 5 EHMMLabeler finishes successfully.

I get following exception
```

java.lang.Exception: The component EHMMLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException: baumWelchEHMM computation failed.
Error: null
	at marytts.tools.voiceimport.EHMMLabeler.baumWelchEHMM(EHMMLabeler.java:534)
	at marytts.tools.voiceimport.EHMMLabeler.compute(EHMMLabeler.java:205)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
Any ideas whats wrong?

**Comment by guliashvili** [comment]
@nshmyrev helped me. Transcript was not containing any colon, because of some bug some internal variable was initialized differently

**Comment by ziafkhan** [comment]
I understand its been a while since its been closed, but i have run into the same error. Could you please elaborate on the fix @guliashvili ?
