### ISSUE TITLE
 java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 149

### ISSUE THREAD

**Issue by Avinash01111992** [marytts/marytts#823]
Hi Now i'm into below step
Before that i tried all types of data type for 'rev_comment' like

```
blob
longblob
mediumblob
```

After changing the DBHandler.java with above data type changes still i'm facing the same issues  
```
2.2. Wikipedia Markup cleaning and mysql database creation
```
after running the below command 

```
avinash@lb:~/lb-work/text-to-speach-engine/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin$ ./wkdb_cleaning_up.sh /home/avinash/wiki_data/wkdb.conf
```

The error is pasted below 

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

WikipediaMarkupCleaner parameters:
  -mysqlHost localhost
  -mysqlUser root
  -mysqlPasswd ibc1-2
  -mysqlDB wiki
  -listFile wikilist.txt
  -minPage 10000
  -minText 1000
  -maxText 15000

Mysql driver loaded, set locale=ka
Mysql connection created successfully.
    TABLE = "ka_cleanText" does not exist, it will be created.
Mysql connection closed.

_______________________________________________________________________________

Processing xml file:xml_splits/page4.xml

Mysql driver loaded, set locale=ka
Creating connection to DB server...
Mysql connection created successfully.
Creating and loading TABLES: page, text and revision. (The loading can take a while...)

Mysql driver loaded, set locale=ka
Using mwdumper to convert xml file into sql source file and loading text, page and revision tables into the DB.
Creating connection to DB server...
Mysql connection created successfully.
Creating empty wikipedia tables: checking if tables text, page and revision already exist.
  Creating table: text
  Creating table: page
  Creating table: revision
Exception in thread "main" java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 149
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
	at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:257)
	at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1088)
	at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:444)
Caused by: org.xml.sax.SAXException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 149
	at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
	... 3 more
```

**Comment by Avinash01111992** [comment]
@seblemaguer  is there any solution for the above error

**Comment by psibre** [comment]
Please note that the marytts-builder code, especially the MySQL-related code, is no longer maintained.

Incidentally, which language are you targeting?

**Comment by Avinash01111992** [comment]
@psibre  i'm targeting for kannada language

**Comment by psibre** [comment]
In that case, have you looked at the existing resources provided by IITM at <https://www.iitm.ac.in/donlab/tts/>?

Note that Kannada has ISO 639-1 code `kn`, not `ka`.

**Comment by Avinash01111992** [comment]
@psibre  Hi i changed locale to kn and i did the steps from beginning again i'm facing the same issue as mentioned above . Now  how to to proceed further for adding a new language  if at at no longer MySQL is maintained ? what exactly it means ?

**Comment by psibre** [comment]
The only things the MySQL stuff is good for is
1. ranking words to (*manually*) transcribe into a lexicon resource, and
2. automatically selecting prompts to record.

If you can create your own lexicon resource, you can run the `gradle-marytts-lexicon-compiler` on it directly. But perhaps Kannada happens to have very simple pronunciation rules and you can just create a simple letter-to-sound converter class? This is how [marytts.language.te.phonemiser.TeluguLTS](../blob/d7b57e81d0e8e9abbd4f8be4ca66766ff700687c/marytts-languages/marytts-lang-te/src/main/java/marytts/language/te/phonemiser/TeluguLTS.java) functions.

Regarding the prompt list, if you already have a prompt list, or even pre-recorded utterances, then you can skip that, too.

**Comment by Avinash01111992** [comment]
@psibre  i'm very much new to all this , please just tell me that its possible to add new language  by executing the commands that you have given. I get struck-ed by executing below command 
**Wikipedia Markup cleaning and mysql database creation**
**$ wkdb_cleaning_up.sh wkdb.conf**

**Comment by psibre** [comment]
If you have a pronunciation lexicon or rules for Kannada, I can confirm that you can add it as a new language. If you have a pre-recorded speech data, or are using the data from IITM, building an actual TTS voice should be straightforward.

If you're using the legacy Wikipedia import tools and related code, you're on your own.

**Comment by Avinash01111992** [comment]
where do i get  **pronunciation lexicon** for kannada i just downloaded the and dumped using legacy Wikipedia using command and script that you'r provided.

**Comment by psibre** [comment]
No idea -- I've never worked with Kannada before. However, it turns out that it's one of the languages supported by [eSpeak](http://espeak.sourceforge.net/), so you could think about bootstrapping a phonemizer module prototype using an eSpeak wrapper.

**Comment by TheNarrator** [comment]
Just wanted to add that I've successfully gotten past this error using this method:
(mysql version=5.7, open-jdk version=1.7)
1. While mysql server is running, login as root to your server
2. Run these 2 queries:
```
SET GLOBAL sql_mode='';
SELECT @@GLOBAL.sql_mode;
```
3. Log out as root. Then without restarting your mysql service try the cleanup script.

**Comment by dao-tt** [comment]
@TheNarrator Thank you I just faced the same problem and I can solve it now
