### ISSUE TITLE
Wikipedia Markup cleaning and mysql database creation

### ISSUE THREAD

**Issue by Avinash01111992** [marytts/marytts#824]
after running the below command according to this 2.2. Wikipedia Markup cleaning and mysql database creation

```
avinash@lb:~/lb-work/text-to-speach-engine/marytts-5.x/target/marytts-builder-5.3-SNAPSHOT/bin$ ./wkdb_cleaning_up.sh /home/avinash/wiki_data/wkdb.conf
```

Error is pasted below 

```
Creating connection to DB server...
Mysql connection created successfully.
Creating empty wikipedia tables: checking if tables text, page and revision already exist.
  Creating table: text
  Creating table: page
  Creating table: revision
Exception in thread "main" java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 149
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
	at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:257)
	at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1088)
	at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:444)
Caused by: org.xml.sax.SAXException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 149
	at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
	... 3 more
```

**Comment by seblemaguer** [comment]
I'm confused, did you solve #823? Is it related to it?

**Comment by Avinash01111992** [comment]
I'm sorry same issue i have posted twice the actual open issue is #823
