### ISSUE TITLE
Mvn package to jar

### ISSUE THREAD

**Issue by Pr1ckl3s** [marytts/marytts#835]
**In the eclipse ide, I can run my project with mary in it perfectly fine. However, when I try to export it to a jar by running my pom.xml as Maven build and run the jar through cmd, I get this error:**
```
Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.NoClassDefFoundError: marytts/exceptions/SynthesisException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$155(LauncherImpl.java:352)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: marytts.exceptions.SynthesisException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
```

**Here's my pom.xml for reference:**
https://pastebin.com/9RtsCd7u

**Any suggestions?**

**Comment by psibre** [comment]
Where in your POM are you actually declaring a MaryTTS dependency?
