### ISSUE TITLE
HTKLabeler problem

### ISSUE THREAD

**Issue by Cipusha** [marytts/marytts#838]
Hi,
I am trying to create unit selection voice. I've 1773 files as data. When HTKLabeler runs it throws exception:

```
java.lang.Exception: The component HTKLabeler produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: marytts.exceptions.MaryConfigurationException:   ERROR [+7031]  PutTransMat: Row 4 of transition mat sum = 1.014746
	at marytts.tools.voiceimport.HTKLabeler.herestTraining(HTKLabeler.java:1020)
	at marytts.tools.voiceimport.HTKLabeler.compute(HTKLabeler.java:247)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274)
```
I searched and found that its caused by too much data. Is there any other way to create unit selection voice?

**Comment by psibre** [comment]
The HTKLabeler was already unmaintained when I joined the MaryTTS developer team in 2010, and I've never successfully gotten it to work.

I recommend you use a different forced alignment tool -- maybe try our experimental [Gradle plugin](https://github.com/marytts/gradle-marytts-kaldi-mfa-plugin) for the [Montreal Forced Aligner](https://montrealcorpustools.github.io/Montreal-Forced-Aligner/).
