### ISSUE TITLE
how to add hindi language in marytts.

### ISSUE THREAD

**Issue by sunilskar** [marytts/marytts#853]
Hi core team,
I want to know how to add hindi language in marytts.
is there any full proof script that after running it. the language is add in marytts or that script create the respected files. 
since when we are doing it from  below link it gives lots of warning and lots of error even we done as per instruction. 

https://github.com/marytts/marytts/wiki/New-Language-Support
pls. help me to update the hindi language in marytts.

**Comment by psibre** [comment]
There is https://github.com/marytts/marytts-lang-hi in case you missed it. Although it hasn't been updated in a few years, it should be a good place to start.

**Comment by sunilskar** [comment]
Hi Psibre,
Thanks for replay.
did u have any video presentation for this module.
or direct installable script. with all command explanation,

**Comment by psibre** [comment]
The Hindi language component is research code, and not up to date. You might be able to get it working if you first install something like `v5.1^` of MaryTTS using Maven under Java 7...
But it would be better to update it to something like our more recent projects for language components.

**Comment by psibre** [comment]
But if you'd rather watch a video, [here is a link](https://youtu.be/DD70oKDlemE?t=42).

**Comment by sunilskar** [comment]
which video link you send for watching .  and why ?

**Comment by sunilskar** [comment]
Hi Psibre,
i had done as per the process given  to below link.
https://github.com/marytts/marytts/wiki/New-Language-Support

but when we  run command  
"wkdb_cleaning_up.sh wkdb.conf "
following  process done.

as@as-HP-540:~/mary/marytts/target/marytts-builder-5.2/bin$ ./wkdb_cleaning_up.sh wkdb.conf
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

WikipediaMarkupCleaner parameters:
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -listFile wikilist.txt
  -minPage 10000
  -minText 1000
  -maxText 15000

Mysql driver loaded, set locale=hi
Mysql connection created successfully.
    TABLE = "hi_cleanText" does not exist, it will be created.
Mysql connection closed.
Empty list of files to process.
as@as-HP-540:~/mary/marytts/target/marytts-builder-5.2/bin$ 

but as per web instruction following output window should come. where i am going wrong
$ wkdb_cleaning_up.sh wkdb.conf

Output:

    It creates a file ./done.txt which contains the files already processed, in case the program stops it can be re-started and it will continue processing the not "done" files in the input list.

    A text file ./wordlist-freq.txt containing the list of words and their frequencies, this file will be created after processing each xml file.

    It creates two tables in the the database, the name of the tables depends on the locale, for example if the locale is "en_US" it will create the tables en_US_cleanText and en_US_wordList, their description is:

      mysql> desc en_US_cleanText;
      +-----------+------------------+------+-----+---------+----------------+
      | Field     | Type             | Null | Key | Default | Extra          |
      +-----------+------------------+------+-----+---------+----------------+
      | id        | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
      | cleanText | mediumblob       | NO   |     |         |                |
      | processed | tinyint(1)       | YES  |     | NULL    |                |
      | page_id   | int(10) unsigned | NO   |     |         |                |
      | text_id   | int(10) unsigned | NO   |     |         |                |
      +-----------+------------------+------+-----+---------+----------------+

      mysql> desc en_US_wordList;
      +-----------+------------------+------+-----+---------+----------------+
      | Field     | Type             | Null | Key | Default | Extra          |
      +-----------+------------------+------+-----+---------+----------------+
      | id        | int(11)          | NO   | PRI | NULL    | auto_increment |
      | word      | tinyblob         | NO   |     |         |                |
      | frequency | int(10) unsigned | NO   |     |         |                |
      +-----------+------------------+------+-----+---------+----------------+


help me

**Comment by sunilskar** [comment]
Hi Psibre,
i had done as per the process given  to below link.
https://github.com/marytts/marytts/wiki/New-Language-Support

but when we  run command  
"wkdb_cleaning_up.sh wkdb.conf "
following  process done.

as@as-HP-540:~/mary/marytts/target/marytts-builder-5.2/bin$ ./wkdb_cleaning_up.sh wkdb.conf
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

WikipediaMarkupCleaner parameters:
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -listFile wikilist.txt
  -minPage 10000
  -minText 1000
  -maxText 15000

Mysql driver loaded, set locale=hi
Mysql connection created successfully.
    TABLE = "hi_cleanText" does not exist, it will be created.
Mysql connection closed.
Empty list of files to process.
as@as-HP-540:~/mary/marytts/target/marytts-builder-5.2/bin$ 

but as per web instruction following output window should come. where i am going wrong
$ wkdb_cleaning_up.sh wkdb.conf

Output:

    It creates a file ./done.txt which contains the files already processed, in case the program stops it can be re-started and it will continue processing the not "done" files in the input list.

    A text file ./wordlist-freq.txt containing the list of words and their frequencies, this file will be created after processing each xml file.

    It creates two tables in the the database, the name of the tables depends on the locale, for example if the locale is "en_US" it will create the tables en_US_cleanText and en_US_wordList, their description is:

      mysql> desc en_US_cleanText;
      +-----------+------------------+------+-----+---------+----------------+
      | Field     | Type             | Null | Key | Default | Extra          |
      +-----------+------------------+------+-----+---------+----------------+
      | id        | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
      | cleanText | mediumblob       | NO   |     |         |                |
      | processed | tinyint(1)       | YES  |     | NULL    |                |
      | page_id   | int(10) unsigned | NO   |     |         |                |
      | text_id   | int(10) unsigned | NO   |     |         |                |
      +-----------+------------------+------+-----+---------+----------------+

      mysql> desc en_US_wordList;
      +-----------+------------------+------+-----+---------+----------------+
      | Field     | Type             | Null | Key | Default | Extra          |
      +-----------+------------------+------+-----+---------+----------------+
      | id        | int(11)          | NO   | PRI | NULL    | auto_increment |
      | word      | tinyblob         | NO   |     |         |                |
      | frequency | int(10) unsigned | NO   |     |         |                |
      +-----------+------------------+------+-----+---------+----------------+


help me

**Comment by sunilskar** [comment]
ok after doing split option it work and start adding file in sql database but it gives following error

Exception in thread "main" java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 61
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:92)
	at marytts.tools.dbselection.DBHandler.loadPagesWithMWDumper(DBHandler.java:257)
	at marytts.tools.dbselection.WikipediaMarkupCleaner.processWikipediaPages(WikipediaMarkupCleaner.java:1088)
	at marytts.tools.dbselection.WikipediaProcessor.main(WikipediaProcessor.java:444)
Caused by: org.xml.sax.SAXException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rev_comment' at row 61
	at org.mediawiki.importer.XmlDumpReader.endElement(XmlDumpReader.java:227)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.mediawiki.importer.XmlDumpReader.readDump(XmlDumpReader.java:88)
	... 3 more


how to rectify this

**Comment by psibre** [comment]
Sounds like a duplicate of #851.

**Comment by psibre** [comment]
But seriously, I'd recommend starting from the existing Hindi language component.

**Comment by sunilskar** [comment]
how can we start with existing hindi language component.
pls. give steps or explain how can we generate installable fies of marytts hindi language

**Comment by sunilskar** [comment]
how can  we start from hindi language component . i found following link about hindi component.

https://github.com/marytts/marytts-lang-hi

how we go further with this component pls. give the steps to create installable marytts language in hindi.
thanks.

**Comment by ranjan-rk** [comment]
@sunilskar Consider spending some time going through the source code of marytts. Explore it in detail. Figure out how did they add support for Engish or German.  The code will tell you everything.
This should be the starting point. There are no shortcuts.
