### ISSUE TITLE
when use  transcriptionTool for my new language ，where i can get  language text and  phoneset?

### ISSUE THREAD

**Issue by RayOsLei** [marytts/marytts#860]

**Comment by nshmyrev** [comment]
What language exactly

**Comment by RayOsLei** [comment]
chinese language @nshmyrev

**Comment by RayOsLei** [comment]
Dose chinese language have  language text and phoneset？@nshmyrev

**Comment by nshmyrev** [comment]
@RayOsLei sure, you can download one here:

http://www.openslr.org/33/

specifically you need 

http://www.openslr.org/resources/33/resource_aishell.tgz

There are many other Chinese datasets on openslr which you may find interesting. You can also check Ekho sources http://www.eguidedog.net/ekho.php for some ideas.

**Comment by RayOsLei** [comment]
hi @nshmyrev ，thanks for your answer，but when i download the [resource_aishell.tgz](http://www.openslr.org/resources/33/resource_aishell.tgz), 

i get this file lexicon.txt, then i excuse this command:

```shell
lexicon_lts_pos_builder.sh ./allophones.zh.xml ./lexicon.txt
```

the allophones.zh.xml as flow:

```
<allophones name="zh" xml:lang="zh_CN"
        features="vheight vfront vrnd vtone ctype cplace cvox">
    <silence ph="_"/>

    <vowel ph="a1" vheight="3" vfront="2" vrnd="-" vtone="1"/>
    <vowel ph="i1" vheight="3" vfront="1" vrnd="-" vtone="1"/>
    <vowel ph="e1" vheight="2" vfront="1" vrnd="-" vtone="1"/>
    <vowel ph="u1" vheight="1" vfront="3" vrnd="+" vtone="1"/>
    <vowel ph="o1" vheight="1" vfront="3" vrnd="+" vtone="1"/>

    <vowel ph="a2" vheight="3" vfront="2" vrnd="-" vtone="2"/>
    <vowel ph="i2" vheight="3" vfront="1" vrnd="-" vtone="2"/>
    <vowel ph="e2" vheight="2" vfront="1" vrnd="-" vtone="2"/>
    <vowel ph="u2" vheight="1" vfront="3" vrnd="+" vtone="2"/>
    <vowel ph="o2" vheight="1" vfront="3" vrnd="+" vtone="2"/>

    <vowel ph="a3" vheight="3" vfront="2" vrnd="-" vtone="3"/>
    <vowel ph="i3" vheight="3" vfront="1" vrnd="-" vtone="3"/>
    <vowel ph="e3" vheight="2" vfront="1" vrnd="-" vtone="3"/>
    <vowel ph="u3" vheight="1" vfront="3" vrnd="+" vtone="3"/>
    <vowel ph="o3" vheight="1" vfront="3" vrnd="+" vtone="3"/>

    <vowel ph="a4" vheight="3" vfront="2" vrnd="-" vtone="4"/>
    <vowel ph="i4" vheight="3" vfront="1" vrnd="-" vtone="4"/>
    <vowel ph="e4" vheight="2" vfront="1" vrnd="-" vtone="4"/>
    <vowel ph="u4" vheight="1" vfront="3" vrnd="+" vtone="4"/>
    <vowel ph="o4" vheight="1" vfront="3" vrnd="+" vtone="4"/>


    <consonant ph="b" ctype="s" cplace="l" cvox="+"/>
    <consonant ph="p" ctype="s" cplace="l" cvox="-"/>
    <consonant ph="t" ctype="s" cplace="a" cvox="-"/>
    <consonant ph="d" ctype="s" cplace="a" cvox="+"/>
    <consonant ph="k" ctype="s" cplace="v" cvox="-"/>
    <consonant ph="g" ctype="s" cplace="v" cvox="+"/>

    <consonant ph="zh" ctype="a" cplace="p" cvox="+"/>
    <consonant ph="ch" ctype="a" cplace="p" cvox="+"/>
    <consonant ph="sh" ctype="a" cplace="p" cvox="-"/>

    <consonant ph="q" ctype="a" cplace="ap" cvox="-"/>
    <consonant ph="j" ctype="a" cplace="ap" cvox="+"/>

    <consonant ph="f" ctype="f" cplace="b" cvox="-"/>
    <consonant ph="v" ctype="f" cplace="b" cvox="+"/>
    <consonant ph="s" ctype="f" cplace="a" cvox="-"/>
    <consonant ph="z" ctype="f" cplace="a" cvox="+"/>
    <consonant ph="h" ctype="f" cplace="g" cvox="-"/>
    <consonant ph="x" ctype="f" cplace="ap" cvox="-"/>

    <consonant ph="l" ctype="l" cplace="a" cvox="+"/>
    <consonant ph="m" ctype="n" cplace="l" cvox="+"/>
    <consonant ph="n" ctype="n" cplace="a" cvox="+"/>
    <consonant ph="r" ctype="r" cplace="a" cvox="+"/>
    <consonant ph="w" ctype="r" cplace="l" cvox="+"/>

    <consonant ph="ng" ctype="n" cplace="v" cvox="+"/>

</allophones>
```

but it occus :

```shell
trainPredict ...
training ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
training completed.
Problem processing the following input:
args[0]:./allophones.zh.xml
args[1]:./lexicon.txt


java.lang.IllegalArgumentException: Too many strings for a byte-string translator: 
"耀" "老" "考" "耄" "者" "耆" "耇" "耈" "耉" "耊" "耋" "而" "耍" "耎" "耐" "耒" "耔" "耕" "耗" "耘" "耙" "耜" "耝" "耞" "耡" "耤" "耦" "耧" "耨" "耩" "耪" "1" "耳" "耵" "5" "耶" "耷" "耸" "耻" "耼" "耽" "耿" "聂" "聃" "聆" "聊" "聋" "职" "聍" "聎" "聒" "联" "䁖" "聘" "聚" "聝" "b" "聩" "i" "聪" "k" "聮" "o" "聯" "聴" "聼" "聿" "肃" "肆" "肇" "肉" "肋" "肌" "肐" "肓" "肕" "肖" "䂖" "肘" "肙" 
...
...
...
(10324 strings)
	at marytts.util.string.ByteStringTranslator.<init>(ByteStringTranslator.java:81)
	at marytts.features.FeatureDefinition.<init>(FeatureDefinition.java:165)
	at marytts.tools.newlanguage.LTSTrainer.graphemeFeatureDef(LTSTrainer.java:310)
	at marytts.tools.newlanguage.LTSTrainer.trainTree(LTSTrainer.java:166)
	at marytts.tools.transcription.LTSLexiconPOSBuilder.trainLTS(LTSLexiconPOSBuilder.java:191)
	at marytts.tools.transcription.LTSLexiconPOSBuilder.trainPredict(LTSLexiconPOSBuilder.java:147)
	at marytts.tools.transcription.LTSLexiconPOSBuilder.main(LTSLexiconPOSBuilder.java:273)

Failure exit
```

**Comment by nshmyrev** [comment]
Well, openmary assumes it can encode characters as byte (256 symbols), its not the case for Chinese. You need to figure out how to go without the translator. In any case small code modifications will be likely required.
