### ISSUE TITLE
Cannot syllabify empty phone string

### ISSUE THREAD

**Issue by RayOsLei** [marytts/marytts#866]
when i excuse  this command:

```shell
lexicon_lts_pos_builder.sh ./allophones.zh.xml ./wordlist-freq.txt
```

It throws the following error:

```
trainPredict ...
training ... 
iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
training completed.
      Training decision tree for: null
Problem processing the following input:
args[0]:./allophones.zh.xml
args[1]:./wordlist-freq.txt


java.lang.IllegalArgumentException: Cannot syllabify empty phone string
	at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:479)
	at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:179)
	at marytts.tools.transcription.LTSLexiconPOSBuilder.trainPredict(LTSLexiconPOSBuilder.java:155)
	at marytts.tools.transcription.LTSLexiconPOSBuilder.main(LTSLexiconPOSBuilder.java:273)
```

here is my [allophones.zh.txt](https://github.com/marytts/marytts/files/1969381/allophones.zh.txt), [wordlist-freq.txt](https://github.com/marytts/marytts/files/1969386/wordlist-freq.txt)

**Comment by RayOsLei** [comment]
anyone please??????

**Comment by seblemaguer** [comment]
Hello, I don't understand why are you using a frequency wordlist? You should have a transcription word list

**Comment by RayOsLei** [comment]
i am sorry
