### ISSUE TITLE
Error when compiling to Jar file, Cannot start MARY server

### ISSUE THREAD

**Issue by 18046** [marytts/marytts#873]
Odd error, when running my Jar file with the libraries packaged in it gives an error on launch

> Jun 26, 2018 6:27:34 PM blazingforest.tts.TextToSpeech <init>
SEVERE: null
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
        at blazingforest.tts.TextToSpeech.<init>(TextToSpeech.java:21)
        at blazingforest.main.ReadFile.<init>(ReadFile.java:35)
        at blazingforest.main.Main.<init>(Main.java:26)
        at blazingforest.main.Main.main(Main.java:70)
Caused by: java.lang.NullPointerException
        at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:70)
        at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
        ... 4 more

I used JarSplice to include all the libraries into the Jar file, yet it still gives an error.
It works fine in eclipse ( my IDE ) so I don't think it's my code or the way I'm adding the libraries to the jar ( JarSplice is usually quite reliable ) so I'm posting it here.

**Comment by seblemaguer** [comment]
Hello,

can you put the full stacktrace? I don't have enough information to debug this

**Comment by psibre** [comment]
This is typical when several MaryTTS jars are packed together without merging the service loaders. Please see, e.g., #725, #690, etc.
