### ISSUE TITLE
importing voice using maryTTS 5.2 VIT tools fails at PhoneFeatureFileWriter with error The number of BYTE features differs: 104 versus 106

### ISSUE THREAD

**Issue by GaneshHaral** [marytts/marytts#893]
Hi,
I am using maryTTS 5.2 voice building tools to generate new voice for hindi language.
For that purpose I am using cmu hindi voice database cmu_indic_hin_ab.ta.bz2
Just to start with I have added only one wave file and its text transcript to test voice import tool.
I am following steps given on https://github.com/marytts/marytts/wiki/UnitSelectionVoiceCreation.
Currently I am at step PhoneFeaturesFileWriter.
When I run this step it gives me below error:
hindi_0002 : Entering at index (0) -- java.lang.Exception: The component PhoneFeatureFileWriter produced the following exception: 
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:277)
Caused by: java.lang.IllegalArgumentException: **Features in file hindi_0002 do not match definition file /home/ganesh/HindiVoice/mary/phoneUnitFeatureDefinition.txt because:
The number of BYTE features differs: 104 versus 106**
	at marytts.tools.voiceimport.PhoneFeatureFileWriter.writeUnitFeaturesTo(PhoneFeatureFileWriter.java:156)
	at marytts.tools.voiceimport.PhoneFeatureFileWriter.compute(PhoneFeatureFileWriter.java:115)
	at marytts.tools.voiceimport.DatabaseImportMain$8.run(DatabaseImportMain.java:274).
I have attached input files used by PhoneFeatureFileWriter
[PhoneFeatureInputFiles.zip](https://github.com/marytts/marytts/files/2453739/PhoneFeatureInputFiles.zip)

Please help me to solve this.

**Comment by GaneshHaral** [comment]
@psibre can you please help me in this matter?

**Comment by GaneshHaral** [comment]
@psibre I am stuck here badly. could you please give me some direction ?
