### ISSUE TITLE
Dutch HMM voice unusable because of allophone problems.

### ISSUE THREAD

**Issue by bkiefer** [marytts/marytts#895]
Having now tried several times to get to a Dutch voice, now with a setup and data set that runs the HMM creation as described in the wiki end-to-end without errors, using the voice results in

```
java.lang.Exception: Module JPhonemiser: Problem processing the data.
        at marytts.server.Request.processOneChunk(Request.java:568)
        at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
        at marytts.server.Request.process(Request.java:337)
        at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
        at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
        at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
        at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
        at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
        at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
        at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.inputReady(AsyncNHttpServiceHandler.java:316)
        at org.apache.http.nio.protocol.BufferingHttpServiceHandler.inputReady(BufferingHttpServiceHandler.java:131)
        at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:173)
        at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIO
Reactor.java:275)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Cannot syllabify empty phone string
        at marytts.modules.phonemiser.AllophoneSet.syllabify(AllophoneSet.java:479)
        at marytts.modules.phonemiser.TrainedLTS.syllabify(TrainedLTS.java:179)
        at marytts.language.nl.Phonemiser.phonemise(Phonemiser.java:74)
        at marytts.modules.JPhonemiser.process(JPhonemiser.java:193)
        at marytts.server.Request.processOneChunk(Request.java:566)
        ... 19 more
```

I believe we created the allophone set according to the information that we found for the Dutch language, compatible to the spelling lexicon that is provided. Where exactly does the process ignore this information, so that the result above happens? A fork of the main repository with an up-to-date
adapted 5.2 version for language nl can be found at `https://github.com/bkiefer/marytts/tree/nl5.2`. This was the basis for the voice building process.

**Comment by psibre** [comment]
What's the input that triggers the error?

**Comment by bkiefer** [comment]
Welkom in de wereld van de spraaksynthese!

**Comment by bkiefer** [comment]
I just realized that the exclamation mark is causing this problem, so maybe i should close this.
