### ISSUE TITLE
Hosting on Secure HTTPS with onstart() and onend() events

### ISSUE THREAD

**Issue by skmalviya** [marytts/marytts#899]
I love the performance and accurate result delivered by marytts server specially the uni-selection models. Interestingly, I would like perform following two task with MaryTTS server:

1. I want to deploy it on **HTTPS localhost** so that I can use it in my websites on **HTTPS**. Please help me in to do so if possible. 

2. Additionally, does marytts have these **onstart()** and **onend()** events which is there in **google speechsynthesis** API. Its really going to build some beautiful TTS-based applications. 

Thank you.!

**Comment by psibre** [comment]
We've held back from dealing with transport protocols, delegating instead to the actual webserver running on the local host. In fact, for MaryTTS v6.x, this has been externalized to a separate project hosted at https://github.com/marytts/marytts-http-server

Could you please elaborate how MaryTTS prevents you from running via HTTPS?

The REST API in the new MaryTTS HTTP server is incubating, but feel free to open a feature request on the corresponding issue tracker (please provide links to the API you mention).

**Comment by skmalviya** [comment]
Please give description of how I could start my **marytts-server** to host on my local **ip-address**. 
current : http://localhost:59124
**what i want : http://172.17.25.112:59124**
So that it would available for all in the intranet.

Thank you.!

**Comment by psibre** [comment]
If your machine's IP address can be reached and the MaryTTS server is running with an open port, then it will be available at the corresponding URL. This should not be an issue.

There is [a wiki page for this](../wiki/Local-MaryTTS-Server-Installation), which may provide more insight.

**Comment by skmalviya** [comment]
I followed the link to host MaryTTS server. Got some following results:

**shrikant@silp50:/local/mary/marytts$ javac -version
javac 1.8.0_03-Ubuntu

shrikant@silp50:/local/mary/marytts$ java -version
java version "1.7.0_181"**

1. **sudo -u mary /opt/apache-maven-3.0.5/bin/mvn package**

`[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-builder' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-builder
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- gradle-maven-plugin:1.0.7:invoke (default) @ marytts-assembly-builder ---
[INFO] jvmArgs: [Ljava.lang.String;@7d5647b3
[INFO] gradleProjectDirectory: /local/mary/marytts/marytts-assembly/assembly-builder
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] 
[INFO] gradle execution complete
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-assembly-runtime 5.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly-runtime ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly-runtime ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449082020
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- gradle-maven-plugin:1.0.7:invoke (default) @ marytts-assembly-runtime ---
[INFO] jvmArgs: [Ljava.lang.String;@1f4e62b5
[INFO] gradleProjectDirectory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] 
[INFO] gradle execution complete
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-assembly 5.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449183733
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ........................................... SUCCESS [0.589s]
[INFO] marytts-common .................................... SUCCESS [3.073s]
[INFO] marytts-signalproc ................................ SUCCESS [2.790s]
[INFO] marytts-runtime ................................... SUCCESS [6.353s]
[INFO] marytts-lang-de ................................... SUCCESS [1.056s]
[INFO] marytts-lang-en ................................... SUCCESS [2.969s]
[INFO] marytts-lang-te ................................... SUCCESS [0.710s]
[INFO] marytts-lang-tr ................................... SUCCESS [0.739s]
[INFO] marytts-lang-ru ................................... SUCCESS [0.714s]
[INFO] marytts-lang-it ................................... SUCCESS [1.197s]
[INFO] marytts-lang-fr ................................... SUCCESS [1.219s]
[INFO] marytts-lang-sv ................................... SUCCESS [0.721s]
[INFO] marytts-lang-lb ................................... SUCCESS [2.858s]
[INFO] marytts-lang-hi ................................... SUCCESS [0.724s]
[INFO] marytts-languages ................................. SUCCESS [0.009s]
[INFO] voice-cmu-slt-hsmm ................................ SUCCESS [2.106s]
[INFO] marytts-client .................................... SUCCESS [1.828s]
[INFO] marytts-builder ................................... SUCCESS [5.536s]
[INFO] marytts-redstart .................................. SUCCESS [0.206s]
[INFO] marytts-transcription ............................. SUCCESS [0.145s]
[INFO] voice-my_voice_hi ................................. SUCCESS [17.371s]
[INFO] voice-myvoice_hi_hmm-hsmm ......................... SUCCESS [0.911s]
[INFO] marytts-assembly-builder .......................... SUCCESS [3.529s]
[INFO] marytts-assembly-runtime .......................... SUCCESS [1:41.724s]
[INFO] marytts-assembly .................................. SUCCESS [0.012s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:39.288s
[INFO] Finished at: Sat Nov 17 15:36:23 IST 2018
[INFO] Final Memory: 47M/1279M
[INFO] ------------------------------------------------------------------------
shrikant@silp50:/local/mary/marytts$ 
`

2. **sudo -u mary /opt/apache-maven-3.0.5/bin/mvn install**

`[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- gradle-maven-plugin:1.0.7:invoke (default) @ marytts-assembly-runtime ---
[INFO] jvmArgs: [Ljava.lang.String;@172ee667
[INFO] gradleProjectDirectory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Build
[INFO] Validate distribution
[INFO] Build
[INFO] 
[INFO] gradle execution complete
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (integration-test) @ marytts-assembly-runtime ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (verify) @ marytts-assembly-runtime ---
[INFO] 
[INFO] --- maven-source-plugin:3.0.0:jar-no-fork (attach-sources) @ marytts-assembly-runtime ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ marytts-assembly-runtime ---
[INFO] Installing /local/mary/marytts/marytts-assembly/assembly-runtime/pom.xml to /home/mary/.m2/repository/de/dfki/mary/marytts-assembly-runtime/5.2/marytts-assembly-runtime-5.2.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building marytts-assembly 5.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449549693
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (integration-test) @ marytts-assembly ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (verify) @ marytts-assembly ---
[INFO] 
[INFO] --- maven-source-plugin:3.0.0:jar-no-fork (attach-sources) @ marytts-assembly ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ marytts-assembly ---
[INFO] Installing /local/mary/marytts/marytts-assembly/pom.xml to /home/mary/.m2/repository/de/dfki/mary/marytts-assembly/5.2/marytts-assembly-5.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ........................................... SUCCESS [0.910s]
[INFO] marytts-common .................................... SUCCESS [2.910s]
[INFO] marytts-signalproc ................................ SUCCESS [2.604s]
[INFO] marytts-runtime ................................... SUCCESS [7.824s]
[INFO] marytts-lang-de ................................... SUCCESS [3.104s]
[INFO] marytts-lang-en ................................... SUCCESS [5.151s]
[INFO] marytts-lang-te ................................... SUCCESS [0.709s]
[INFO] marytts-lang-tr ................................... SUCCESS [0.721s]
[INFO] marytts-lang-ru ................................... SUCCESS [0.765s]
[INFO] marytts-lang-it ................................... SUCCESS [2.557s]
[INFO] marytts-lang-fr ................................... SUCCESS [1.181s]
[INFO] marytts-lang-sv ................................... SUCCESS [0.729s]
[INFO] marytts-lang-lb ................................... SUCCESS [4.472s]
[INFO] marytts-lang-hi ................................... SUCCESS [0.730s]
[INFO] marytts-languages ................................. SUCCESS [0.016s]
[INFO] voice-cmu-slt-hsmm ................................ SUCCESS [4.674s]
[INFO] marytts-client .................................... SUCCESS [5.140s]
[INFO] marytts-builder ................................... SUCCESS [7.572s]
[INFO] marytts-redstart .................................. SUCCESS [0.254s]
[INFO] marytts-transcription ............................. SUCCESS [0.139s]
[INFO] voice-my_voice_hi ................................. SUCCESS [22.148s]
[INFO] voice-myvoice_hi_hmm-hsmm ......................... SUCCESS [2.424s]
[INFO] marytts-assembly-builder .......................... SUCCESS [3.599s]
[INFO] marytts-assembly-runtime .......................... SUCCESS [1:41.384s]
[INFO] marytts-assembly .................................. SUCCESS [0.015s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:01.974s
[INFO] Finished at: Sat Nov 17 15:42:29 IST 2018
[INFO] Final Memory: 41M/841M
[INFO] ------------------------------------------------------------------------
shrikant@silp50:/local/mary/marytts$ 
`

3. **sudo -u mary /opt/apache-maven-3.0.5/bin/mvn site:site site:stage -DstagingDirectory=/local/mary/www**

`[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/voice-myvoice_hi_hmm-hsmm' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/voice-myvoice_hi_hmm-hsmm
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking marytts-assembly-builder 5.2
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly-builder ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly-builder ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-builder' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-builder
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449691604
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-builder' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-builder
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking marytts-assembly-runtime 5.2
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly-runtime ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly-runtime ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449691616
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking marytts-assembly 5.2
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542449691624
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.3:aggregate @ marytts-common <<<
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ........................................... SUCCESS [23.451s]
[INFO] marytts-common .................................... FAILURE [0.352s]
[INFO] marytts-signalproc ................................ SKIPPED
[INFO] marytts-runtime ................................... SKIPPED
[INFO] marytts-lang-de ................................... SKIPPED
[INFO] marytts-lang-en ................................... SKIPPED
[INFO] marytts-lang-te ................................... SKIPPED
[INFO] marytts-lang-tr ................................... SKIPPED
[INFO] marytts-lang-ru ................................... SKIPPED
[INFO] marytts-lang-it ................................... SKIPPED
[INFO] marytts-lang-fr ................................... SKIPPED
[INFO] marytts-lang-sv ................................... SKIPPED
[INFO] marytts-lang-lb ................................... SKIPPED
[INFO] marytts-lang-hi ................................... SKIPPED
[INFO] marytts-languages ................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................ SKIPPED
[INFO] marytts-client .................................... SKIPPED
[INFO] marytts-builder ................................... SKIPPED
[INFO] marytts-redstart .................................. SKIPPED
[INFO] marytts-transcription ............................. SKIPPED
[INFO] voice-my_voice_hi ................................. SKIPPED
[INFO] voice-myvoice_hi_hmm-hsmm ......................... SKIPPED
[INFO] marytts-assembly-builder .......................... SKIPPED
[INFO] marytts-assembly-runtime .......................... SKIPPED
[INFO] marytts-assembly .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.206s
[INFO] Finished at: Sat Nov 17 15:44:51 IST 2018
[INFO] Final Memory: 44M/881M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-cli) on project marytts-common: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site failed: site.xml late interpolation ${project.*} expression found in link: '${project.url}:59125'. Use early interpolation ${this.*} -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-common
shrikant@silp50:/local/mary/marytts$ 
`

Unable to cross this last hurdle!! Please help....

**Comment by skmalviya** [comment]
When I run the following command:
** sudo -u mary /opt/apache-maven-3.0.5/bin/mvn -e site:site site:stage -DstagingDirectory=/local/mary/www
**

`[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-builder' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-builder
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking marytts-assembly-runtime 5.2
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly-runtime ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly-runtime ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542450248357
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly/assembly-runtime' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly/assembly-runtime
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking marytts-assembly 5.2
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-java-7-or-higher) @ marytts-assembly ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ marytts-assembly ---
[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildNumber: 4759643034d127647d9fd54b4dfb38cd8beb3009 at timestamp: 1542450248365
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/local/mary/marytts/marytts-assembly' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /local/mary/marytts/marytts-assembly
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] <<< maven-javadoc-plugin:2.10.3:aggregate @ marytts-common <<<
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] MaryTTS ........................................... SUCCESS [22.701s]
[INFO] marytts-common .................................... FAILURE [0.337s]
[INFO] marytts-signalproc ................................ SKIPPED
[INFO] marytts-runtime ................................... SKIPPED
[INFO] marytts-lang-de ................................... SKIPPED
[INFO] marytts-lang-en ................................... SKIPPED
[INFO] marytts-lang-te ................................... SKIPPED
[INFO] marytts-lang-tr ................................... SKIPPED
[INFO] marytts-lang-ru ................................... SKIPPED
[INFO] marytts-lang-it ................................... SKIPPED
[INFO] marytts-lang-fr ................................... SKIPPED
[INFO] marytts-lang-sv ................................... SKIPPED
[INFO] marytts-lang-lb ................................... SKIPPED
[INFO] marytts-lang-hi ................................... SKIPPED
[INFO] marytts-languages ................................. SKIPPED
[INFO] voice-cmu-slt-hsmm ................................ SKIPPED
[INFO] marytts-client .................................... SKIPPED
[INFO] marytts-builder ................................... SKIPPED
[INFO] marytts-redstart .................................. SKIPPED
[INFO] marytts-transcription ............................. SKIPPED
[INFO] voice-my_voice_hi ................................. SKIPPED
[INFO] voice-myvoice_hi_hmm-hsmm ......................... SKIPPED
[INFO] marytts-assembly-builder .......................... SKIPPED
[INFO] marytts-assembly-runtime .......................... SKIPPED
[INFO] marytts-assembly .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.356s
[INFO] Finished at: Sat Nov 17 15:54:08 IST 2018
[INFO] Final Memory: 46M/989M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-cli) on project marytts-common: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site failed: site.xml late interpolation ${project.*} expression found in link: '${project.url}:59125'. Use early interpolation ${this.*} -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-cli) on project marytts-common: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site failed: site.xml late interpolation ${project.*} expression found in link: '${project.url}:59125'. Use early interpolation ${this.*}
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site failed: site.xml late interpolation ${project.*} expression found in link: '${project.url}:59125'. Use early interpolation ${this.*}
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalArgumentException: site.xml late interpolation ${project.*} expression found in link: '${project.url}:59125'. Use early interpolation ${this.*}
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler$URLRebaser.rebaseLink(DefaultDecorationModelInheritanceAssembler.java:456)
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.rebaseLinkItemPaths(DefaultDecorationModelInheritanceAssembler.java:300)
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.rebaseMenuPaths(DefaultDecorationModelInheritanceAssembler.java:288)
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.mergeMenus(DefaultDecorationModelInheritanceAssembler.java:257)
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleBodyInheritance(DefaultDecorationModelInheritanceAssembler.java:231)
	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleModelInheritance(DefaultDecorationModelInheritanceAssembler.java:109)
	at org.apache.maven.doxia.tools.DefaultSiteTool.getDecorationModel(DefaultSiteTool.java:1200)
	at org.apache.maven.doxia.tools.DefaultSiteTool.getDecorationModel(DefaultSiteTool.java:440)
	at org.apache.maven.plugins.site.descriptor.AbstractSiteDescriptorMojo.prepareDecorationModel(AbstractSiteDescriptorMojo.java:86)
	at org.apache.maven.plugins.site.render.AbstractSiteRenderingMojo.createSiteRenderingContext(AbstractSiteRenderingMojo.java:279)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:151)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:135)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :marytts-common
shrikant@silp50:/local/mary/marytts$ 
`

**Comment by psibre** [comment]
You don't need to run the `site` command. It's only for building the (legacy) MaryTTS website.

**Comment by skmalviya** [comment]
I want to show you the screen shot.
1. When run http://localhost:59125
![localhost](https://user-images.githubusercontent.com/19930752/48664672-3d716300-eac8-11e8-8ccf-039470a355e6.png)

2. When run http://172.17.25.50:59125
![server](https://user-images.githubusercontent.com/19930752/48664669-33e7fb00-eac8-11e8-98ba-bf4e24dabaa8.png)

**Comment by skmalviya** [comment]
It is clearly visible that 1. is loaded properly, 
but 2. is keep loading but never able to load completely.

**Comment by psibre** [comment]
Maybe your browser is blocking scripts for 172.17.25.50?
