### ISSUE TITLE
Exception on Java 12

### ISSUE THREAD

**Issue by vitaly-zdanevich** [marytts/marytts#917]
https://github.com/marytts/marytts/blob/31c10d5bd47f08b24034c81635507a9b5a404a3a/marytts-runtime/src/main/java/marytts/server/EnvironmentChecks.java#L46

```Exception in thread "main" marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at Txt2Wav.main(Txt2Wav.java:15)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3410)
	at java.base/java.lang.String.substring(String.java:1883)
	at marytts.server.EnvironmentChecks.check(EnvironmentChecks.java:46)
	at marytts.server.Mary.startup(Mary.java:286)
	at marytts.server.Mary.startup(Mary.java:204)
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:72)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 1 more
```

`javaVersion` here is `12`.

**Comment by seblemaguer** [comment]
Hello,

this is related to #897. The 6.X s solving this problem normally but we will try to do a release to solve this specific part in between as we are overworked right now.
