### ISSUE TITLE
Execution failed for task ':marytts-languages:marytts-lang-de:integrationTest'

### ISSUE THREAD

**Issue by joerg65** [marytts/marytts#925]
I try to compile marytts on Armbian running on an Odroid C1 with mainline kernel 5.2.0-rc6. There was no jdk preinstalled, so installed openjdk-8-jdk-headless.

4 tests are failing:

Test | Duration | Result
-- | -- | --
testCase[0](SPD) | 0.044s | passed
testCase[10](iban3) | 0.065s | failed
testCase[11](vChr) | 0.058s | passed
testCase[1](abbrev9) | 0.130s | passed
testCase[2](abbrev10) | 0.098s | passed
testCase[3](abbrev11) | 0.065s | passed
testCase[4](abbrev12) | 0.039s | passed
testCase[5](net1) | 0.105s | passed
testCase[6](specialchar1) | 0.056s | passed
testCase[7](unicode1) | 0.236s | failed
testCase[8](iban1) | 0.118s | failed
testCase[9](iban2) | 0.192s | failed

This is the output of testCase[10](iban3):
```
java.lang.Exception: XML documents are not equal
==========target:=============
<?xml version="1.0" encoding="UTF-8"?>
<maryxml version="0.5" xml:lang="de"
    xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <p>
        <s>
            <mtu accent="first" orig="DE12345678901234567890">
                <prosody rate="-20%">
                    <phonology precision="precise">
                        <mtu accent="last" orig="DE">
                            <t accent="unknown">D</t>
                            <t accent="unknown">E</t>
                        </mtu>
                    </phonology>
                </prosody>
                <mtu accent="last" orig="12345678901234567890">
                    <t>eins</t>
                    <t>zwei</t>
                    <t>drei</t>
                    <t>vier</t>
                    <t>fünf</t>
                    <t>sechs</t>
                    <t>sieben</t>
                    <t>acht</t>
                    <t>neun</t>
                    <t>null</t>
                    <t>eins</t>
                    <t>zwei</t>
                    <t>drei</t>
                    <t>vier</t>
                    <t>fünf</t>
                    <t>sechs</t>
                    <t>sieben</t>
                    <t>acht</t>
                    <t>neun</t>
                    <t>null</t>
                </mtu>
            </mtu>
        </s>
    </p>
</maryxml>


==========processed:============
<?xml version="1.0" encoding="UTF-8"?>
<maryxml version="0.5" xml:lang="de"
    xmlns="http://mary.dfki.de/2002/MaryXML" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <p>
        <s>
            <mtu accent="first" orig="DE12345678901234567890">
                <prosody rate="-20%">
                    <phonology precision="precise">
                        <mtu accent="last" orig="DE">
                            <t accent="unknown">D</t>
                            <t accent="unknown">E</t>
                        </mtu>
                    </phonology>
                </prosody>
                <mtu accent="last" orig="12345678901234567890">
                    <t>eins</t>
                    <t>zwei</t>
                    <t>drei</t>
                    <t>vier</t>
                    <t>f��nf</t>
                    <t>sechs</t>
                    <t>sieben</t>
                    <t>acht</t>
                    <t>neun</t>
                    <t>null</t>
                    <t>eins</t>
                    <t>zwei</t>
                    <t>drei</t>
                    <t>vier</t>
                    <t>f��nf</t>
                    <t>sechs</t>
                    <t>sieben</t>
                    <t>acht</t>
                    <t>neun</t>
                    <t>null</t>
                </mtu>
            </mtu>
        </s>
    </p>
</maryxml>


	at marytts.tests.modules.MaryModuleTestCase.processAndCompare(MaryModuleTestCase.java:115)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at marytts.language.de.PreprocessorIT.testCase(PreprocessorIT.groovy:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.te`stng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Text does not match: fünf f��nf
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1115)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1108)
	at marytts.util.dom.DomUtils.compareNodes(DomUtils.java:1050)
	at marytts.tests.modules.MaryModuleTestCase.processAndCompare(MaryModuleTestCase.java:103)
	... 58 more

```

**Comment by psibre** [comment]
Thanks for the report! This smells like a locale issue. Could you please provide the output of `locale` in your environment?

**Comment by joerg65** [comment]
Thank you, here is output of `locale`:

```
$ locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=de_DE.UTF-8
```

**Comment by buergi** [comment]
Same problem for me, with current master, any news on this?

**Comment by seblemaguer** [comment]
Hello, do you also have the locale into german UTF8?

**Comment by buergi** [comment]
Hm, I tried it on Windows with German settings, however I don't have any locale environmentvvariables set. I also tried it with explicitly set German ones, without any success (probably I should have tried out English locales 😅). However, I managed to successfully build on Linux with English locales. Would be great the soon have new official prebuild jar release.
