### ISSUE TITLE
cmuslthsmmconfigtest failure

### ISSUE THREAD

**Issue by rkizito** [marytts/marytts#927]
I'm running marytts-master and using openjdk12, gradle 5.5.1 and getting the error below. What i'm i missing? 

Gradle suite > Gradle test >  marytts.voice.CmuSltHsmm.CmuSltHsmmConfigTest > setup FAILED
    marytts.exceptions.MaryConfigurationException: cannot load properties
        at marytts.config.MaryConfig.<init>(MaryConfig.java:197)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfig.<init>(CmuSltHsmmConfig.java:11)

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite.callConstructor(ConstructorSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:241)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfigTest.setup(CmuSltHsmmConfigTest.groovy:12)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.io.Reader.<init>(Reader.java:167)
            at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
            at java.base/java.util.Scanner.<init>(Scanner.java:566)
            at marytts.util.io.PropertiesTrimTrailingWhitespace.load(PropertiesTrimTrailingWhitespace.java:21)
            at marytts.config.MaryConfig.<init>(MaryConfig.java:195)
            ... 13 more

BUILD FAILED in 1m 49s
104 actionable tasks: 4 executed, 100 up-to-date

**Comment by psibre** [comment]
Works for me on OpenJDK 12 with Gradle v5.4.1 (which is the version used by the Gradle wrapper in master -- please always build Gradle projects with the wrapper if it's there).

Are you on Windows?

**Comment by psibre** [comment]
Switching to Gradle v5.5.1 also works for us.

Could you please dump the full output of your Gradle build and attach it here as a text file?

**Comment by rkizito** [comment]
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :installerGuiStartScripts UP-TO-DATE
> Task :marytts-common:compileJava UP-TO-DATE
> Task :marytts-common:processResources UP-TO-DATE
> Task :marytts-common:classes UP-TO-DATE
> Task :marytts-common:jar UP-TO-DATE
> Task :marytts-signalproc:compileJava UP-TO-DATE
> Task :marytts-signalproc:processResources UP-TO-DATE
> Task :marytts-signalproc:classes UP-TO-DATE
> Task :marytts-signalproc:jar UP-TO-DATE
> Task :marytts-runtime:compileJava UP-TO-DATE
> Task :marytts-runtime:compileGroovy NO-SOURCE
> Task :marytts-runtime:processResources UP-TO-DATE
> Task :marytts-runtime:classes UP-TO-DATE
> Task :marytts-runtime:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:jar UP-TO-DATE
> Task :voice-cmu-slt-hsmm:compileJava NO-SOURCE
> Task :voice-cmu-slt-hsmm:generateSource UP-TO-DATE
> Task :voice-cmu-slt-hsmm:compileGroovy UP-TO-DATE
> Task :voice-cmu-slt-hsmm:generateConfig UP-TO-DATE
> Task :voice-cmu-slt-hsmm:generateServiceLoader UP-TO-DATE
> Task :voice-cmu-slt-hsmm:processResources UP-TO-DATE
> Task :voice-cmu-slt-hsmm:classes UP-TO-DATE
> Task :voice-cmu-slt-hsmm:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-de:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-en:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-fr:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-it:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:compileJava NO-SOURCE
> Task :marytts-languages:marytts-lang-lb:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-lb:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-ru:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:compileJava NO-SOURCE
> Task :marytts-languages:marytts-lang-sv:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-sv:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:compileJava UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-te:jar UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:generateComponentXmlDescriptor UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:compileJava NO-SOURCE
> Task :marytts-languages:marytts-lang-tr:generateSource UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:compileGroovy UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:generateConfig UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:generateServiceLoader UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:processResources UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:classes UP-TO-DATE
> Task :marytts-languages:marytts-lang-tr:jar UP-TO-DATE
> Task :distTar UP-TO-DATE
> Task :distZip UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE
> Task :marytts-common:assemble UP-TO-DATE
> Task :marytts-common:compileTestJava UP-TO-DATE
> Task :marytts-common:processTestResources UP-TO-DATE
> Task :marytts-common:testClasses UP-TO-DATE
> Task :marytts-common:test UP-TO-DATE
> Task :marytts-common:compileIntegrationTestJava NO-SOURCE
> Task :marytts-common:processIntegrationTestResources NO-SOURCE
> Task :marytts-common:integrationTestClasses UP-TO-DATE
> Task :marytts-common:integrationTest NO-SOURCE
> Task :marytts-common:check UP-TO-DATE
> Task :marytts-common:build UP-TO-DATE
> Task :marytts-runtime:assemble UP-TO-DATE
> Task :marytts-runtime:compileTestJava UP-TO-DATE
> Task :marytts-runtime:compileTestGroovy NO-SOURCE
> Task :marytts-runtime:processTestResources UP-TO-DATE
> Task :marytts-runtime:testClasses UP-TO-DATE
> Task :marytts-runtime:test UP-TO-DATE
> Task :marytts-runtime:compileIntegrationTestJava UP-TO-DATE
> Task :marytts-runtime:compileIntegrationTestGroovy UP-TO-DATE
> Task :marytts-runtime:processIntegrationTestResources NO-SOURCE
> Task :marytts-runtime:integrationTestClasses UP-TO-DATE
> Task :marytts-runtime:integrationTest UP-TO-DATE
> Task :marytts-runtime:check UP-TO-DATE
> Task :marytts-runtime:build UP-TO-DATE
> Task :marytts-signalproc:assemble UP-TO-DATE
> Task :marytts-signalproc:compileTestJava UP-TO-DATE
> Task :marytts-signalproc:processTestResources UP-TO-DATE
> Task :marytts-signalproc:testClasses UP-TO-DATE
> Task :marytts-signalproc:test UP-TO-DATE
> Task :marytts-signalproc:compileIntegrationTestJava NO-SOURCE
> Task :marytts-signalproc:processIntegrationTestResources NO-SOURCE
> Task :marytts-signalproc:integrationTestClasses UP-TO-DATE
> Task :marytts-signalproc:integrationTest NO-SOURCE
> Task :marytts-signalproc:check UP-TO-DATE
> Task :marytts-signalproc:build UP-TO-DATE
> Task :voice-cmu-slt-hsmm:assemble UP-TO-DATE
> Task :voice-cmu-slt-hsmm:compileTestJava UP-TO-DATE
> Task :voice-cmu-slt-hsmm:compileTestGroovy UP-TO-DATE
> Task :voice-cmu-slt-hsmm:processTestResources NO-SOURCE
> Task :voice-cmu-slt-hsmm:testClasses UP-TO-DATE

> Task :voice-cmu-slt-hsmm:test

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.CmuSltHsmmConfigTest > setup FAILED
    marytts.exceptions.MaryConfigurationException: cannot load properties
        at marytts.config.MaryConfig.<init>(MaryConfig.java:197)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfig.<init>(CmuSltHsmmConfig.java:11)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite.callConstructor(ConstructorSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:241)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfigTest.setup(CmuSltHsmmConfigTest.groovy:12)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.io.Reader.<init>(Reader.java:167)
            at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
            at java.base/java.util.Scanner.<init>(Scanner.java:566)
            at marytts.util.io.PropertiesTrimTrailingWhitespace.load(PropertiesTrimTrailingWhitespace.java:21)
            at marytts.config.MaryConfig.<init>(MaryConfig.java:195)
            ... 13 more

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.ConfigTest > canGetByName FAILED
    java.util.ServiceConfigurationError: marytts.config.MaryConfig: marytts.voice.CmuSltHsmm.CmuSltHsmmConfig Unable to get public no-arg constructor
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
        at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at marytts.config.MaryConfig.getVoiceConfig(MaryConfig.java:156)
        at marytts.voice.CmuSltHsmm.ConfigTest.canGetByName(ConfigTest.java:48)

        Caused by:
        java.lang.NoSuchMethodException: marytts.voice.CmuSltHsmm.CmuSltHsmmConfig.<init>()
            at java.base/java.lang.Class.getConstructor0(Class.java:3354)
            at java.base/java.lang.Class.getConstructor(Class.java:2156)
            at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:661)
            at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:658)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:552)
            at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:669)
            ... 6 more

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.ConfigTest > hasRightName FAILED
    marytts.exceptions.MaryConfigurationException: cannot load properties
        at marytts.config.MaryConfig.<init>(MaryConfig.java:197)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfig.<init>(CmuSltHsmmConfig.java:11)
        at marytts.voice.CmuSltHsmm.ConfigTest.hasRightName(ConfigTest.java:42)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.io.Reader.<init>(Reader.java:167)
            at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
            at java.base/java.util.Scanner.<init>(Scanner.java:566)
            at marytts.util.io.PropertiesTrimTrailingWhitespace.load(PropertiesTrimTrailingWhitespace.java:21)
            at marytts.config.MaryConfig.<init>(MaryConfig.java:195)
            ... 2 more

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.ConfigTest > hasVoiceConfigs FAILED
    java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertTrue(Assert.java:44)
        at org.testng.Assert.assertTrue(Assert.java:54)
        at marytts.voice.CmuSltHsmm.ConfigTest.hasVoiceConfigs(ConfigTest.java:55)

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.ConfigTest > hasVoiceConfigs2 FAILED
    java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertTrue(Assert.java:44)
        at org.testng.Assert.assertTrue(Assert.java:54)
        at marytts.voice.CmuSltHsmm.ConfigTest.hasVoiceConfigs2(ConfigTest.java:62)

Gradle suite > Gradle test > marytts.voice.CmuSltHsmm.ConfigTest > isVoiceConfig FAILED
    marytts.exceptions.MaryConfigurationException: cannot load properties
        at marytts.config.MaryConfig.<init>(MaryConfig.java:197)
        at marytts.voice.CmuSltHsmm.CmuSltHsmmConfig.<init>(CmuSltHsmmConfig.java:11)
        at marytts.voice.CmuSltHsmm.ConfigTest.isVoiceConfig(ConfigTest.java:36)

        Caused by:
        java.lang.NullPointerException
            at java.base/java.io.Reader.<init>(Reader.java:167)
            at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
            at java.base/java.util.Scanner.<init>(Scanner.java:566)
            at marytts.util.io.PropertiesTrimTrailingWhitespace.load(PropertiesTrimTrailingWhitespace.java:21)
            at marytts.config.MaryConfig.<init>(MaryConfig.java:195)
            ... 2 more

> Task :voice-cmu-slt-hsmm:test FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5.1/userguide/command_line_interface.html#sec:command_line_warnings
104 actionable tasks: 1 executed, 103 up-to-date

**Comment by psibre** [comment]
@rkizito Sorry, I forgot to say, please run it with `--info`. But please make sure you don't paste it into a comment in this discussion, but just *attach the file*, like it says right here at the bottom of the edit box.

**Comment by rkizito** [comment]
$gradle -v

------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          12.0.2 (Oracle Corporation 12.0.2+10)
OS:           Linux 4.15.0-20-generic amd64

$ java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

**Comment by rkizito** [comment]
Ubuntu 18

**Comment by psibre** [comment]
On a hunch, what's the output of `locale`?

**Comment by rkizito** [comment]
attachment is not working

**Comment by rkizito** [comment]
LANG=en_US.UTF-8
LC_NUMERIC=lg_UG.UTF-8

**Comment by psibre** [comment]
OK, with that locale setting, I also get some test errors. I was able to approximate your environment by building via Docker:
```
~/workspace/marytts$ docker run -it --rm -v $PWD:/work -w /work -e LANG=en_US.UTF-8 -e LC_NUMERIC=lg_UG.UTF-8 openjdk:12-oracle ./gradlew build
```
Looks like some of our code is not locale-safe... I'll open a new issue.

**Comment by rkizito** [comment]
Thanks. I still don't see why i can't upload a file.

**Comment by psibre** [comment]
Browser issue... =(

**Comment by rkizito** [comment]
[rkdump.txt](https://github.com/marytts/marytts/files/3471218/rkdump.txt)
[rkizitodump.txt](https://github.com/marytts/marytts/files/3471222/rkizitodump.txt)
 i've attached the full
