### ISSUE TITLE
wkdb_featuremaker error

### ISSUE THREAD

**Issue by ican24** [marytts/marytts#934]
Dear Team,

Firstly thank you for your great solution!  
It is a wonderful chance for all nations to develop a complete TTS, which is so important tool in the Industry 4.0 era.

Right now I am trying to adapt Armenian language to your project.
Just few steps are remaining until the finish point. 
Unfortunately in the "5. Run feature maker with the minimal NLP components" of "Adding support for a new language to MARY TTS" I met a trouble, which is not yet overcame myself.

Below is error message of wkdb_featuremaker.sh script
```
$ sudo -u mary /local/mary/marytts/target/marytts-builder-5.2/bin/wkdb_featuremaker.sh wkdb.conf
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

FeatureMaker parameters:
  -locale hy_AM
  -mysqlHost localhost
  -mysqlUser mary
  -mysqlPasswd wiki123
  -mysqlDB wiki
  -reliability strict
  -featuresForselection phone,next_phone,selection_prosody

FeatureMaker started...

Mysql driver loaded, set locale=hy_AM
Mysql connection created successfully.
    TABLE = "hy_AM_dbselection" already exists, should it be deleted (y/n)?n
    ADDING sentences TO EXISTING dbselection TABLE "hy_AM_dbselection" (y/n)?y
Starting builtin MARY TTS... MARY TTS started.

Getting list of unprocessed clean_text records from hy_AM_cleanText
Number of unprocessed clean_text records to process --> [24732]
Looping over unprocessed clean_text records from wikipedia...
TARGETFEATURES to extract: phone next_phone selection_prosody 
Starting time:23_09_2019_08:16:06

Exception in thread "main" java.lang.NullPointerException
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:202)
	at marytts.features.FeatureRegistry.getTargetFeatureComputer(FeatureRegistry.java:231)
	at marytts.tools.dbselection.FeatureMaker.main(FeatureMaker.java:170)

```
I may suppose that the issue is an empty element in line 170 of FeatureMaker.java
```
TargetFeatureComputer featureComputer = FeatureRegistry.getTargetFeatureComputer(MaryUtils.string2locale(locale),
					targetFeatures); 
```
I had tried to replace end of sentence char from ":" to "." in the "hy_AM_cleanText" table thinking that the parser is unable to split sentences, but no any change.
I am attaching one record of  "hy_AM_cleanText" table. 
[db.txt](https://github.com/marytts/marytts/files/3641129/db.txt)
I am ready to provide all required information to investigate this case.

I'll be so apprecieted, if you advise me how to fix my issue.

Thank you in advance

**Comment by ican24** [comment]
The reason was an absent of marytts-lang-hy-5.2.jar in marytts/target/marytts-builder-5.2/lib.

**Comment by ican24** [comment]
One important notification, which may save your time and nerves!

If your are using command line sample ($ wkdb_setup.sh ./ en en_US)  from "0.2 Create a wiki data directory" to create your database, you will meet featuremaker error trying to use one of language  templates (folders), for example marytts-lang-ru as it is advised in "4. Minimal NLP components for the new language", where allophoneset variable is a "xy.allophoneset" not "xy_XY.allophoneset" in 
`marytts/marytts-languages/marytts-lang-xy/src/main/resources/marytts/language/xy/xy.config`
You may fix it adding 
`xy_XY.allophoneset=jar:<your_path>`
