### ISSUE TITLE
Internal server error on generate Audio

### ISSUE THREAD

**Issue by Metti9** [marytts/marytts#958]
Hello, on this request i get following error

http://IP:59125/process?INPUT_TEXT=hallo+uhr&INPUT_TYPE=TEXT&AUDIO=WAVE&OUTPUT_TYPE=AUDIO&LOCALE=en-US&effect_Volume_parameters=amount%3D2.0%3B&effect_Volume_selected=on&VOICE=bits3

```
java.lang.Exception: Module Synthesis: Problem processing the data.
	at marytts.server.Request.processOneChunk(Request.java:568)
	at marytts.server.Request.processOrLookupOneChunk(Request.java:403)
	at marytts.server.Request.process(Request.java:337)
	at marytts.server.http.SynthesisRequestHandler.process(SynthesisRequestHandler.java:261)
	at marytts.server.http.SynthesisRequestHandler.handleClientRequest(SynthesisRequestHandler.java:91)
	at marytts.server.http.BaseHttpRequestHandler.handle(BaseHttpRequestHandler.java:138)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler$RequestHandlerAdaptor.handle(BufferingHttpServiceHandler.java:189)
	at org.apache.http.nio.protocol.SimpleNHttpRequestHandler.handle(SimpleNHttpRequestHandler.java:51)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.processRequest(AsyncNHttpServiceHandler.java:453)
	at org.apache.http.nio.protocol.AsyncNHttpServiceHandler.requestReceived(AsyncNHttpServiceHandler.java:225)
	at org.apache.http.nio.protocol.BufferingHttpServiceHandler.requestReceived(BufferingHttpServiceHandler.java:127)
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:161)
	at org.apache.http.impl.nio.DefaultServerIOEventDispatch.inputReady(DefaultServerIOEventDispatch.java:147)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:161)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:335)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:275)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:542)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: No byte value known for string [{_L]
	at marytts.util.string.ByteStringTranslator.get(ByteStringTranslator.java:146)
	at marytts.features.MaryLanguageFeatureProcessors$HalfPhoneUnitName.process(MaryLanguageFeatureProcessors.java:167)
	at marytts.features.TargetFeatureComputer.computeFeatureVector(TargetFeatureComputer.java:140)
	at marytts.unitselection.select.FFRTargetCostFunction.computeTargetFeatures(FFRTargetCostFunction.java:306)
	at marytts.unitselection.select.DiphoneFFRTargetCostFunction.computeTargetFeatures(DiphoneFFRTargetCostFunction.java:133)
	at marytts.unitselection.select.UnitSelector.selectUnits(UnitSelector.java:104)
	at marytts.unitselection.UnitSelectionSynthesizer.synthesize(UnitSelectionSynthesizer.java:177)
	at marytts.modules.synthesis.Voice.synthesize(Voice.java:527)
	at marytts.modules.Synthesis.synthesizeOneSection(Synthesis.java:252)
	at marytts.modules.Synthesis.process(Synthesis.java:222)
	at marytts.server.Request.processOneChunk(Request.java:566)
	... 19 more

```

**Comment by seblemaguer** [comment]
Hello,

is it normal that the locale is `en_US`?
