### ISSUE TITLE
Unit tests for French fail under Windows

### ISSUE THREAD

**Issue by psibre** [marytts/marytts#987]
```
C:\vagrant\marytts>gradlew :marytts-languages:marytts-lang-fr:test

> Task :marytts-languages:marytts-lang-fr:test

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testExpandOrdinal[0](2, deuxi├¿me) FAILED
    java.lang.AssertionError: expected [deuxi├¿me] but found [deuxiΦme]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:575)
        at org.testng.Assert.assertEquals(Assert.java:585)
        at marytts.language.fr.PreprocessTest.testExpandOrdinal(PreprocessTest.java:81)

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testExpandOrdinal[1](3, troisi├¿me) FAILED
    java.lang.AssertionError: expected [troisi├¿me] but found [troisiΦme]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:575)
        at org.testng.Assert.assertEquals(Assert.java:585)
        at marytts.language.fr.PreprocessTest.testExpandOrdinal(PreprocessTest.java:81)

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testExpandOrdinal[2](4, quatri├¿me) FAILED
    java.lang.AssertionError: expected [quatri├¿me] but found [quatriΦme]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.assertEqualsImpl(Assert.java:136)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:575)
        at org.testng.Assert.assertEquals(Assert.java:585)
        at marytts.language.fr.PreprocessTest.testExpandOrdinal(PreprocessTest.java:81)

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testSpellout[7](2e, deuxi├¿me) FAILED
    java.lang.AssertionError: did not expect to find [true] but found [false]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertTrue(Assert.java:43)
        at org.testng.Assert.assertTrue(Assert.java:53)
        at marytts.language.fr.PreprocessTest.testSpellout(PreprocessTest.java:67)

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testSpellout[8](3e, troisi├¿me) FAILED
    java.lang.AssertionError: did not expect to find [true] but found [false]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertTrue(Assert.java:43)
        at org.testng.Assert.assertTrue(Assert.java:53)
        at marytts.language.fr.PreprocessTest.testSpellout(PreprocessTest.java:67)

Gradle suite > Gradle test > marytts.language.fr.PreprocessTest > testSpellout[9](4e, quatri├¿me) FAILED
    java.lang.AssertionError: did not expect to find [true] but found [false]
        at org.testng.Assert.fail(Assert.java:97)
        at org.testng.Assert.failNotEquals(Assert.java:969)
        at org.testng.Assert.assertTrue(Assert.java:43)
        at org.testng.Assert.assertTrue(Assert.java:53)
        at marytts.language.fr.PreprocessTest.testSpellout(PreprocessTest.java:67)

23 tests completed, 6 failed

> Task :marytts-languages:marytts-lang-fr:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':marytts-languages:marytts-lang-fr:test'.
> There were failing tests. See the report at: file:///C:/vagrant/marytts/marytts-languages/marytts-lang-fr/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
18 actionable tasks: 1 executed, 17 up-to-date
```

**Comment by psibre** [comment]
What has me confused is why the encoding of, e.g., https://github.com/marytts/marytts/blob/9eb6f43d4e3b54cbbdcf895fd6cbd9993551c5da/marytts-languages/marytts-lang-fr/src/test/java/marytts/language/fr/PreprocessTest.java#L48-L53 causes https://github.com/marytts/marytts/blob/9eb6f43d4e3b54cbbdcf895fd6cbd9993551c5da/marytts-languages/marytts-lang-fr/src/test/java/marytts/language/fr/PreprocessTest.java#L77-L82 to fail, while the encoding of https://github.com/marytts/marytts/blob/9eb6f43d4e3b54cbbdcf895fd6cbd9993551c5da/marytts-languages/marytts-lang-lb/src/test/groovy/marytts/language/lb/LuxembourgishPreprocessTest.groovy#L36-L49 does not cause https://github.com/marytts/marytts/blob/9eb6f43d4e3b54cbbdcf895fd6cbd9993551c5da/marytts-languages/marytts-lang-lb/src/test/groovy/marytts/language/lb/LuxembourgishPreprocessTest.groovy#L91-L96 to fail. The only difference seems to be the fact that LuxembourgishPreprocessTest is written in Groovy.

**Comment by psibre** [comment]
@seblemaguer Any ideas? I don't have time to investigate right now...

**Comment by falisca** [comment]
I have the same problem, also it seems that gradle must be forced to use utf8 on windows 10 64 java8.
I forced gradle to utf8 encoding with these lines in the BuildLogic.gradle:

compileJava.options.encoding = 'UTF-8' 
compileTestJava.options.encoding = 'UTF-8'
javadoc.options.encoding = 'UTF-8'

I suspect that we must use these in other gradle files

**Comment by falisca** [comment]
Sorry i forget to say that I have the locale problem, then after adding utf8 gradle commansd I run in this bug on the tests.

**Comment by seblemaguer** [comment]
@psibre no, no idea so far but I will investigate right now

**Comment by seblemaguer** [comment]
it seems groovy is by passing the locale and forces the encoding to be in utf-8

**Comment by psibre** [comment]
Turns out it's specific to the marytts-lang-fr, not the Groovy SourceSet.

Just to be certain, I tried "converting" the French PreprocessTest to Groovy:
```
$ git status 
On branch windows-fixes
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   marytts-languages/marytts-lang-fr/src/test/groovy/marytts/language/fr/PreprocessTest.groovy

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    marytts-languages/marytts-lang-fr/src/test/java/marytts/language/fr/PreprocessTest.java

```
```diff
diff --git a/marytts-languages/marytts-lang-fr/src/test/groovy/marytts/language/fr/PreprocessTest.groovy b/marytts-languages/marytts-lang-fr/src/test/groovy/marytts/language/fr/PreprocessTest.groovy
index d87e26b69..0821faad2 100644
--- a/marytts-languages/marytts-lang-fr/src/test/groovy/marytts/language/fr/PreprocessTest.groovy
+++ b/marytts-languages/marytts-lang-fr/src/test/groovy/marytts/language/fr/PreprocessTest.groovy
@@ -3,6 +3,7 @@
  */
 package marytts.language.fr;
 
+import marytts.language.fr.Preprocess;
 import marytts.util.dom.DomUtils;
 
 import org.custommonkey.xmlunit.*;
@@ -24,32 +25,32 @@ public class PreprocessTest {
 
     @DataProvider(name = "DocData")
     private Object[][] numberExpansionDocData() {
-        return new Object[][]{{"1", "un"},
-                {"2", "deux"},
-                {"3", "trois"},
-                {"4", "quatre"},
-                {"42", "quarante-deux"},
-                {"1er", "premier"},
-                {"1re", "première"},
-                {"2e", "deuxième"},
-                {"3e", "troisième"},
-                {"4e", "quatrième"}};
+        return [["1", "un"],
+                ["2", "deux"],
+                ["3", "trois"],
+                ["4", "quatre"],
+                ["42", "quarante-deux"],
+                ["1er", "premier"],
+                ["1re", "première"],
+                ["2e", "deuxième"],
+                ["3e", "troisième"],
+                ["4e", "quatrième"]];
     }
 
     @DataProvider(name = "NumExpandData")
     private Object[][] numberExpansionDocDataCardinal() {
-        return new Object[][]{{"1", "un"},
-                {"2", "deux"},
-                {"3", "trois"},
-                {"4", "quatre"},
-                {"42", "quarante-deux"}};
+        return [["1", "un"],
+                ["2", "deux"],
+                ["3", "trois"],
+                ["4", "quatre"],
+                ["42", "quarante-deux"]];
     }
 
     @DataProvider(name = "OrdinalExpandData")
     private Object[][] numberExpansionDocDataOrdinal() {
-        return new Object[][]{{"2", "deuxième"},
-                {"3", "troisième"},
-                {"4", "quatrième"}};
+        return [["2", "deuxième"],
+                ["3", "troisième"],
+                ["4", "quatrième"]];
     }
 
     @Test(dataProvider = "DocData")
@@ -57,10 +58,10 @@ public class PreprocessTest {
         Document tokenisedDoc;
         Document expectedDoc;
         String tokens = "<maryxml xmlns=\"http://mary.dfki.de/2002/MaryXML\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"0.5\" xml:lang=\"fr\"><p><s><t>"
-                + tokenised + "</t></s></p></maryxml>";
+        + tokenised + "</t></s></p></maryxml>";
         tokenisedDoc = DomUtils.parseDocument(tokens);
         String words = "<maryxml xmlns=\"http://mary.dfki.de/2002/MaryXML\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"0.5\" xml:lang=\"fr\"><p><s><mtu orig=\""
-                + tokenised + "\"><t>" + expected + "</t></mtu></s></p></maryxml>";
+        + tokenised + "\"><t>" + expected + "</t></mtu></s></p></maryxml>";
         expectedDoc = DomUtils.parseDocument(words);
         module.checkForNumbers(tokenisedDoc);
         Diff diff = XMLUnit.compareXML(expectedDoc, tokenisedDoc);
```
But it still fails in the same way.

**Comment by psibre** [comment]
Then I tried debugging what the *actual* source file encoding is for the JavaCompile tasks is:
```diff
diff --git a/build.gradle b/build.gradle
index daff36756..e04893700 100644
--- a/build.gradle
+++ b/build.gradle
@@ -9,6 +9,12 @@ allprojects {
     repositories {
         jcenter()
     }
+
+    afterEvaluate {
+        tasks.withType(JavaCompile) {
+            println "$options.encoding $it.path"
+        }
+    }
 }
 
 apply from: 'applicationLogic.gradle'
```
And *sure enough*, the one for French is `null`:
```
> Configure project :
null :compileJava
null :compileTestJava

> Configure project :marytts-common
UTF-8 :marytts-common:compileIntegrationTestJava
UTF-8 :marytts-common:compileJava
UTF-8 :marytts-common:compileTestJava

> Configure project :marytts-runtime
UTF-8 :marytts-runtime:compileIntegrationTestJava
UTF-8 :marytts-runtime:compileJava
UTF-8 :marytts-runtime:compileTestJava

> Configure project :marytts-signalproc
UTF-8 :marytts-signalproc:compileIntegrationTestJava
UTF-8 :marytts-signalproc:compileJava
UTF-8 :marytts-signalproc:compileTestJava

> Configure project :voice-cmu-slt-hsmm
null :voice-cmu-slt-hsmm:compileIntegrationTestJava
null :voice-cmu-slt-hsmm:compileJava
null :voice-cmu-slt-hsmm:compileTestJava

> Configure project :marytts-languages:marytts-lang-de
UTF-8 :marytts-languages:marytts-lang-de:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-de:compileJava
UTF-8 :marytts-languages:marytts-lang-de:compileTestJava

> Configure project :marytts-languages:marytts-lang-en
UTF-8 :marytts-languages:marytts-lang-en:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-en:compileJava
UTF-8 :marytts-languages:marytts-lang-en:compileTestJava

> Configure project :marytts-languages:marytts-lang-fr
null :marytts-languages:marytts-lang-fr:compileIntegrationTestJava
null :marytts-languages:marytts-lang-fr:compileJava
null :marytts-languages:marytts-lang-fr:compileTestJava

> Configure project :marytts-languages:marytts-lang-it
UTF-8 :marytts-languages:marytts-lang-it:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-it:compileJava
UTF-8 :marytts-languages:marytts-lang-it:compileTestJava

> Configure project :marytts-languages:marytts-lang-lb
UTF-8 :marytts-languages:marytts-lang-lb:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-lb:compileJava
UTF-8 :marytts-languages:marytts-lang-lb:compileTestJava

> Configure project :marytts-languages:marytts-lang-ru
UTF-8 :marytts-languages:marytts-lang-ru:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-ru:compileJava
UTF-8 :marytts-languages:marytts-lang-ru:compileTestJava

> Configure project :marytts-languages:marytts-lang-sv
UTF-8 :marytts-languages:marytts-lang-sv:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-sv:compileJava
UTF-8 :marytts-languages:marytts-lang-sv:compileTestJava

> Configure project :marytts-languages:marytts-lang-te
UTF-8 :marytts-languages:marytts-lang-te:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-te:compileJava
UTF-8 :marytts-languages:marytts-lang-te:compileTestJava

> Configure project :marytts-languages:marytts-lang-tr
UTF-8 :marytts-languages:marytts-lang-tr:compileIntegrationTestJava
UTF-8 :marytts-languages:marytts-lang-tr:compileJava
UTF-8 :marytts-languages:marytts-lang-tr:compileTestJava
```
Incidentally, the same goes for `voice-cmu-slt-hsmm`.

**Comment by psibre** [comment]
The reason is to trivial it's not even funny:
```
$ find . -name build.gradle -exec grep -H buildLogic {} \;
./marytts-languages/marytts-lang-te/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-tr/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-sv/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-ru/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-it/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-en/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-de/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-languages/marytts-lang-lb/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-signalproc/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-common/build.gradle:apply from: "$rootDir/buildLogic.gradle"
./marytts-runtime/build.gradle:apply from: "$rootDir/buildLogic.gradle"
```
All of the above apply the `buildLogic.gradle` script.
But the following **no not**:
```
$ find . -name build.gradle -exec grep -L buildLogic {} \;
./marytts-languages/marytts-lang-fr/build.gradle
./voice-cmu-slt-hsmm/build.gradle
./build.gradle
./marytts-assembly/assembly-runtime/build.gradle
```
the root project and the `assembly-runtime` have an excuse (they don't compile any Java sources), but it's now clear what's going on.

**Comment by psibre** [comment]
Not sure why the `buildLogic.gradle` script was missing from those to subprojects...

Another case of Windows exposing encoding issues that were implicitly just not a problem on other build platforms.

I've opened #990 for this.

**Comment by psibre** [comment]
In this particular case, the problem would *probably* have been solved when we updated the component plugin again (see #962) and executed our plan to split out the language subprojects.
